import bs4 as bs
import requests
import math
from datetime import date

from datetime import datetime as dt
from halo import Halo
import time
import requests

from multiprocessing import Pool


# renta
# venta

urls_list = [
    "https://www.citymax-gt.com/resultados-busqueda/page/1/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/2/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/3/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/4/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/5/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/6/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/7/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/8/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/9/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/10/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/11/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/12/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/13/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/14/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/15/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/16/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/17/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/18/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/19/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/20/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/21/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/22/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/23/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/24/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/25/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/26/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/27/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/28/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/29/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/30/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/31/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/32/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/33/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/34/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/35/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/36/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/37/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/38/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/39/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/40/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/41/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/42/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/43/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/44/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/45/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/46/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/47/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/48/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/49/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/50/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/51/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/52/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/53/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/54/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/55/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/56/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/57/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/58/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/59/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/60/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/61/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/62/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/63/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/64/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/65/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/66/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/67/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/68/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/69/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/70/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/71/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/72/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/73/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/74/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/75/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/76/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/77/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/78/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/79/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/80/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/81/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/82/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/83/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/84/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/85/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/86/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/87/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/88/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/89/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/90/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/91/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/92/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/93/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/94/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/95/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/96/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/97/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/98/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/99/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/100/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/101/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/102/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/103/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/104/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/105/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/106/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/107/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/108/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/109/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/110/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/111/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/112/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/113/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/114/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/115/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/116/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/117/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/118/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/119/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/120/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/121/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/122/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/123/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/124/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/125/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/126/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/127/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/128/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/129/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/130/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/131/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/132/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/133/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/134/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/135/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/136/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/137/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/138/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/139/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/140/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/141/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/142/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/143/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/144/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/145/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/146/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/147/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/148/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/149/?status=renta",
    "https://www.citymax-gt.com/resultados-busqueda/page/150/?status=renta",
]
url = "http://localhost:1337/v2/kazas"


def laraIndex(item):
    req = requests.post(url, json=item)
    print(req.text)


max_items = 1600
urls = [
    "https://www.citymax-gt.com/60599/Alquilo-Oficina-con-102.77m2-en-Zona-10-PAO-025-03-14-2", 
"https://www.citymax-gt.com/60762/AMPLIA-OFIBODEGA-EN-RENTA-EN-ZONA-INDUSTRIAL-Z.-12", 
"https://www.citymax-gt.com/60778/APARTAMENTO-LUJOSO-EN-RENTA-EDIFICIO-ATRIUM-ZONA-10", 
"https://www.citymax-gt.com/60860/En-alquiler-oficinaen-Zona-10-Oficina-amueblada-", 
"https://www.citymax-gt.com/60863/Alquilo-Oficina-amueblada-en-Zona-10-Guatemala", 
"https://www.citymax-gt.com/57887/LOCAL-EN-RENTA-UBICADO-EN-ZONA-12", 
"https://www.citymax-gt.com/61999/KIOSCO-EN-RENTA-EN-ZONA-10-DE-GUATEMALA", 
"https://www.citymax-gt.com/58505/Rento-terreno-en-zona-12", 
"https://www.citymax-gt.com/62666/En-renta-habitaci%C3%B3n-en-casa-de-hu%C3%A9spedes-en-zona-10", 
"https://www.citymax-gt.com/60015/LOCAL-COMERCIAL-EN-RENTA-CENTRO-COMERCIAL-NUEVO-CARRETERA-EL-SALVADOR", 
"https://www.citymax-gt.com/62804/CityMax-Alquila-Oficinaen-Zona-10-", 
"https://www.citymax-gt.com/60297/Rento-casa-CERCANA-ZONA-15-Ciudad-Guatemala", 
"https://www.citymax-gt.com/75714/Oficina-enr-eta-en-zona-10-proxima-a-Av-Reforma", 
"https://www.citymax-gt.com/60402/HERMOSO-APARTAMENTO-AMUEBLADO-EN-VENTA-ZONA-14-GUATEMALA", 
"https://www.citymax-gt.com/75798/APARTAMENTO-EN-RENTA-CERCANO-A-CENTRO-MEDICO-ZONA-10", 
"https://www.citymax-gt.com/60519/Alquilo-apartamento-amueblado-en-zona-13-1-Habitaci%C3%B3n-", 
"https://www.citymax-gt.com/60871/Alquilo-apartamento-ubicado-en-zona-10", 
"https://www.citymax-gt.com/61042/Alquilo-Local-con-470.00m2-en-Zona-12-PAL-040-07-14-1", 
"https://www.citymax-gt.com/61144/Casa-o-Terreno-en-Alquiler-sobre-la-Calzada-Roosevelth-", 
"https://www.citymax-gt.com/61192/LOCAL-COMERCIAL-EN-RENTA-EN-RUTA-AL-ATL%C3%81NTICO", 
"https://www.citymax-gt.com/83791/En-renta-Bodega-en-Complejo-Industrial-en-Amatitlan", 
"https://www.citymax-gt.com/84260/Vendo-Ofibodega-en-construcci%C3%B3n-en-zona-4-Mixco", 
"https://www.citymax-gt.com/84262/Pre-Venta-de-Ofibodegas-en-zona-4-Mixco-el-Naranjo", 
"https://www.citymax-gt.com/85692/Se-Alquila-oficina-en-zona-10-bien-ubicada", 
"https://www.citymax-gt.com/87557/Oficina-en-Alquiler-en-zona-11Guatemala", 
"https://www.citymax-gt.com/91130/Local-Oficina-en-Alquiler-en-Zona-Pradera-", 
"https://www.citymax-gt.com/92402/Apartamento-amueblado-en-renta-en-Zona-14-Guatemala", 
"https://www.citymax-gt.com/105613/Alquilo-apartamento-amueblado-en-zona-10", 
"https://www.citymax-gt.com/107969/Rento-oficina-en-zona-13-Guatemala", 
"https://www.citymax-gt.com/108422/Oficina-en-Alquiler-en-Torino-Zona-10", 
"https://www.citymax-gt.com/98524/Local-disponible-para-negocio-u-oficina-en-obra-gris", 
"https://www.citymax-gt.com/98527/Oficinas-disponible-en-RENTA-dentro-de-Centro-Comercial", 
"https://www.citymax-gt.com/98531/Opci%C3%B3n-de-local-u-Oficina-en-Renta-en-la-Roosevelt", 
"https://www.citymax-gt.com/98534/Locales-disponible-en-obra-gris-en-la-Roosevelt", 
"https://www.citymax-gt.com/98843/Renta-Local-disponible-en-Plaza-Comercial-del-Naranjo-", 
"https://www.citymax-gt.com/99324/Apartamento-en-Renta-en-zona-13-al-Final-de-Hincapie", 
"https://www.citymax-gt.com/102451/Oficina-en-renta-en-la-6ta-avenida-zona-10-Hospitales", 
"https://www.citymax-gt.com/103594/Bodega-en-Renta-y-Venta-en-zona-14-La-Villa", 
"https://www.citymax-gt.com/104242/Local-en-Renta-sobre-la-Roosevelt-de-96mt2-Primer-nivel", 
"https://www.citymax-gt.com/104244/Local-en-renta-en-obra-gris-sobre-la-Roosevelt-61mt2", 
"https://www.citymax-gt.com/61570/Locales-disponibles-en-Centro-Comercial-zona-17", 
"https://www.citymax-gt.com/61572/LOCAL-EN-ALQUILER-CENTRANORTE-CARRETERA-AL-ATLANTICO", 
"https://www.citymax-gt.com/61581/Bodega-en-renta-en-zona-17-Carretera-a-el-Atl%C3%A1ntico", 
"https://www.citymax-gt.com/61587/En-RENTA-BODEGA-EN-PUNTO-ESTRAT%C3%89GICO-DE-ZONA-18", 
"https://www.citymax-gt.com/61589/KIOSKO-EN-ALQUILER-CENTRO-COMERCIAL-RUTA-AL-ATLANTICO", 
"https://www.citymax-gt.com/61590/Locales-DISPONIBLES-y-acreditados-en-Renta", 
"https://www.citymax-gt.com/61861/Alquilo-Oficina-con-70.00m2-en-Zona-10-PAO-079-07-11-12", 
"https://www.citymax-gt.com/61894/Alquilo-Oficina-con-110.00m2-en-Zona-4-PAO-031-06-15-5", 
"https://www.citymax-gt.com/62670/Alquilo-Bodega-con-306.25m2-en-Carretera-a-El-Salvador-Km.-16-al-30-PAOB-028-01-10-45", 
"https://www.citymax-gt.com/76172/LOCAL-EN-RENTA-RUTA-AL-ATLANTICO-ZONA-17-GUATEMALA-", 
"https://www.citymax-gt.com/114995/ALQUILO-TERRENO-DE-13-X-16-SOBRE-CARRETERA-EN-SAN-LUCAS", 
"https://www.citymax-gt.com/116245/APARTAMENTO-EN-RENTA-ZONA-11-UNA-HABIT.-LINEA-BLANCA", 
"https://www.citymax-gt.com/116436/ALQUILO-TERRENO-PARA-TORRE-DE-TELEFONIA-O-GASOLINERA", 
"https://www.citymax-gt.com/116703/ALQUILO-BODEGA-DE-1,400M2-EN-PUERTA-PARADA,-km-13.5", 
"https://www.citymax-gt.com/116706/SE-RENTA-AMPLIA-BODEGA-DE-1,546-M2-EN-PUERTA-PARADA", 
"https://www.citymax-gt.com/116714/SE-RENTA-BODEGA-INDUSTRIAL-DE-2946-M2-PUERTA-PARADA", 
"https://www.citymax-gt.com/118729/PREDIO-EN-ALQUILER-EN-BOSQUES-DE-SAN-NICOLAS,-MIXCO-Z-4", 
"https://www.citymax-gt.com/119771/CLINICA-EN-RENTA-ZONA-10-SIXTINO-1", 
"https://www.citymax-gt.com/122934/RENTO-LINDA-CASA-EN-ANTIGUA-GUATEMALA", 
"https://www.citymax-gt.com/123418/GRANJA-EN-RENTA-PUERTO-DE-SAN-JOSE-ESCUINTLA", 
"https://www.citymax-gt.com/89289/Locale-en-renta-en-Carretera-a-El-Salvador-km-19.5", 
"https://www.citymax-gt.com/90022/Apartamento-de-Lujo-en-alquiler-Zona-14-", 
"https://www.citymax-gt.com/93640/Amplio-apartamento-en-RENTA-en-zona-10", 
"https://www.citymax-gt.com/105159/Hermoso-apartamento-en-alquiler-zona-10", 
"https://www.citymax-gt.com/108107/Rento-oficina-tipo-co-working-amueblada-en-zona-16", 
"https://www.citymax-gt.com/110149/Local-en-renta-en-Plaza-Comercial-en-Quetzaltenango", 
"https://www.citymax-gt.com/114477/APARTAMENTO-EN-RENTA-EN-ZONA-15", 
"https://www.citymax-gt.com/114542/Bodega-en-Alquiler-en-complejo-Industrial-de-Escuintla", 
"https://www.citymax-gt.com/116248/Rento-Bodega-ubicada-en-Olintepeque-Quetzaltenango-", 
"https://www.citymax-gt.com/117999/Oficina-en-Alquiler-en-Zona-Pradera-zona-10", 
"https://www.citymax-gt.com/103186/Apartamento-en-renta-en-Valles-de-Vista-Hermosa-Zona-15", 
"https://www.citymax-gt.com/106724/Alquiler-local-para-oficina-o-cl%C3%ADnica-San-Jos%C3%A9-P%C3%ADnula", 
"https://www.citymax-gt.com/108451/Local-o-Bodega-renta-a-orilla-calle-en-USPANTAN-QUICHE", 
"https://www.citymax-gt.com/110943/Apartamento-amueblado-en-zona-15-Guatemala", 
"https://www.citymax-gt.com/110970/Aparta-estudio-amueblado-en-alquiler-zona-15-Guatemala", 
"https://www.citymax-gt.com/111731/Oficina-o-cl%C3%ADnica-en-renta-de-10-Mts2-en-Lirios-Cayal%C3%A1", 
"https://www.citymax-gt.com/111873/Amplia-oficina-en-renta-en-Zona-Pradera-de-195.72-Mts2", 
"https://www.citymax-gt.com/112548/Rento-Oficina-Comercial-en-zona-9-sobre-Avenida-Reforma", 
"https://www.citymax-gt.com/112786/Se-Renta-Edificio-en-zona-12-Sobre-Avenida-Petapa", 
"https://www.citymax-gt.com/113623/Edificio-de-6-niveles-en-Renta-en-Zona-5-San-Pedrito", 
"https://www.citymax-gt.com/118921/Local-comercial-en-Renta-en-zona-6-sobre-la-15-avenida", 
"https://www.citymax-gt.com/119737/LOCAL-EN-ALQUILER-en-zona-5-ideal-para-Auto-Servicio", 
"https://www.citymax-gt.com/121057/Apartamento-en-renta-en-nivel-1-con-jardín-en-zona-10", 
"https://www.citymax-gt.com/121058/Apartamento-en-renta-con-jardín-en-la-zona-10", 
"https://www.citymax-gt.com/121059/Apartamento-en-renta-con-línea-blanca-en-zona-10-nuevos", 
"https://www.citymax-gt.com/122886/Local-en-RENTA-centro-comercial-en-zona-5", 
"https://www.citymax-gt.com/123218/Apartamento-en-renta-en-zona-13-al-final-las-Américas", 
"https://www.citymax-gt.com/123704/En-Alquiler-Ofi-Bodega-zona-2-de-Mixco-La-Escuadrilla-", 
"https://www.citymax-gt.com/123852/Céntrico-apartamento-en-zona-5-de-3-habitaciones", 
"https://www.citymax-gt.com/124551/Alquiler-de-apartamentos-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/57262/Se-alquila-oficina-en-zona-10-sobre-13-calle-", 
"https://www.citymax-gt.com/57310/Alquilo-Oficina-con-68.00m2-en-Zona-10-PAO-058-01-12", 
"https://www.citymax-gt.com/59237/renta-Apartamento-Zona-10-en-el-centro-de-la-zona-VIVA", 
"https://www.citymax-gt.com/59581/Oficina-en-Renta-en-la-19-calle-zona-10-Edifico-", 
"https://www.citymax-gt.com/59977/Oficina-en-alquiles-en-Edificio-ejecutivo-en-zona-14", 
"https://www.citymax-gt.com/60116/OFICINA-EN-RENTA-EN-ZONA-15-VISTA-HERMOSA-GUATEMALA", 
"https://www.citymax-gt.com/61190/Local-en-Renta-en-Carretera-al-Atl%C3%A1ntico-en-la-carreter", 
"https://www.citymax-gt.com/61391/Alquilo-Apartamento-con-149.57m2-en-Zona-10-PAA-019-11-14", 
"https://www.citymax-gt.com/61617/Edificio-en-renta-en-zona-18-Carretera-al-Atlantico", 
"https://www.citymax-gt.com/62386/Alquilo-Apartamento-con-125.00m2-en-Zona-10-PAA-041-04-10-16", 
"https://www.citymax-gt.com/61410/Apartamento-en-Alquiler-en-Muxbal-entorno-ecol%C3%B3gico", 
"https://www.citymax-gt.com/62440/50-ESTACIONES-DE-TRABAJO-EN-CALL-CENTER-ZONA-13-EN-RENTA", 
"https://www.citymax-gt.com/62450/100-ESTACIONES-DE-TRABAJO-EN-RENTA-EN-CALL-CENTER-ZONA-13", 
"https://www.citymax-gt.com/62451/200-ESTACIONES-DE-TRABAJO-EN-ALQUILER-EN-CALL-CENTER-ZONA-13", 
"https://www.citymax-gt.com/75909/CASA-VACACIONAL-EN-RENTA-EN-LIKIN-PUERTO-DE-SAN-JOSE", 
"https://www.citymax-gt.com/83038/Alquilo-Oficina-sobre-Carretera-a-El-Salvador-Guatemala", 
"https://www.citymax-gt.com/83041/Alquilo-Oficina-con-93.55m2-Carretera-El-Salvador", 
"https://www.citymax-gt.com/83043/Alquilo-Oficina-Carretera-El-Salvador-Ciudad-Guatemala", 
"https://www.citymax-gt.com/83439/CITYMAX-RENTA-OFICINA-EN-ZONA-PRADERA-84.50MTS", 
"https://www.citymax-gt.com/85177/Renta-Local-Comercial-en-Centro-Historico-Z.1", 
"https://www.citymax-gt.com/112515/Oficina-en-renta-en-Insigne-zona-15", 
"https://www.citymax-gt.com/113110/Oficina-CoWorking-renta-en-edificio-de-zona-10-Ciudad", 
"https://www.citymax-gt.com/114753/Oficina-en-alquiler-zona-10-zona-Pradera", 
"https://www.citymax-gt.com/115801/Oficina-en-Alquiler-en-Zona-10,-Amplia-e-iluminada!!", 
"https://www.citymax-gt.com/116628/CityMax-alquila-AMPLIO-apartamento-edificio-zona-14", 
"https://www.citymax-gt.com/117738/CityMax-alquila-excelente-local-en-plaza-de-zona-12", 
"https://www.citymax-gt.com/117739/Locales-comerciales-en-USAC-zona-12", 
"https://www.citymax-gt.com/117740/Alquilo-Kiosco-en-plaza-comercial-de-zona-12-Guatemala", 
"https://www.citymax-gt.com/117741/Alquiler-de-local-en-plaza-de-zona-12-Ciudad-Guatemala", 
"https://www.citymax-gt.com/117742/Local-comercial-en-renta-plaza-zona-12", 
"https://www.citymax-gt.com/79405/KIOSKO-EN-RENTA-ZONA-10-CERCANO-A-PRADERA-", 
"https://www.citymax-gt.com/81697/Bonita-oficina-en-renta-en-Zona-Pradera-zona-10", 
"https://www.citymax-gt.com/82348/Oficina-en-RENTA-edificio-exclusivo-en-zona-10", 
"https://www.citymax-gt.com/90031/Renta-amplio-local-de-201.63mts-en-C.C.-Xela-", 
"https://www.citymax-gt.com/90406/CityMax-renta-Lindo-Apartamento-en-zona-10", 
"https://www.citymax-gt.com/104223/Alquilo-apartamento-amueblado-zona-10-Guatemala", 
"https://www.citymax-gt.com/105116/Alquiler-apartamento-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/105153/Apartamento-en-zona-10-para-alquilar", 
"https://www.citymax-gt.com/107745/Local-comercial-en-renta-en-zona-7-Calzada-San-Juan", 
"https://www.citymax-gt.com/108704/Oficina-en-renta-en-GEMINIS-10-zona-10", 
"https://www.citymax-gt.com/104246/Local-en-renta-listo-con-acabados-sobre-la-Roosevelt-", 
"https://www.citymax-gt.com/105384/Alquilo-bodega-en-complejo-San-Jos%C3%A9-Pinula-", 
"https://www.citymax-gt.com/105825/Oficina-en-Alquiler-en-Avenida-Reforma-Zona-9-Guatemala", 
"https://www.citymax-gt.com/105826/Oficina-de-1786-Mts-en-Renta-en-la-zona-9-Ave.-Reforma", 
"https://www.citymax-gt.com/105828/Oficina-en-Renta-en-la-Zona-10-de-289-m2-TABICADA", 
"https://www.citymax-gt.com/105918/Apartamento-amueblado-en-renta-en-zona-15-Vista-Hermosa", 
"https://www.citymax-gt.com/106233/Ofibodega-en-Alquiler-en-Km-32-Amatitl%C3%A1n", 
"https://www.citymax-gt.com/106264/Renta-de-Oficina-en-la-Calzada-Roosevelt-zona-11", 
"https://www.citymax-gt.com/107781/Local-comercial-en-renta-en-zona-7-Calzada-San-Juan", 
"https://www.citymax-gt.com/108673/Oficina-en-Renta-en-zona-10-sobre-la-6ta-avenida-", 
"https://www.citymax-gt.com/76173/LOCAL-COMERCIAL-EN-RENTA-RUTA-AL-ATLANTICO-", 
"https://www.citymax-gt.com/76174/LOCAL-EN-RENTA-ZONA-17-RUTA-AL-ATLANTICO-", 
"https://www.citymax-gt.com/76603/SE-RENTA-Edificio-Comercial-Industrial-en-Zona-18", 
"https://www.citymax-gt.com/81121/Casa-en-rentasobre-la-Simeon-Ca%C3%B1as-zona-2", 
"https://www.citymax-gt.com/81416/Bodega-en-renta-en-zona-2-Alquila-en-Complejo-seguridad", 
"https://www.citymax-gt.com/81741/Alquilo-excelente-Local-en-carretera-a-El-Salvador", 
"https://www.citymax-gt.com/82711/Rento-bodega-en-Carretera-a-El-Salvador-km.20-", 
"https://www.citymax-gt.com/83039/Alquilo-Oficina-con-62.81m2-en-Carretera-El-Salvador", 
"https://www.citymax-gt.com/83606/Alquilo-oficina-en-zona-15-Guatemala", 
"https://www.citymax-gt.com/84742/Alquilo-local-comercial-en-calzada-Roosevelt", 
"https://www.citymax-gt.com/123443/ALQUILO-PREDIO-EN-EL-PUERTO-DE-SAN-JOSE,-ESCUINTLA-", 
"https://www.citymax-gt.com/123959/LOCAL-COMERCIAL-EN-RENTA-EN-AMATITLAN", 
"https://www.citymax-gt.com/123961/LOCAL-COMERCIAL-EN-AMATITLAN-EN-ALQUILER-", 
"https://www.citymax-gt.com/124587/BODEGAS-EN-ALQUILER-LIBRAMIENTO-CHIMALTENANGO", 
"https://www.citymax-gt.com/124980/FRESCO-APARTAMENTO-EN-VISTA-BELLA-KM-9.5-AL-SALVADOR", 
"https://www.citymax-gt.com/125008/RENTA-BODEGA-1,200Mts-EN-LIBRAMIENTO-CHIMALTENANGO", 
"https://www.citymax-gt.com/125009/BODEGA-INDUSTRIAL-DE-2,000-METROS-RUTA-A-OCCIDENTE", 
"https://www.citymax-gt.com/126754/Alquiler-local-esquina-para-franquicia,-puerto-san-José", 
"https://www.citymax-gt.com/127559/Local-CC-LOS-PROCERES-zona-10-se-alquila,--en-nivel-3", 
"https://www.citymax-gt.com/127687/Renta--bello-apartamento-nuevo-en-renta-IQ10-zona-10", 
"https://www.citymax-gt.com/119119/Alquilo-oficina-tabicada-en-zona-10", 
"https://www.citymax-gt.com/119146/oficina-con-185-m2-en-Renta-en-nivel-Alto-de-la-Zona-10", 
"https://www.citymax-gt.com/119967/CityMax-alquila-apartamento-en-zona-14-Guatemala", 
"https://www.citymax-gt.com/121268/CityMax-alquila-apartamento-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/123703/RENTA-DE-OFICINA-IDEAL-PARA-CLINICA-MEDICA-EN-ZONA-9", 
"https://www.citymax-gt.com/126244/Apartamento-Nuevo-y-Amueblado-en-zona-14", 
"https://www.citymax-gt.com/127771/RENTA--APARTAMENTO-DE-3-HABITACIONES-EN-ZONA-15-VH2", 
"https://www.citymax-gt.com/129071/ALQUILER-DE-APARTAMENTO-AMUEBLADO-EN-TORRENOVA-ZONA-13", 
"https://www.citymax-gt.com/55536/Apartamento-en-Renta-Promociona-CITYMAX-en-la-Zona-10", 
"https://www.citymax-gt.com/55901/APARTAMENTO-3-HAB.-EN-ALQUILER-ZONA-14", 
"https://www.citymax-gt.com/113857/Terreno-uso-Comercial-Renta-en-Guastatoya-El-Progreso", 
"https://www.citymax-gt.com/115057/Rento-Ofibodega-de-981Mts-en-Esquipulas,-Chiquimula-", 
"https://www.citymax-gt.com/116709/Apartamentos-en-renta-en-zona-1", 
"https://www.citymax-gt.com/117998/Alquilo-lindas-oficinas-en-Zona-Pradera-zona-10", 
"https://www.citymax-gt.com/118000/Rento-oficina-154Mts-en-ZONA-PRADERA-zona-10", 
"https://www.citymax-gt.com/119034/Oficina-en-Alquiler-Zona-10-Guatemala", 
"https://www.citymax-gt.com/120205/Rento-Oficina-en-Zona-Pradera-zona-10", 
"https://www.citymax-gt.com/120921/Apartamento-AMUEBLADO-en-Alquiler-en-Zona-4-QUO", 
"https://www.citymax-gt.com/121064/Oficina-o-local-comercial-en-Renta-en-Lirios-de-Cayalá-", 
"https://www.citymax-gt.com/122800/Rento-Amplio-Apartamento-de-200-Mts2-en-Solaria-Zona-16", 
"https://www.citymax-gt.com/125474/Apartamento-en-Alquiler-en-Zona-5-San-Pedrito", 
"https://www.citymax-gt.com/126476/Local-de-90-mt2-en-alquiler-en-zona-9,-cerca-a-12-calle", 
"https://www.citymax-gt.com/126519/Oficina-nueva-en-renta-en-zona-9-sector-Montufar", 
"https://www.citymax-gt.com/126520/Oficina-nueva-en-renta-en-zona-9,-cerca-a-la-7-Avenida", 
"https://www.citymax-gt.com/126521/Oficina-de-71-mts-en-alquiler-en-el-centro-de-la-zona-9", 
"https://www.citymax-gt.com/126639/Local-comercial-en-Renta-en-El-Naranjo-Mixco", 
"https://www.citymax-gt.com/127941/Bodega-en-renta-en-zona-5-Calzada-la-Paz-", 
"https://www.citymax-gt.com/128752/Apartamento-en-renta-en-Ancona-al-Final-San-Cristobal", 
"https://www.citymax-gt.com/56470/Alquilo-Apartamento-con-161.65m2-en-Zona-14-PAA-011-01-11-4", 
"https://www.citymax-gt.com/57175/OFICINA-EN-RENTAZONA-4-DE-MIXCO-EL-NARANJO-", 
"https://www.citymax-gt.com/62459/Bodega-industrial-en-renta-en-km-98-Puerto-Quetzal", 
"https://www.citymax-gt.com/62547/Alquilo-OFIBODEGA-en-MUXBAL-km-8-de-3-niveles", 
"https://www.citymax-gt.com/62671/cityMax-renta-ofibodega-en-Carretera-a-El-Salvador-km22", 
"https://www.citymax-gt.com/62912/Local-en-Renta-en-zona-9-Cerca-al-Comercial-Montufar", 
"https://www.citymax-gt.com/74879/Alquilo-Bodega-con-200.00m2-en-Zona-12-PAB-036-06-16", 
"https://www.citymax-gt.com/75716/Se-renta-Ofibodega-en-la-zona-7-dentro-de-condominio", 
"https://www.citymax-gt.com/79411/Local-en-zona-10-en-s%C3%B3tano-en-Plaza-en-Alquiler", 
"https://www.citymax-gt.com/79412/Alquilo-local-tipo-kiosko-en-zona-10", 
"https://www.citymax-gt.com/81053/C%C3%A9ntrica-y-c%C3%B3moda-oficina-en-RENTA-en-Zona-10-", 
"https://www.citymax-gt.com/82781/Se-renta-oficina-en-zona-14-sobre-La-Am%C3%A9ricas-", 
"https://www.citymax-gt.com/85178/se-ALQUILA-Local-en-la-zona-1-De-Guatemala", 
"https://www.citymax-gt.com/86573/CLINICA-EN-RENTA-EN-ZONA-10-EQUIPADA", 
"https://www.citymax-gt.com/92819/Local-en-renta-Plaza-comercial-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/92842/Local-comercial-en-alquiler-Plaza-comercial-km-13.5-CES", 
"https://www.citymax-gt.com/96118/Casa-en-renta-sobre-el-Bulevar-Vista-Hermosa-en-zona-15", 
"https://www.citymax-gt.com/96145/Casa-en-renta-en-zona-15-sobre-Bulevar-Vista-Hermosa-", 
"https://www.citymax-gt.com/99367/Renta-de-Bodega-o-loca-en-zona-1-sobre-la-3era-avenida-", 
"https://www.citymax-gt.com/99679/RENTO-CASA-EN-VILLAS-CAMPESTRE-II-FRAIJANES-GUATEMALA", 
"https://www.citymax-gt.com/99727/Oficina-en-alquiler-en-edificio-bien-ubicado-en-zona-10", 
"https://www.citymax-gt.com/101468/Alquilo-Local-Comercial-Cerca-de-Parque-de-Chiquimula-", 
"https://www.citymax-gt.com/119734/ALQUILER-DE-LOCAL-En-zona-5-Centro-Comercial", 
"https://www.citymax-gt.com/124362/Apartamento-en-Alquiler-Condado-La-Villa-Zona-14", 
"https://www.citymax-gt.com/126442/CityMax-renta-de-oficina-en-Plaza-ubicada-en-zona-10", 
"https://www.citymax-gt.com/127312/Alquiler-de-Clínica-médica-zonas-10-Guatemala", 
"https://www.citymax-gt.com/129590/Apartamento-en-Renta-Serena-de-Arrazola-CES", 
"https://www.citymax-gt.com/56258/Alquilo-Apartamento-en-Zona-14-amueblado", 
"https://www.citymax-gt.com/58786/Bodega-en-renta-o-venta-Km.-29-Pal%C3%ADn-Guatemala", 
"https://www.citymax-gt.com/58895/Rento-local-u-oficina-en-zona-1", 
"https://www.citymax-gt.com/58903/Local-en-renta-en-zona-1-Centro-Hist%C3%B3rico-Guatemala-", 
"https://www.citymax-gt.com/60117/LUJOSA-OFICINA-EN-RENTA-EN-ZONA-15-CIUDAD-GUATEMALA", 
"https://www.citymax-gt.com/110811/Amplia-oficina-en-alquiler-zona-10-Zona-Viva-Guatemala", 
"https://www.citymax-gt.com/112610/Amplio-local-en-renta-en-Plaza-Comercial-en-zona-12-Pe", 
"https://www.citymax-gt.com/112778/Local-Comercial-en-Renta-en-en-Plaza,-zona-12-Av-Patapa", 
"https://www.citymax-gt.com/113109/Alquilo-oficina-Amueblada-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/114487/Rento-lindo-apartamento-en-edificio-de-zona-10", 
"https://www.citymax-gt.com/114754/Oficina-tipo-Coworking-en-Zona-Pradera-Zona-10-en-renta", 
"https://www.citymax-gt.com/114755/Espacio-de-Oficina-en-Renta-Zona-Pradera-Zona-10", 
"https://www.citymax-gt.com/114770/Apartamento-en-Alquiler-en-Avenida-las-Americas-Z.13", 
"https://www.citymax-gt.com/117272/Oficina-corporativa-en-renta-Zona-10", 
"https://www.citymax-gt.com/118001/Linda-oficina-en-alquiler-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/85088/LOCAL-ANCLA-EN-ALQUILER-EN-PLAZA-COMERCIAL-ZONA-18-", 
"https://www.citymax-gt.com/85089/CITYMAX-RENTA-LOCAL-IDEAL-AGENCIA-DE-BANCO-EN-ZONA-18-", 
"https://www.citymax-gt.com/85090/SE-ALQUILA-LOCAL-EN-SEGUNDO-NIVEL-EN-ZONA-17", 
"https://www.citymax-gt.com/85181/Local-en-Promocion-de-Alquiler-en-la-Zona-1-Guatemala", 
"https://www.citymax-gt.com/85621/Bodega-en-renta-con-306.25m2-en-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/89091/CityMax-Renta-Local-en-Centro-Comercial-en-la-zona-1-", 
"https://www.citymax-gt.com/89111/Preciosa-y-amplia-casa-en-Renta-en-Elgin-II-zona-13", 
"https://www.citymax-gt.com/89340/En-Renta-amplio-local-comercial-en-zona-1", 
"https://www.citymax-gt.com/89474/En-renta-local-en-Centro-comercial-zona-18", 
"https://www.citymax-gt.com/89487/CityMax-renta-bodega-en-zona-2-El-Zapote", 
"https://www.citymax-gt.com/110262/Terreno-en-Renta-en-San-Bartolom%C3%A9-Milpas-Altas-", 
"https://www.citymax-gt.com/110750/Oficina-en-Renta-en-zona-10-Edificio-Ejecutivo-", 
"https://www.citymax-gt.com/110986/Oficina-en-Alquiler-en-Zona-4-de-Guatemala", 
"https://www.citymax-gt.com/110992/Rento-Oficina-en-la-zona-4-de-Guatemala", 
"https://www.citymax-gt.com/110994/Oficina-con-90.77-m2-de-Construcci%C3%B3n-en-Renta-Zona-4", 
"https://www.citymax-gt.com/111603/Local-comercial-en-Renta-en-zona-9,-Cerca-a-Montufar", 
"https://www.citymax-gt.com/112211/Ofibodega-en-Venta-en-zona-5-Dentro-de-Complejo", 
"https://www.citymax-gt.com/113707/Alquilo-bodega--ubicada-en-Amatitlán", 
"https://www.citymax-gt.com/113719/Rento-bodega-en-Amatitlán-Guatemala", 
"https://www.citymax-gt.com/115323/Oficina-compartida-en-renta-en-Torre-profesional-zona-4", 
"https://www.citymax-gt.com/127888/Clínica-en-alquiler-en-Zona-Medica-zona-9-tabicada", 
"https://www.citymax-gt.com/128377/Casa-comercial-frente-hospital-San-Juan-de-Dios-RENTA", 
"https://www.citymax-gt.com/129506/Local-en-alquiler-San-José-Pinula", 
"https://www.citymax-gt.com/56314/Alquilo-bonito-apartamento-en-zona-10-GT", 
"https://www.citymax-gt.com/56336/Alquilo-Apartamento-amueblado-con-300Mts-en-Zona-13", 
"https://www.citymax-gt.com/56399/Hermoso-Apartamento-en-Renta-en-la-Zona-14-Guatemala", 
"https://www.citymax-gt.com/56467/Alquilo-Apartamento-con-65.00m2-en-Zona-13-PAA-040-04-12", 
"https://www.citymax-gt.com/57289/En-renta-Oficina-en-zona-10-bien-ubicada", 
"https://www.citymax-gt.com/57527/Alquilo-Oficina-en-edificio-de-zona-13-Guatemala", 
"https://www.citymax-gt.com/57535/Alquilo-oficina-amueblada-en-zona-14", 
"https://www.citymax-gt.com/123474/Rento-Apartamento-en-la-Zona-15-Vista-Hermosa-Amueblado", 
"https://www.citymax-gt.com/125950/Apartamento-en-Renta-de-400-Mts2--en-Tiffany-Zona-10", 
"https://www.citymax-gt.com/126853/Casa-en-Renta-Grande-de-2-Niveles-uso-Mixto-en-Zona-3", 
"https://www.citymax-gt.com/127101/Edificio-en-renta-para-oficinas-en-zona-10!!", 
"https://www.citymax-gt.com/127509/Oficina-en-Renta-para-Estrenar-en-Edificio-Nova-Zona-9", 
"https://www.citymax-gt.com/128104/Terreno-en-Renta-en-Palencia-sobre-calle-Principal", 
"https://www.citymax-gt.com/129191/Local-Comercial-en-Renta-en-Excelente-Punto-en-Zona-1", 
"https://www.citymax-gt.com/129594/Apartamento-en-Alquiler-en-Zona-15-V.H.I", 
"https://www.citymax-gt.com/129595/Apartamento-en-Alquiler-Zona-15-V.H.-I-", 
"https://www.citymax-gt.com/129596/APARTAMENTO-EN-RENTA-EN-ZONA-15-DE-2-HABITACIONES", 
"https://www.citymax-gt.com/56049/CityMax-alquila-Apartamento-en-la-ZONA-15", 
"https://www.citymax-gt.com/56460/Alquilo-o-Vendo-apartamento-amueblado-en-zona-10", 
"https://www.citymax-gt.com/57045/Alquilo-hermosa-casa-amueblada-en-Izabal-Guatemala", 
"https://www.citymax-gt.com/57173/CityMax-Renta-Oficina-con-103Mts-en-Zona-15-Guatemala", 
"https://www.citymax-gt.com/57174/Rento-Oficina-con-212Mts-en-Zona-15-Guatemala", 
"https://www.citymax-gt.com/57265/Alquilo-oficina-en-zona-10-%C2%A1oficina-c%C3%A9ntrica", 
"https://www.citymax-gt.com/57344/Alquilo-Oficina-con-69.27m2-en-Zona-10-PAO-001-10-09-TII-37", 
"https://www.citymax-gt.com/57533/OFICINA-AMUEBLADA-EN-EDIFICIO-ZONA-14", 
"https://www.citymax-gt.com/57544/cityMax-Renta-oficina-en-zona-14-Ciudad-de-Guatemala", 
"https://www.citymax-gt.com/57618/Local-en-Renta-en-la-zona-10-%C2%A1Edificio-bien-ubicado", 
"https://www.citymax-gt.com/82942/Oficina-en-CENTRO-HIST%C3%93RICO-sobre-la-7-avenida-zona-1", 
"https://www.citymax-gt.com/84653/Apartamento-en-renta-en-km-9-Carretera-al-Salvador", 
"https://www.citymax-gt.com/87190/Casa-en-AlquilerVista-Hermosa-II-zona-15-por-CITYMAX", 
"https://www.citymax-gt.com/87269/Local-en-%C3%A1rea-de-Foodcourt-ya-disponible-con-acabados-", 
"https://www.citymax-gt.com/87344/Se-renta-oficina-nueva-con-piso-y-acabados-en-zona-10", 
"https://www.citymax-gt.com/87345/Oficina-nueva-en-alquiler-en-zona-10-Los-Proceres", 
"https://www.citymax-gt.com/87556/Oficina-Comercial-en-Alquiler-en-la-Zona-11-Roosevelt", 
"https://www.citymax-gt.com/88380/Ofibodega-dentro-de-complejo-en-renta-zona-12-Petapa", 
"https://www.citymax-gt.com/89237/Local-ancla-en-renta-en-zona-5-Bulevar-Asunci%C3%B3n", 
"https://www.citymax-gt.com/90363/Oficina-Nueva-en-Renta-en-zona-15-cuenta-con-acabados-", 
"https://www.citymax-gt.com/57258/OFICINA-AMPLIA-EN-RENTA-EN-EDIFICIO-Z.10-", 
"https://www.citymax-gt.com/58191/Alquilo-Bodega-en-Zona-11-PAOB-032-04-09-9", 
"https://www.citymax-gt.com/58224/Bodega-en-Renta-en-sobre-Carretera-al-Atl%C3%A1ntico", 
"https://www.citymax-gt.com/59343/Alquilo-Apartamento-con-193.00m2-en-Zona-14-", 
"https://www.citymax-gt.com/59378/Alquilo-Oficina-con-68.00m2-en-Zona-10-PAO-079-07-11-6", 
"https://www.citymax-gt.com/59547/Alquilo-Oficina-con-13.00m2-en-Zona-10-PAO-079-07-11-7", 
"https://www.citymax-gt.com/59826/Oficina-en-edificio-exclusivo-%C2%A1Rento-zona-10", 
"https://www.citymax-gt.com/61186/Local-en-Renta-en-Centro-Comercial-de-la-zona-10-", 
"https://www.citymax-gt.com/61584/CITYMAX-RENTA-bodegas-en-KM-8-al-Atlantico", 
"https://www.citymax-gt.com/61586/BODEGA-EN-RENTA-ZONA-17", 
"https://www.citymax-gt.com/101678/Ofibodega-en-Alquiler-en-Km-13.8-Carretera-El-Salvador", 
"https://www.citymax-gt.com/104148/Ofiespacio-en-Renta-zona-12-", 
"https://www.citymax-gt.com/104583/OFIBODEGA-EN-ALQUILER-A-200-M-CALZADA-ROOSEVELT", 
"https://www.citymax-gt.com/105404/Bodega-en-Alquiler-en-Zona-el-Cortijo-Zona-12", 
"https://www.citymax-gt.com/106722/Alquiler-oficina-o-clinica-en-San-Jos%C3%A9-P%C3%ADnula-", 
"https://www.citymax-gt.com/108328/Parqueo-en-renta-en-San-Jose-Pinula-en-v%C3%ADa-principal", 
"https://www.citymax-gt.com/108382/ALQUILO-TERRENO-PARA-PREDIO-EN-CHIQUIMULA", 
"https://www.citymax-gt.com/114075/Alquiler-de-Oficina-en-Renta-en-Zona-Pradera-zona-10", 
"https://www.citymax-gt.com/114533/RENTO-TERRENO-COMERCIAL-EN-ZONA-14-SECTOR-LA-VILLA-", 
"https://www.citymax-gt.com/114536/TERRENO-COMERCIAL-EN-SANTA-CATARINA-PINULA", 
"https://www.citymax-gt.com/60127/Rento-apartamento-en-zona-14-Amueblado", 
"https://www.citymax-gt.com/60244/LOCAL-COMERCIAL-EN-RENTA-RI%C3%93-HONDO-ZACAPA-GUATEMALA.", 
"https://www.citymax-gt.com/60245/Alquilo-Local-en-Rio-Hondo-Zacapa-", 
"https://www.citymax-gt.com/60246/Alquilo-Local-con-250.00m2-en-Zacapa-Rio-Hondo", 
"https://www.citymax-gt.com/60252/Alquilo-Local-ComercialR%C3%ADo-Hondo-Zacapa", 
"https://www.citymax-gt.com/60661/LOCAL-TOTALMENTE-TABICADO-EN-CENTRO-COMERCIAL-ZONA-1-GUATEMALA", 
"https://www.citymax-gt.com/61194/Rento-Local-con-Comercial-en-El-Rancho-El-Progreso", 
"https://www.citymax-gt.com/61197/Rento-local-en-Ruta-al-Atl%C3%A1ntico", 
"https://www.citymax-gt.com/61568/LOCAL-EN-ALQUILER-CARRETERA-AL-ATL%C3%81NTICO", 
"https://www.citymax-gt.com/61569/Local-ACREDITADO-En-Centro-Comercial-RENTA-zona-17", 
"https://www.citymax-gt.com/118695/CityMax-renta-oficina-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/119029/Oficina-de-97-m2-en-RENTA-en-Zona-10", 
"https://www.citymax-gt.com/119066/Alquilo-oficina-en-Murano-Center-Zona-10-Guate", 
"https://www.citymax-gt.com/119176/Apartamento-NUEVO-en-alquiler-zona-14", 
"https://www.citymax-gt.com/119601/Alquiler-Local-clínica-en-zona-10", 
"https://www.citymax-gt.com/122955/Clínica-Medica-en-Alquiler-a-ESTRENAR-Renovati-Zona-10", 
"https://www.citymax-gt.com/125369/Apartamento-en-zona-10-cerca-Los-Proceres", 
"https://www.citymax-gt.com/125667/Renta-de-Apartamento-Amueblado-en-Mira-Zona-10", 
"https://www.citymax-gt.com/126697/Apartamento-nuevo-en-Renta-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/128649/Renta-edificio,-bodega-y-oficinas-en-zona-13", 
"https://www.citymax-gt.com/90774/Apartamento-en-renta-zona-1-Guatemala", 
"https://www.citymax-gt.com/91229/Local-en-renta-en-centro-comercial-zona-17-Guatemala-", 
"https://www.citymax-gt.com/91232/Kiosco-en-Alquiler-centro-comercial-en-zona-17", 
"https://www.citymax-gt.com/93051/Apartamento-en-Renta-en-Zona-1-Torre-Entre-Arboles", 
"https://www.citymax-gt.com/93917/RENTO-Apartamento-bien-ubicado-en-zona-15", 
"https://www.citymax-gt.com/94586/Alquilo-apartamento-amueblado-en-Z15", 
"https://www.citymax-gt.com/96080/Alquilo-oficina-en-edificio-de-zona-9", 
"https://www.citymax-gt.com/98792/Apartamento-remodelado-en-venta-amueblado-en-Zona-10", 
"https://www.citymax-gt.com/100855/Oficina-en-renta-Design-Center-68-metros-amueblada", 
"https://www.citymax-gt.com/101123/Casa-en-Renta-Tipo-Colonial-en-Antigua-Guatemala", 
"https://www.citymax-gt.com/115446/Local-Comercial-ideal-para-ancla-sobre-la-Roosevelt-", 
"https://www.citymax-gt.com/115604/Oficina-o-clínica-en-renta-en-zona-10-Edificio-Sixtino", 
"https://www.citymax-gt.com/115690/Local-en-renta-de-550-mt2-en-zona-7-sobre-la-Roosevelt", 
"https://www.citymax-gt.com/115905/Alquiler-de-Bodega-Complejo-Industrial-de-Escuintla!!!!", 
"https://www.citymax-gt.com/116718/Apartamento-de-3-habitaciones-en-alquiler-en-zona-7-", 
"https://www.citymax-gt.com/116719/Se-alquila-Apartamento-zona-7-cerca-a-la-Roosevelt--", 
"https://www.citymax-gt.com/116759/Oficina-en-renta-en-zona-9-sobre-la-7-avenida-", 
"https://www.citymax-gt.com/116952/Oficina-en-renta-en-zona-4-Torre-Profesional-", 
"https://www.citymax-gt.com/117997/Rento-oficina-tabicada-en-Zona-Pradera-zona-10", 
"https://www.citymax-gt.com/118746/Casa-en-Alquiler-en-zona-6-Guatemala", 
"https://www.citymax-gt.com/59133/APARTAMENTO-EN-RENTA-UBICADO-EN-ZONA-10-CERCANO-OCKLAND-MALL-GUATEMALA", 
"https://www.citymax-gt.com/59794/Alquilo-Oficina-con-48.00m2-en-Zona-10-PAO-079-07-11-10", 
"https://www.citymax-gt.com/60701/Alquilo-Apartamento-amueblado-de-208mt2-con-balc%C3%B3n-", 
"https://www.citymax-gt.com/61557/OFICINA-EN-ALQUILER-ZONA-13-CIUDAD-GUATEMALA-", 
"https://www.citymax-gt.com/61621/Apartamento-en-alquiler-Nivel-Alto-Zona-10", 
"https://www.citymax-gt.com/62123/APARTAMENTO-EN-RENTA-EN-ZONA-10-DE-GUATEMALA", 
"https://www.citymax-gt.com/62632/Alquilo-Oficina-con-433.62m2-en-Zona-10-PAO-002-12-09-3", 
"https://www.citymax-gt.com/78176/OFICINAS-EN-VENTA-EN-ZONA-10-ENGANCHE-FINANCIADO-", 
"https://www.citymax-gt.com/84808/Oficina-en-Alquiler-en-Boulevard-Liberaci%C3%B3n-Zona-13", 
"https://www.citymax-gt.com/86410/CityMax-alquila-bello-apartamento-amueblado-en-zona-14.", 
"https://www.citymax-gt.com/129620/Apartamento-en-Alquiler-Zona-15-con-2-habitaciones", 
"https://www.citymax-gt.com/57296/Alquilo-Oficina-con-11.00m2-en-Zona-10-PAO-036-03-11-3", 
"https://www.citymax-gt.com/57299/Alquilo-Oficina-en-Zona-10-", 
"https://www.citymax-gt.com/57885/LOCAL-COMERCIAL-EN-RENTA-O-VENTA-ZONA-10-GUATEMALA", 
"https://www.citymax-gt.com/57301/Alquilo-oficina-amueblada-en-zona-10", 
"https://www.citymax-gt.com/58509/Terreno-en-Km.-26-sobre-Carretera-a-El-Salvador-Guate", 
"https://www.citymax-gt.com/57302/Oficina-amueblada-en-renta-en-zona-10", 
"https://www.citymax-gt.com/58518/Apartamento-en-renta-en-zona-15", 
"https://www.citymax-gt.com/57304/Alquilo-oficina-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/58568/CASA-EN-ALQUILER-EN-MONTERRICO-GUATEMALA", 
"https://www.citymax-gt.com/57305/Rento-oficina-amueblada-en-zona-10", 
"https://www.citymax-gt.com/58969/Apartamento-en-Renta-con-360.00m2-en-Zona-14", 
"https://www.citymax-gt.com/57856/Renta-local-comercial-en-zona-10", 
"https://www.citymax-gt.com/59066/OFICINA-En-renta-en-zona-9", 
"https://www.citymax-gt.com/58955/Apartamento-amueblado-3-habitaciones-zona-10-Guatemala", 
"https://www.citymax-gt.com/59095/Oficina-en-renta-en-zona-9", 
"https://www.citymax-gt.com/60400/Alquiler-oficina-en-zona-14-Guatemala", 
"https://www.citymax-gt.com/59103/Apartamento-en-renta-en-edificio-de-zona-9-Guatemala", 
"https://www.citymax-gt.com/59147/AMPLIA-OFICINA-EN-RENTA-UBICADA-EN-ZONA-15-GUATEMALA", 
"https://www.citymax-gt.com/59327/Apartamento-en-Renta-en-la-Zona-14-por-CITYMAX", 
"https://www.citymax-gt.com/91002/Se-alquila-oficina-en-zona-11-Guatemala", 
"https://www.citymax-gt.com/91023/Se-vende-apartamento-en-zona-15-Vista-Hermosa-1-GANGA", 
"https://www.citymax-gt.com/91393/Apartamento-de-1-Habitaci%C3%B3n-en-Km-18-Carr-Al-Salvador", 
"https://www.citymax-gt.com/91522/Apartamento-en-Renta-y-venta-en-zona-16-cerca-a-Cayal%C3%A1", 
"https://www.citymax-gt.com/92629/Ofibodega-en-alquiler-con-San-Cristobal-zona-8-de-Mixco", 
"https://www.citymax-gt.com/92891/Oficina-en-alquiler-en-zona-10-Cerca-a-Hacienda-Real", 
"https://www.citymax-gt.com/93721/Bodega-en-Renta-en-zona-11-en-el-Guarda-nivel-3-400mt2", 
"https://www.citymax-gt.com/98309/Local-comercial-dentro-de-Centro-Comercial-zona-7", 
"https://www.citymax-gt.com/98311/Local-en-Renta-En-sector-de-la-Roosevelt-zona-7-", 
"https://www.citymax-gt.com/98518/Local-Disponible-en-Renta-en-zona-7-sobre-la-Roosevelt", 
"https://www.citymax-gt.com/61800/Apartamento-en-Renta-en-la-ZONA-14-Guatemala-Promueve-CityMax", 
"https://www.citymax-gt.com/76726/Renta-Oficina-en-El-Naranjo", 
"https://www.citymax-gt.com/76787/Renta-Oficina-496Mts-Zona-4-Mixco-El-Naranjo", 
"https://www.citymax-gt.com/77972/OFICINAEN-RENTA-EN-EL-NARANJO-ZONA-4-DE-MIXCO", 
"https://www.citymax-gt.com/79484/Rento-oficina-EN-RENTA-Zona-4-MIXCO-EL-NARANJO", 
"https://www.citymax-gt.com/82002/Alquilo-oficina-enMixco-Guatemala", 
"https://www.citymax-gt.com/82009/Alquilo-oficina-Amueblada-en-zona-4-Mixco", 
"https://www.citymax-gt.com/82021/OFICINA-Amueblada-EN-RENTA-EN-CRECE-zona-4-Mixco", 
"https://www.citymax-gt.com/82288/CityMax-Renta-Oficinas-NUEVAS-en-18-CALLE-zona-10", 
"https://www.citymax-gt.com/82674/Alquilo-Bodega-con-255-m2-en-Zona-4-de-Mixco", 
"https://www.citymax-gt.com/59360/Alquilo-Apartamento-con-333.00m2-en-Zona-14-PAA-026-05-09-5", 
"https://www.citymax-gt.com/59425/CityMax-Renta-Oficina-en-Edificio-DOMANI-zona-15", 
"https://www.citymax-gt.com/59728/alquilo-oficina-frente-al-C.C.-zona-4-CityMax", 
"https://www.citymax-gt.com/59771/Apartamento-amueblado-en-renta-en-Torre-Real-km-9-CAES-", 
"https://www.citymax-gt.com/59792/APARTAMENTO-EN-RENTA-ZONA-16-GUATEMALA", 
"https://www.citymax-gt.com/60251/Alquilo-Local-con-3.50m2-en-Rio-HondoZacapa", 
"https://www.citymax-gt.com/60253/Rento-terreno-en-Ri%C3%B3-Hondo-Zacapa", 
"https://www.citymax-gt.com/60261/OFICINA-EN-RENTA-EN-MUXBAL", 
"https://www.citymax-gt.com/60524/Alquilo-Apartamento-con-95.00m2-en-Zona-10-PAA-018-02-14", 
"https://www.citymax-gt.com/60597/Alquilo-Oficina-con-193.00m2-en-Zona-10-PAO-025-03-14", 
"https://www.citymax-gt.com/82116/Alquilo-Apartamento-con-430.00m2-en-Zona-14-PAA-026-05-09-13", 
"https://www.citymax-gt.com/82251/CityMax-renta-apartamento-amueblado-zona-10-Guatemala", 
"https://www.citymax-gt.com/82760/CityMax-renta-propiedad-comercial-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/83146/Rento-Terreno-en-el-Km.-98-Puerto-Quetzal", 
"https://www.citymax-gt.com/83253/CityMax-promueve-en-Renta-Edificio-Para-oficinas-en-Z.9", 
"https://www.citymax-gt.com/83408/Amplia-Cl%C3%ADnica-en-Renta-Zona-9--Excelente-ubicaci%C3%B3n", 
"https://www.citymax-gt.com/83535/CITYMAX-Renta-Apartamento-de-Lujo-en-la-Zona-14", 
"https://www.citymax-gt.com/83653/Local-en-Renta-sobre-la-7-avenida-zona-9-CityMax", 
"https://www.citymax-gt.com/84003/Quinta-de-Malib%C3%BA-en-renta-en-Escuintla-Guatemala", 
"https://www.citymax-gt.com/84358/Terreno-en-Renta-Para-Inversion-Asuncion-Mita-Jutiapa", 
"https://www.citymax-gt.com/105152/Apartamento-tipo-loft-en-alquiler-Zona-10-Guatemala", 
"https://www.citymax-gt.com/105154/Apartamento-en-alquiler-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/105156/Apartamento-en-renta-ubicado-zona-10-Guatemala", 
"https://www.citymax-gt.com/105158/Apartamento-moderno-en-alquiler-zona-10-Guatemala", 
"https://www.citymax-gt.com/105162/Moderno-PentHouse-en-alquiler-zona-10", 
"https://www.citymax-gt.com/105163/PentHouse-en-zona-10-Guatemala-en-Renta", 
"https://www.citymax-gt.com/105587/Rento-apartamento-amueblado-en-zona-10", 
"https://www.citymax-gt.com/105929/Rento-oficina-en-Muxbal-km-8.5", 
"https://www.citymax-gt.com/106735/Edificio-en-renta-en-zona-1-de-CobanAlta-Verapaz", 
"https://www.citymax-gt.com/110810/Apartamento-Amueblado-en-zona-10-Alquiler", 
"https://www.citymax-gt.com/126587/Oficina-en-renta-en-zona-9-Cerca-de-Montufar", 
"https://www.citymax-gt.com/126597/Alquiler-Apartamento-Amueblado-zona-10-Guatemala", 
"https://www.citymax-gt.com/127002/-Alquiler-de-oficina-en-Unicentro-zona-10", 
"https://www.citymax-gt.com/127455/Amplio-Apartamento-Amueblado-en-Zona-14", 
"https://www.citymax-gt.com/127529/Local-en-Antigua-Guatemala-en-Hotel-Boutique", 
"https://www.citymax-gt.com/128613/Renta-terreno-ideal-para-gasolinera-en-Escuintla", 
"https://www.citymax-gt.com/129197/Alquiler-de-casa-y-terreno-en-Alta-Verapaz-Guatemala", 
"https://www.citymax-gt.com/57014/CASA-EN-CONDOMINIO-EN-ALQUILER-EN-ANTIGUA", 
"https://www.citymax-gt.com/57222/-OFICINA-EN-ALQUILER-EN-ZONA-11-GUATEMALA-POR-CITYMAX", 
"https://www.citymax-gt.com/57227/Alquilo-Oficina-con-83-mts-de-construcci%C3%B3n-Zona-11-", 
"https://www.citymax-gt.com/121161/Local-Comercial-en-renta-en-plaza-ubicada-en-San-Lucas", 
"https://www.citymax-gt.com/121164/En-Alquiler-local-comercial-en-San-Lucas-Sacatepequez", 
"https://www.citymax-gt.com/121165/Local-comercial-en-renta-San-Lucas-Sacatepéquez", 
"https://www.citymax-gt.com/122467/Oficina-en-alquiler-en-el-Naranjo-Zona-4-de-Mixco", 
"https://www.citymax-gt.com/122475/Oficina-en-Internaranjo-Zona-4-de-Mixco-en-Renta", 
"https://www.citymax-gt.com/124291/Oficina-en-renta-en-HQ-Fontabella-zona-10", 
"https://www.citymax-gt.com/124292/Local-en-renta-en-HQ-Fontabella-zona-10", 
"https://www.citymax-gt.com/124293/Oficina-en-renta-en-HQ-Fontabella-zona-10", 
"https://www.citymax-gt.com/129351/Apartamento-en-renta-Petapolis-zona-12-Guatemala", 
"https://www.citymax-gt.com/129691/Oficina-en-renta-Distrito-Miraflores-zona-11-Roosevelt", 
"https://www.citymax-gt.com/116426/Rento-Bodega-Nueva-en-Las-Tunas-Zona-4-de-Mixco", 
"https://www.citymax-gt.com/116429/Bodega-en-Renta-en-Zona-4-de-Mixco-las-Tunas", 
"https://www.citymax-gt.com/116430/Alquilo-en-Parque-Industrial-las-Tunas-Bodega-Z.4-Mixco", 
"https://www.citymax-gt.com/116431/Renta-de-Ofibodega-Nueva-en-zona-4-de-Mixco-Naranjo", 
"https://www.citymax-gt.com/117151/CASA-TIPO-MANSION-EN-RENTA,-SAN-BARTOLOME-SACATEPEQUEZ", 
"https://www.citymax-gt.com/118495/Alquiler-de-oficina-virtual-en-zona-4-de-la-Ciudad", 
"https://www.citymax-gt.com/118500/Rento-oficina-virtual-edificio-de-zona-4", 
"https://www.citymax-gt.com/118502/Oficina-equipada-en-renta-en-zona-4-Guatemala", 
"https://www.citymax-gt.com/118538/Oficinas-Amuebladas-y-Equipadas-en-zona-4-Guatemala", 
"https://www.citymax-gt.com/118631/Alquilo-casa-comercial-ideal-para-oficinas-Sacatepéquez", 
"https://www.citymax-gt.com/62711/Oficina-en-renta-en-zona-10-diagonal-6-Guatemala-", 
"https://www.citymax-gt.com/75577/Alquilo-Apartamento-con-163.00m2-en-Zona-14-PAA-001-07-16", 
"https://www.citymax-gt.com/76083/Vendo-o-Alquilo-Apartamento-AMUEBLADO-z14-", 
"https://www.citymax-gt.com/76123/Alquilo-Local-con-102.63m2-en-Zona-10-PAL-055-08-13-2", 
"https://www.citymax-gt.com/78803/Alquilo-Apartamento-con-100.00m2-en-Zona-10-PAA-059-11-10", 
"https://www.citymax-gt.com/79604/Apartamento-en-renta-en-edificio-de-zona-15", 
"https://www.citymax-gt.com/80110/Kiosko-en-renta-en-edificio-de-zona-10-%C2%A1CityMax", 
"https://www.citymax-gt.com/81454/Alquilo-Local-con-80.13m2-en-Zona-10-PAL-041-09-13-2", 
"https://www.citymax-gt.com/81956/Local-en-alquiler-en-zona-4-Guatemala-%C2%A1CityMax", 
"https://www.citymax-gt.com/82053/Casa-en-renta-en-Carreterera-a-El-Salvador", 
"https://www.citymax-gt.com/126286/Locales-en-Renta-en-Carretera-a-el-Salvador-Km-16", 
"https://www.citymax-gt.com/126287/Rento-Local-en-Km-16-Carretera-a-el-Salvador-PUNTO-16", 
"https://www.citymax-gt.com/126293/Bodeguitas-sobre-Calzada-San-Juan-zona-7", 
"https://www.citymax-gt.com/126605/Renta-local-área-Food-Court-sobre-Carretera-San-Lucas", 
"https://www.citymax-gt.com/126606/Se-renta-local-comercial-2do-nivel-Plaza-en-San-Lucas", 
"https://www.citymax-gt.com/126608/En-Alquiler-local-comercial-60Mts-Plaza-de-San-Lucas-", 
"https://www.citymax-gt.com/126610/En-Renta-local-en-San-Lucas-Sacatepéquez", 
"https://www.citymax-gt.com/126611/Renta-local-en-San-Lucas-Sac.-plaza-sobre-Carretera", 
"https://www.citymax-gt.com/126655/Renta-local-comercial-Puerto-de-San-Jose-50-mtrs2", 
"https://www.citymax-gt.com/126888/En-Renta-Apartamento-en-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/57224/Alquilo-Oficina-con-88.00m2-en-Zona-11-PAO-060-03-11-5", 
"https://www.citymax-gt.com/57228/Alquilo-Oficina-con-37.00m2-en-Zona-11-PAO-060-03-11-9", 
"https://www.citymax-gt.com/57243/Alquilo-oficina-en-zona-9-Guatemala", 
"https://www.citymax-gt.com/57531/Excelente-oficina-en-renta-en-zona-13", 
"https://www.citymax-gt.com/57857/Alquilo-Local-con-80mt2-en-primer-Nivel-zona-10", 
"https://www.citymax-gt.com/58035/Alquilo-Local-en-Plaza-Villa-Nueva-CITYMAX", 
"https://www.citymax-gt.com/59042/LOCAL-EN-RENTA-ZONA-4-IDEAL-PARA-OFICINAS-GUATEMALA", 
"https://www.citymax-gt.com/59670/Vendo-o-Alquilo-Local-con-50.00m2-en-San-Miguel-Petapa-PML-032-04-13", 
"https://www.citymax-gt.com/59824/Oficina-en-renta-en-zona-10-con-buena-ubicaci%C3%B3n", 
"https://www.citymax-gt.com/59828/Alquilo-Oficina-con-67Mts-en-Zona-10-Guatemala", 
"https://www.citymax-gt.com/100024/Excelente-Ubicacion-Terreno-en-Renta-a-mts-del-Parque", 
"https://www.citymax-gt.com/101644/Renta-de-casa-en-Zona-1-Avenida-Elena-de-3-niveles", 
"https://www.citymax-gt.com/104781/Oficina-en-alquiler-Zona-Pradera-zona-10", 
"https://www.citymax-gt.com/105795/Apartamento-En-Renta-Shift-Cayal%C3%A1-Amueblado-", 
"https://www.citymax-gt.com/111762/RENTA-DE-CUARTO-FRIO-PARA-REFRIGERACI%C3%93N-INDUSTRIAL-", 
"https://www.citymax-gt.com/111766/ALQUILER-DE-CUARTO-FRIO-DENTRO-DE-COMPLEJO-INDUSTRIAL", 
"https://www.citymax-gt.com/111771/RENTA-DE-BODEGAS-FRIAS-COMERCIALES-E-INDUSTRIALES", 
"https://www.citymax-gt.com/111773/RENTA-DE-BODEGAS-CONGELADAS-Y-REFRIGERADOS-COMERCIALES-", 
"https://www.citymax-gt.com/111775/Renta-de-Cuarto-Frio-en-Roosevelt-dentro-de-complejo-", 
"https://www.citymax-gt.com/113359/Alquilo-linda-oficina-en-GEMINIS-10-zona-10", 
"https://www.citymax-gt.com/60707/APARTAMENTO-LUJOSO-EN-ALQUILER-ZONA-14-GUATEMALA", 
"https://www.citymax-gt.com/60708/APARTAMENTO-RENTA-EXCLUSIVO-SECTOR-ZONA-10-GUATEMALA", 
"https://www.citymax-gt.com/60908/Alquilo-Oficina-con-828.85m2-en-Zona-9-PAO-062-10-10-3", 
"https://www.citymax-gt.com/61153/CityMax-renta-terreno-en-La-Trinidad-Boca-del-Monte-", 
"https://www.citymax-gt.com/61154/CityMax-Renta-terreno-en-Boca-del-Monte-Guatemala", 
"https://www.citymax-gt.com/61155/Terreno-en-alquiler-en-Boca-del-Monte-Villa-Canales", 
"https://www.citymax-gt.com/61191/Alquilo-hermoso-rancho-en-Ruta-al-Atl%C3%A1ntico", 
"https://www.citymax-gt.com/61193/local-en-renta-en-km-85-Guatemala", 
"https://www.citymax-gt.com/61217/Tanques-en-renta-en-Santo-Tom%C3%A1s-de-Castilla-Guatemala", 
"https://www.citymax-gt.com/61350/Alquilo-Apartamento-con-107.54m2-en-Zona-15-PAA-028-10-14-4", 
"https://www.citymax-gt.com/110988/Oficina-Tabicada-en-Alquiler-en-la-Zona-4-Guatemala", 
"https://www.citymax-gt.com/111145/Terreno-Construccion-en-Alquiler-Blv.-Vista-Hermosa-Z15", 
"https://www.citymax-gt.com/111829/Apartamento-en-renta-en-zona-4", 
"https://www.citymax-gt.com/112024/Rento-oficina-en-zona-14-Guatemala", 
"https://www.citymax-gt.com/114749/Oficina-en-alquiler-en-Zona-Pradera-Coworking", 
"https://www.citymax-gt.com/115688/Oficina-en-Alquiler-en-Zona-Pradera-zona-10-", 
"https://www.citymax-gt.com/115778/Amplia-oficina-en-renta-en-Zona-10-Las-Margaritas.", 
"https://www.citymax-gt.com/115925/Oficina-en-Renta-en-zona-4-Granat-Guatemala", 
"https://www.citymax-gt.com/116050/RENTA-DE-apartamento-Zona-9-Guatemala", 
"https://www.citymax-gt.com/116669/Apartamento-con-Amplia-Terraza-en-Cayala-Z.16-Guatemala", 
"https://www.citymax-gt.com/84388/Oficina-Nueva-en-Renta-en-zona-10", 
"https://www.citymax-gt.com/84395/CityMax-Alquila-oficina-en-zona-10-ciudad", 
"https://www.citymax-gt.com/84652/Amplio-apartamento-en-renta-en-zona-14-Guatemala", 
"https://www.citymax-gt.com/84959/Alquilo-casa-vacacional-en-Puerto-de-San-Jos%C3%A9-Escuintla", 
"https://www.citymax-gt.com/85982/Terreno-comercial-en-renta-enEscuintla-Guatemala", 
"https://www.citymax-gt.com/86404/Oficinaefficiency-en-renta-en-zona-15-Guatemala", 
"https://www.citymax-gt.com/86405/Oficinaefficiency-en-renta-en-zona-15-Guatemala", 
"https://www.citymax-gt.com/87427/OFIBODEGA-EN-RENTA-A-PUERTO-QUETZAL-ESCUINTLA", 
"https://www.citymax-gt.com/89583/OFIBODEGA-EN-RENTA-CARRETERA-A-PUERTO-QUETZAL", 
"https://www.citymax-gt.com/89988/Terreno-comercial-en-renta-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/81603/Rento-hermosa-casa-en-condominio-zona-14", 
"https://www.citymax-gt.com/85782/Apartamento-amueblado-en-Renta-en-San-Rafael-", 
"https://www.citymax-gt.com/90945/Oficinas-Amplias-en-renta-en-Europlaza-Zona-14", 
"https://www.citymax-gt.com/98508/Apartamento-Nuevo-en-Renta-City-Haus-Zona-10-Guatemala", 
"https://www.citymax-gt.com/104778/Oficina-en-renta-en-Zona-Pradera-zona-10-Guatemala", 
"https://www.citymax-gt.com/111030/Local-Comercial-en-Renta-Zona-14-Guatemala", 
"https://www.citymax-gt.com/111031/En-Renta-Local-Comercial-La-ca%C3%B1ada-zona-14-Guatemala", 
"https://www.citymax-gt.com/115938/Oficina-en-Renta-en-el-Km-9-Carretera-a-el-Salvador-", 
"https://www.citymax-gt.com/115952/Alquilo-Oficina-en-Km-9-Torre-Tigo", 
"https://www.citymax-gt.com/115954/Oficina-con-178-m2-en-Renta-en-Torre-Tigo-Km-9.5-", 
"https://www.citymax-gt.com/57526/Alquilo-Oficina-con-104Mts.-en-Zona-13-Americas", 
"https://www.citymax-gt.com/57903/Alquilo-Local-con-240.00m2-en-Zona-13-PAL-006-12-09-3", 
"https://www.citymax-gt.com/58194/ALQUILER-DE-BODEGAS-EN-ZONA-11-GUATEMALA-", 
"https://www.citymax-gt.com/59795/OFICINA-EN-RENTA-ZONA-10-CIUDAD-DE-GUATEMALA", 
"https://www.citymax-gt.com/61817/Alquilo-local-en-centro-comercial-Villa-Nueva-%C2%A1CityMax", 
"https://www.citymax-gt.com/61899/Alquilo-Oficina-con-130.00m2-en-Zona-4-PAO-031-06-15-10", 
"https://www.citymax-gt.com/62555/Se-renta-oficina-en-excelente-ubicaci%C3%B3n-zona-10", 
"https://www.citymax-gt.com/82960/Alquilo-oficina-en-edificio-comercial-en-zona-10", 
"https://www.citymax-gt.com/83030/Vendo-hermosa-casa-en-San-Lucas-Sacatepequez", 
"https://www.citymax-gt.com/83744/Alquilo-hermosa-casa-en-LABOR-DE-CASTILLA", 
"https://www.citymax-gt.com/118660/En-Alquiler-apartamento-Amueblado-zona-10-Guatemala", 
"https://www.citymax-gt.com/118804/Alquilo-local-en-zona-10-edificio-comercial-Guatemala", 
"https://www.citymax-gt.com/118821/Local-comercial-en-renta-en-zona-10-Murano-Center", 
"https://www.citymax-gt.com/118824/Alquilo-local-en-edificio-Murano-Center-en-zona-10", 
"https://www.citymax-gt.com/118825/CityMax-renta-local-en-Edificio-comercial-zona-10-Guate", 
"https://www.citymax-gt.com/118829/Nivel-completo-de-Oficinas-en-alquiler-en-zona-10-", 
"https://www.citymax-gt.com/119005/Oficina-en-renta-en-ZONA-PRADERA-zona-10", 
"https://www.citymax-gt.com/119025/Oficina-en-Renta-en-Zona-10-Edificio-Murano", 
"https://www.citymax-gt.com/119026/Alquilo-Oficina-de-183-m2-en-Zona-10-Zona-VIVA", 
"https://www.citymax-gt.com/119027/Oficina-Comercial-en-Renta-de-97Mts-en-Zona-10", 
"https://www.citymax-gt.com/82289/OFICINAS-en-alquiler-Bulevar-Los-Pr%C3%B3ceres-zona-10", 
"https://www.citymax-gt.com/83040/Alquilo-Oficina-con-86.20m2-en-Carretera-El-Salvador", 
"https://www.citymax-gt.com/86576/Alquilo-CL%C3%8DNICA-amueblada-en-zona-10", 
"https://www.citymax-gt.com/91129/Se-Alquila-Local-Oficina-en-Zona-Pradera-de-98-m2-Z.10", 
"https://www.citymax-gt.com/93756/Apartamento-amueblado-Cerca-Pradera-Concepcion-%C2%A1Rento", 
"https://www.citymax-gt.com/99008/Se-Alquila-Local-en-Plaza-Hincapie-zona-13-", 
"https://www.citymax-gt.com/102737/Casa-en-venta-en-Carretera-a-El-Salvador-cerca-Walmart", 
"https://www.citymax-gt.com/105595/Alquilo-oficina-en-zona-13-Guatemala", 
"https://www.citymax-gt.com/106395/Oficina-en-renta-en-Edificio-de-zona-10-Guatemala", 
"https://www.citymax-gt.com/114448/Alquilo-apartamento-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/60713/APARTAMENTO-RENTA-ZONA-10-GUATEMALA", 
"https://www.citymax-gt.com/60868/Apartamento-bien-ubicado-rento-apartamento-en-zona-10", 
"https://www.citymax-gt.com/61052/Terreno-comercial-en-renta-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/61124/APARTAMENTO-EN-ALQUILER-ZONA-13", 
"https://www.citymax-gt.com/61195/Alquilo-Local-en-El-Rancho", 
"https://www.citymax-gt.com/61196/Local-en-Ruta-al-Atl%C3%A1ntico-en-renta", 
"https://www.citymax-gt.com/61537/Apartamento-en-%28Renta%29-en-la-Zona-10-Promueve-CityMax", 
"https://www.citymax-gt.com/62128/LOCAL-COMERCIAL-FOOD-COURT-RENTA-ZONA-4", 
"https://www.citymax-gt.com/62146/Alquilo-Apartamento-con-139.00m2-en-Zona-14-PAA-012-12-12-1", 
"https://www.citymax-gt.com/62308/Alquilo-apartamento-en-edificio-exclusivo-zona-14", 
"https://www.citymax-gt.com/126889/Apartamento-en-Renta-en-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/127877/Oficina-en-renta-en-Ascend-zona-9-Guatemala", 
"https://www.citymax-gt.com/128014/Apartamento--Alquiler-Amueblado-en-el-Centro-Historico", 
"https://www.citymax-gt.com/128015/Local-en-renta-en-Plaza-comercial-km-14-a-Carretera", 
"https://www.citymax-gt.com/128016/Alquiler-de-oficina-en-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/128126/Apartamento-Amueblado-renta-en-zona-9", 
"https://www.citymax-gt.com/128985/Casa-en-Renta-en-zona-2-de-4-dormitorios-254-metros-", 
"https://www.citymax-gt.com/129380/Apartamento-Moderno-amueblado-en-renta-en-Centro-Vivo-", 
"https://www.citymax-gt.com/56292/Lindo-Apto-en-renta-en-zona-10-pr%C3%B3ximo-a-Di%C3%A1gonal-6.", 
"https://www.citymax-gt.com/56382/HERMOSO-APARTAMENTO-EN-RENTA-EN-ZONA-14-GUATEMALA", 
"https://www.citymax-gt.com/113385/Bodega-En-Renta-en-Aurora-zona-13-Dentro-de-Garita-", 
"https://www.citymax-gt.com/114052/Oficina-en-Renta-Géminis-10-", 
"https://www.citymax-gt.com/115136/Renta-de-Terreno-Comercial-En-El-Centro-de-Chiquimula-", 
"https://www.citymax-gt.com/116300/Apartamento-Nuevo-en-Jardines-de-la-Asunción-Zona-5-", 
"https://www.citymax-gt.com/117717/Terreno-comercial-en-renta-en-Amatitlán", 
"https://www.citymax-gt.com/61747/CASA-AMUEBLADA-EN-RENTA-ZONA-15", 
"https://www.citymax-gt.com/117731/Apartamento-en-Renta-Zona-7-Edificio-Difiori-", 
"https://www.citymax-gt.com/61772/Apartamento-amueblado-en-renta-en-zona-9-Guatemala", 
"https://www.citymax-gt.com/118350/Apartamento-En-Renta-Torre-del-Valle-Amueblado-Z.-10", 
"https://www.citymax-gt.com/61775/Local-u-Oficina-en-renta-en-zona-9-Guatemala", 
"https://www.citymax-gt.com/119035/Oficina-en-Renta-ubicado-Zona-10-TABICADA", 
"https://www.citymax-gt.com/61855/Rento-apartamento-en-Antigua-Guatemala", 
"https://www.citymax-gt.com/119256/Local-en-alquiler-en-Plaza-Zona-4-Guatemala", 
"https://www.citymax-gt.com/61901/Alquilo-Apartamento-con-120m2-en-Zona-15-2-habitaciones", 
"https://www.citymax-gt.com/119275/Locales-en-renta-en-Plaza-zona-4-Guatemala", 
"https://www.citymax-gt.com/61924/En-renta-oficina-en-zona-10", 
"https://www.citymax-gt.com/61927/APARTAMENTO-EN-RENTA-ZONA-10-OAKLAND", 
"https://www.citymax-gt.com/61949/OFICINA-En-alquiler-ZONA-9-", 
"https://www.citymax-gt.com/62092/CASA-EN-RENTA-OCKLAND-ZONA-10-", 
"https://www.citymax-gt.com/62131/CASA-EN-RENTA-EN-ALTAMAR-PUERTO-SAN-JOSEESCUINTLA-", 
"https://www.citymax-gt.com/90341/Oficina-nueva-en-renta-en-Zona-15-Guatemala", 
"https://www.citymax-gt.com/90561/CITYMAX-Alquila-Local-en-Carretera-a-el-Salvador", 
"https://www.citymax-gt.com/90876/Apartamento-amueblado-zona-10-Guatemala", 
"https://www.citymax-gt.com/90879/Alquilo-Villa-amueblada-en-Antigua-Guatemala", 
"https://www.citymax-gt.com/91100/Apartamento-amueblado-en-renta-en-Montebello-Guatemala", 
"https://www.citymax-gt.com/91112/Renta-local-de-144.50mts-en-Xela-INTERPLAZA", 
"https://www.citymax-gt.com/91394/Apartamento-Amueblado-en-Juan-Gaviota", 
"https://www.citymax-gt.com/91956/Oficina-en-Alquiler-en-Zona-Pradera-Zona-10-Guatemala", 
"https://www.citymax-gt.com/96053/Oficina-en-Alquiler-en-Avenida-Reforma-Z.9", 
"https://www.citymax-gt.com/96055/Rento-Oficina-en-Ave-Reforma-con-161.858-m2-en-Zona-9", 
"https://www.citymax-gt.com/118409/Casa-en-Renta-en-Muxbal-Ciudad-de-Guatemala", 
"https://www.citymax-gt.com/119161/Apartamento-en-Alquiler-Villa-Risho-Zona-14-con-336Mts", 
"https://www.citymax-gt.com/119992/Alquilo-apartamento-en-edificio-Tintoretto-zona-14", 
"https://www.citymax-gt.com/122506/Apartamento-tipo-casa-en-renta-con-muebles", 
"https://www.citymax-gt.com/122913/Oficina-en-Alquiler-Corporativo-Muxbal", 
"https://www.citymax-gt.com/123097/Alquilo-apartamento-en-zona-10-Ciudad-Guatemala", 
"https://www.citymax-gt.com/123178/Local-comercial-a-Estrenar-en-Zona-10-en-Renta", 
"https://www.citymax-gt.com/123181/RENTA-Local-en-Zona-10-Edificio-Corporativo", 
"https://www.citymax-gt.com/123716/Alquiler-oficina-en-zona-9-Ciudad-Guatemala", 
"https://www.citymax-gt.com/123720/CityMax-alquila-oficina-en-zona-9-Guatemala", 
"https://www.citymax-gt.com/87565/Oficina-en-Renta-en-zona-11-sobre-la-Roosevelt", 
"https://www.citymax-gt.com/92074/Local-en-renta-en-Villa-Lobos-Centro-comercial-nuevo-", 
"https://www.citymax-gt.com/92326/Excelente-proyecto-oficinas-en-pre-venta-en-El-Naranjo", 
"https://www.citymax-gt.com/92328/Ofibodega-en-pre-venta-%C2%A1Nuevo-proyecto-en-El-Naranjo", 
"https://www.citymax-gt.com/92330/Ofibodega-en-pre-venta-%C2%A1proyecto-ubicado-en-El-Naranjo", 
"https://www.citymax-gt.com/93702/Terreno-en-renta-en-San-Lucas-Sacatep%C3%A9quez-Guatemala", 
"https://www.citymax-gt.com/106263/Renta-de-Oficina-en-Zona-11-cercano-a-Galerias-Prima", 
"https://www.citymax-gt.com/107372/Casa-grande-en-aqluiler-en-zona-12-Guatemala", 
"https://www.citymax-gt.com/107738/Oficina-en-renta-en-zona-7-sobre-Calzada-San-Juan-", 
"https://www.citymax-gt.com/107739/Oficina-en-renta-en-zona-7-sobre-Calzada-San-Juan", 
"https://www.citymax-gt.com/116463/Alquiler-de-Oficina-en-km-9.5-Carretera-a-el-Salvador-", 
"https://www.citymax-gt.com/116504/Oficina-en-Renta-en-Zona-Pradera,-Zona-10,-Guatemala", 
"https://www.citymax-gt.com/125637/Apartamento-en-Alquiler-en-Oakland-Villas-zona-10-Guate", 
"https://www.citymax-gt.com/129558/Oficinas-en-Alquiler-Avenida-Petapa-Zona-12", 
"https://www.citymax-gt.com/56456/Apartamento-amueblado-en-renta-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/57031/CASA-EN-RENTAEN-CARRETERA-EL-SALVADOR-GUATEMALA", 
"https://www.citymax-gt.com/57176/Vendo-Oficina-con-49.72m2-en-San-Jos%C3%A9-Pinula-PV0-023-10-11-1", 
"https://www.citymax-gt.com/57229/Alquilo-oficina-zona-11-CALZADA-ROOSEVELT", 
"https://www.citymax-gt.com/57943/Local-en-renta-sobre-Carretera-a-El-Salvador-km-14.5-", 
"https://www.citymax-gt.com/59167/Alquiler-apartamento-en-zona-14-Guatemala", 
"https://www.citymax-gt.com/119032/Rento-Oficina-de-154-m2-en-Zona-Viva-Zona-10", 
"https://www.citymax-gt.com/119054/Alquiler-de-oficina-en-zona-4-Cuatro-Grados-Norte", 
"https://www.citymax-gt.com/119055/Oficina-en-renta-en-zona-4-Ciudad-de-Guatemala", 
"https://www.citymax-gt.com/119057/cityMax-alquila-oficinas-en-zona-4", 
"https://www.citymax-gt.com/119058/Oficinas-en-renta-ubicadas-en-zona-4-Guatemala", 
"https://www.citymax-gt.com/119060/Oficina-en-zona-4-Ciudad-Guatemala", 
"https://www.citymax-gt.com/119061/Rento-Oficina-en-Zona-10-con-154-m2-TABICADA", 
"https://www.citymax-gt.com/119120/OFICINA-EN-ZONA-10-CON-151-m2-EN-ALQUIER-", 
"https://www.citymax-gt.com/119126/Oficina-Disponible-en-Nivel-Alto-en-renta-zona-10-", 
"https://www.citymax-gt.com/119150/Oficina-en-Penthouse-en-Renta-Zona-10", 
"https://www.citymax-gt.com/117274/Oficina-o-clínica--en-alquiler-zona-9-Guatemala", 
"https://www.citymax-gt.com/118498/Bodegas-en-Parque-Las-Tunas-Internaranjo-Empresarial", 
"https://www.citymax-gt.com/118634/RENTO-Apartamento-Amueblado-en-zona-14-", 
"https://www.citymax-gt.com/118950/Bodegas-en-Parque-Las-Tunas-Internaranjo-Empresarial", 
"https://www.citymax-gt.com/119102/Renta-oficina-Moderna-zona-15-nuevo-Centro-Empresarial", 
"https://www.citymax-gt.com/119124/Edificio-de-Oficinas-en-Alquiler-en-Zona-10-Guatemala", 
"https://www.citymax-gt.com/119909/Alquilo-apartamento-en-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/119910/Rento-apartamento-en-condominio-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/119912/Alquilo-apartamento-en-edificio-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/120931/En-Renta-oficina-en-Ascend-zona-9", 
"https://www.citymax-gt.com/62544/LOCAL-COMERCIAL-EN-ALQUILER-EN-ZONA-7-", 
"https://www.citymax-gt.com/62672/Rento-oficina-en-zona-13-Ciudad-De-Guatemala", 
"https://www.citymax-gt.com/62790/ALQUILER-DE-OFIBODEGA-EN-SN-MIGUEL-PETAPA-CON-GARITA-", 
"https://www.citymax-gt.com/62806/Alquilo-Apartamento-con-254.00m2-en-Zona-14-PAA-034-10-10-10", 
"https://www.citymax-gt.com/62850/Oficina-en-Renta-en-la-ZONA-10-Dubai-Center", 
"https://www.citymax-gt.com/76093/Alquilo-Apartamento-zona-14", 
"https://www.citymax-gt.com/78273/Alquilo-Oficina-con-545.95m2-en-Zona-10-PAO-028-07-08-19", 
"https://www.citymax-gt.com/80226/Alquilo-OFICINA-en-AVANTE-zona-15-GUATEMALA", 
"https://www.citymax-gt.com/59791/Vendo-o-Alquilo-Apartamentoen-Zona-16-", 
"https://www.citymax-gt.com/80859/CityMax-Renta-Oficina-Cercana-Centro-C%C3%ADvico-zona-4", 
"https://www.citymax-gt.com/62505/Se-Vende-Apartamento-en-La-Monta%C3%B1a-Zona-16", 
"https://www.citymax-gt.com/81043/Rento-oficina-en-zona-10-cerca-de-Europlaza", 
"https://www.citymax-gt.com/62879/CASA-EN-RENTA-ZONA-10-OACKLAND", 
"https://www.citymax-gt.com/82681/Apartamento-CON-JARDIN-y-3HabitacionesZ.15-Guatemala", 
"https://www.citymax-gt.com/83106/Apartamento-amueblado-en-alquiler-zona-15", 
"https://www.citymax-gt.com/87347/CityMax-RENTA-Apartamento-Semi-Amueblado-en-Zona-16", 
"https://www.citymax-gt.com/99411/Apartamento-en-Renta-en-Zona-16", 
"https://www.citymax-gt.com/110670/Oficina-En-Renta-en-Zona-9-Edificio-Torre-Cristal", 
"https://www.citymax-gt.com/110971/Aparta-estudio-amueblado-en-alquiler-zona-15-Guatemala", 
"https://www.citymax-gt.com/115361/Apartamento-en-Renta-Zona-7-sobre-Mateo-Flores", 
"https://www.citymax-gt.com/62425/Acogedora-Casa-en-Renta-Santa-Rosalia-Kil%C3%B3metro-12.5-CE", 
"https://www.citymax-gt.com/121255/Terreno-Comercial-en-Renta-Zona-11-Las-Charcas---------", 
"https://www.citymax-gt.com/62596/Alquilo-Local-con-1303.67m2-en-Zona-4-PAO-015-02-16", 
"https://www.citymax-gt.com/75751/Alquilo-Oficina-con-55.00m2-en-Zona-4-PAO-031-06-15-22", 
"https://www.citymax-gt.com/76069/EXCLUSIVO-APARTAMENTO-EN-RENTA-ZONA-14", 
"https://www.citymax-gt.com/76099/Alquilo-Oficina-con-95.00m2-en-Zona-15", 
"https://www.citymax-gt.com/121259/Terreno-Comercial-sobre-Avenida-Petapa-zona-12-en-Renta", 
"https://www.citymax-gt.com/77170/CONSTRUCCI%C3%93N-DE-BODEGA-A-MEDIDA-KM.78-A-PUERTO-QUETZAL-", 
"https://www.citymax-gt.com/123559/Ofibodega-y-fabrica-en-Renta-Z.-8-San-Miguel-Petapa---", 
"https://www.citymax-gt.com/78583/Alquilo-Oficina-con-60.00m2-en-Zona-13-PAO-041-04-10-15", 
"https://www.citymax-gt.com/125867/Apartamento-En-Renta-Shift-de-Cayala-Zona-16-", 
"https://www.citymax-gt.com/78889/OFICINA-COMERCIAL-EN-RENTA-TABICADA-EN-ZONA-4", 
"https://www.citymax-gt.com/126240/En-Alquiler-oficina-en-Ascend-zona-9-Guatemala", 
"https://www.citymax-gt.com/79401/LOCAL-COMERCIAL-EN-BOULEVAR-LOS-PROCERES-ZONA-10-GUATEMALA-", 
"https://www.citymax-gt.com/126323/Oficina-Nueva-en-Renta-Edificio-01010-zona-10----------", 
"https://www.citymax-gt.com/81981/Alquiler-de-ofibodega-en-zona-4-Mixco", 
"https://www.citymax-gt.com/126545/Apartamento-AMUEBLADO-en-la-Zona-4-Edificio-QUO", 
"https://www.citymax-gt.com/127167/Casa-En-Renta-Con-Suelo-Comercial-Zona-10--------------", 
"https://www.citymax-gt.com/127526/Bodega-en-Renta-en-Los-Álamos-San-Miguel-Petapa--------", 
"https://www.citymax-gt.com/127969/Apartamento-en-Alquiler-en-CENTO-Santa-Catarina-Pinula", 
"https://www.citymax-gt.com/97350/Apartamento-en-Alquiler-Nivel-Completo-Zona-10-", 
"https://www.citymax-gt.com/97508/Vendo-terreno-en-km-33-ruta-a-El-Salvador-Villa-Canales", 
"https://www.citymax-gt.com/100834/Se-Renta-Apartamento-para-Estrenar-en-Zona-15-V.H.I", 
"https://www.citymax-gt.com/100892/TERRENO-COMERCIAL-DE-20000-VARAS-EN-KM-78-ESCUINTLA", 
"https://www.citymax-gt.com/103639/Terreno-comercial-en-renta-en-Chimaltenango-Guatemala", 
"https://www.citymax-gt.com/104387/Linda-y-amplia-casa-en-renta-en-km-14.5-CES", 
"https://www.citymax-gt.com/104847/Rento-local-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/105026/Rento-apartamento-tipo-loft-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/123721/Oficina-en-alquiler-en-edificio-de-zona-9-Guatemala", 
"https://www.citymax-gt.com/105146/Rento-apartamento-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/123722/Alquiler-de-oficina-en-zona-9-Ciudad-Guatemala", 
"https://www.citymax-gt.com/105151/Apartamento-Loft-en-Renta-zona-10-Guatemala", 
"https://www.citymax-gt.com/125000/Apartamento-Amueblado-en-alquiler-Diago6-zona-10", 
"https://www.citymax-gt.com/125342/Casa-en-Renta-Zona-10-Guatemala", 
"https://www.citymax-gt.com/125581/Pent-House-Amueblado-en-Renta-Zona-10-Guatemala", 
"https://www.citymax-gt.com/125586/Oficina-en-Alquiler-Zona-10-area-Hotelera", 
"https://www.citymax-gt.com/125836/Bodega-en-Renta-en-zona-13-Guatemala", 
"https://www.citymax-gt.com/125949/Oficinas-en-Renta-de-2-Niveles-en-la-Zona-9-", 
"https://www.citymax-gt.com/125974/Apartamento-en-renta-en-Zona-15-Excelente-Ubicación!!", 
"https://www.citymax-gt.com/126571/Apartamento-en-alquiler-zona-14", 
"https://www.citymax-gt.com/107740/Oficina-en-renta-en-zona-7-sobre-Calzada-San-Juan", 
"https://www.citymax-gt.com/59827/Oficina-bien-ubicada-edificio-zona-10-alquiler", 
"https://www.citymax-gt.com/107741/Oficina-en-renta-zona-7-Calzada-San-Juan-Guatemala", 
"https://www.citymax-gt.com/59956/CityMax-promociona-local-en-renta-Carretera-a-Salvador", 
"https://www.citymax-gt.com/59958/En-renta-local-Comercial-en-CC-Carretera-a-El-Salvador", 
"https://www.citymax-gt.com/107743/Local-comercial-en-renta-en-zona-7-Calzada-San-Juan", 
"https://www.citymax-gt.com/60267/Alquilo-Apartamento-con-180.00m2-en-Zona-10-PAA-045-06-09", 
"https://www.citymax-gt.com/107746/Local-comercial-en-renta-en-zona-7-Calzada-San-Juan", 
"https://www.citymax-gt.com/60432/Apartamento-amueblado-en-renta-zona-14-Guatemala-", 
"https://www.citymax-gt.com/107778/Local-comercial-en-renta-en-zona-7-Calzada-San-Juan", 
"https://www.citymax-gt.com/60591/Oficina-efficiency-en-renta-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/113007/co-working", 
"https://www.citymax-gt.com/60598/Alquilo-Oficina-con-90.22m2-en-Zona-10-PAO-025-03-14-1", 
"https://www.citymax-gt.com/114037/Alquilo-oficina-en-edifcio-nuevo-en-zona-9", 
"https://www.citymax-gt.com/60649/Oficina-en-renta-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/114589/Oficina-en-Alquiler-en-edificio-Scena-", 
"https://www.citymax-gt.com/60834/Alquilo-hermosa-casa-en-zona-14", 
"https://www.citymax-gt.com/116419/Bodega-en-Alquiler-area-del-Naranjo-Z.4-Mixco", 
"https://www.citymax-gt.com/62261/Local-en-Renta-en-Plaza-Comercial-de-zona-10", 
"https://www.citymax-gt.com/116422/Renta-de-bodega-en-Distribodegas-zona-4-de-Mixco", 
"https://www.citymax-gt.com/119765/Renta-local-comercial-en-la-Reforma-zona-9-", 
"https://www.citymax-gt.com/120210/Loca-comercial-en-renta-entrada-al-Quiche-zona-1", 
"https://www.citymax-gt.com/120488/Oficina-en-Alquiler-en-Edificio-Nova-Zona-9", 
"https://www.citymax-gt.com/120489/Oficina-Nueva-en-Alquiler-en-Zona-9", 
"https://www.citymax-gt.com/120500/Oficina-en-Alquiler-en-Avenida-Reforma-Zona-9", 
"https://www.citymax-gt.com/120501/Nueva-Oficina-en-Renta-en-Zona-9-Ave.-Reforma-Z.9", 
"https://www.citymax-gt.com/120523/Ofibodega-en-Alquiler-en-InterNaranjo-El-Naranjo-Mixco", 
"https://www.citymax-gt.com/120524/Alquilo-Ofibodega-en-Internaranjo-Z.4-de-Mixco-Naranjo", 
"https://www.citymax-gt.com/121152/Alquilo-local-comercial-en-San-Lucas-Sacatepéquez", 
"https://www.citymax-gt.com/121160/Alquiler-de-local-comercial-en--San-Lucas", 
"https://www.citymax-gt.com/121284/Apartamento-en-renta--en-zona-10-cerca-de-20-calle", 
"https://www.citymax-gt.com/122914/Apartamento-en-Residencial-San-Antonio-km-16.5-CES", 
"https://www.citymax-gt.com/123280/Oficina-Amueblada-en-Renta-zona-9", 
"https://www.citymax-gt.com/123290/Oficinas-en-alquiler-en-Europlaza", 
"https://www.citymax-gt.com/123425/Rento-Terreno-comercial-San-Jose-Pinula-", 
"https://www.citymax-gt.com/123460/Oficinas-equipadas-en-Alquiler-Zona-14-Europlaza", 
"https://www.citymax-gt.com/123462/Espacio-en-Oficina-en-Renta-Edificio-Europlaza-Zona-14", 
"https://www.citymax-gt.com/123468/Alquilo-Oficina-en-Zona-14-Edificio-Europlaza", 
"https://www.citymax-gt.com/125396/Final-Hincapié-Renta-apartamento-zona-13", 
"https://www.citymax-gt.com/126065/Bodeguita-en-Alquiler-zona-7-Calzada-San-Juan", 
"https://www.citymax-gt.com/81501/LOCAL-Comercial-dentro-de-Centro-Comercial-en-Roosevelt", 
"https://www.citymax-gt.com/82011/Alquilo-Apartamento-con-164.00m2-en-Zona-10-Diagonal", 
"https://www.citymax-gt.com/85725/CITYMAX-RENTA-LOCAL-EXCELENTE-UBICACI%C3%93N-COMERCIAL-Z.-9-", 
"https://www.citymax-gt.com/86461/Renta-Apartamento-Villa-Los-Alamos-con-Linea-Blanca-", 
"https://www.citymax-gt.com/90269/Apartamento-Alquiler-Zona-13-Elgin", 
"https://www.citymax-gt.com/92561/Amplia-Oficina-Amueblada-en-Renta-en-Zona-10", 
"https://www.citymax-gt.com/93308/Alquiler-de-Oficina-zona-10-Excelente-Ubicaci%C3%B3n", 
"https://www.citymax-gt.com/93681/OFIBODEGA-EN-RENTA-CARR.-A-ATLANTICO-NUEVA-", 
"https://www.citymax-gt.com/96359/Oficina-En-Renta-Para-Estrenar-Edificio-Moderno-Zona-15", 
"https://www.citymax-gt.com/99013/Plaza-Hincapi%C3%A9-se-Alquila-Local-48-mts-zona-13", 
"https://www.citymax-gt.com/59456/CityMax-alquila-apartamento-amueblado-en-zona-14-", 
"https://www.citymax-gt.com/60391/Apartamento-en-renta-en-primer-nivel-zona-14-Guatemala", 
"https://www.citymax-gt.com/61133/Rento-apartamento-en-zona-13", 
"https://www.citymax-gt.com/61274/En-Renta-Dos-Niveles-de-Locales-en-Ciudad-Peronia", 
"https://www.citymax-gt.com/61405/Alquilo-Oficina-con-359.62m2-en-Zona-10-Guatemala", 
"https://www.citymax-gt.com/62040/Alquilo-Oficina-con-172.25m2-en-Zona-10-PAO-006-07-07-1", 
"https://www.citymax-gt.com/62401/Alquilo-Oficina-con-300.00m2-en-Zona-14-PAO-025-03-09-17", 
"https://www.citymax-gt.com/75715/Alquilo-Oficina-Amueblada-en-Zona-10-", 
"https://www.citymax-gt.com/83042/Alquilo-Oficina-con-93.96m2-Carretera-El-Salvador", 
"https://www.citymax-gt.com/84687/Oficina-NUEVA-en-Alquiler-Zona-10", 
"https://www.citymax-gt.com/115474/Oficina-en-Renta-en-Zona-10-en-Paseo-Plaza", 
"https://www.citymax-gt.com/119263/Apartamento-en-Alquiler-Amueblado-en-Milenia-Zona-10", 
"https://www.citymax-gt.com/128286/En-Renta-Apartamento-para-estrenar-en-Zona-10", 
"https://www.citymax-gt.com/128714/En-Renta-Edificio-Comercial-en-Zona-11-", 
"https://www.citymax-gt.com/129089/Apartamento-Amueblado-en-Zona-15-EPIC", 
"https://www.citymax-gt.com/129163/Apartamento-en-Renta-en-Lirios-de-Cayalá-Zona-16", 
"https://www.citymax-gt.com/129166/Apartamento-en-Renta-en-Lirios-Zona-16", 
"https://www.citymax-gt.com/129170/Apartamento-Amueblado-en-RENTA-en-Zona-16-Cayalá", 
"https://www.citymax-gt.com/129568/Apartamento-Amueblado-en-Renta-en-Zona-10-", 
"https://www.citymax-gt.com/55945/%C2%A1Apartamento-en-en-Renta-en-la-ZONA-15", 
"https://www.citymax-gt.com/128745/Casa-en-Renta-Remodelada-en-Santa-Rosalia-km-12.5-CES", 
"https://www.citymax-gt.com/128748/Apartamento-en-Renta-Mediterranium-Zona-15-V.H.1", 
"https://www.citymax-gt.com/129138/Apartamento-en-Renta-Pacifica-Plaza-zona-14------------", 
"https://www.citymax-gt.com/129623/Apartamento-En-Renta-Zona-11-Edif.-Loira-Mariscal-", 
"https://www.citymax-gt.com/129626/Apartamento-en-Renta-Santa-Maria-de-las-Charcas-Zona-11", 
"https://www.citymax-gt.com/56315/Alquilo-Apartamento-en-zona-10", 
"https://www.citymax-gt.com/56473/Alquilo-Apartamento-con-202.00m2-en-Zona-14-PAA-004-04-12", 
"https://www.citymax-gt.com/57230/Alquilo-oficina-en-zona-11-%C2%A1CityMax", 
"https://www.citymax-gt.com/57529/Oficinaen-alquiler-ZONA-13-excelente-ubicaci%C3%B3n", 
"https://www.citymax-gt.com/58032/Alquilo-Local-con-60.00m2-en-Villa-Nueva-PAL-019-04-09-11", 
"https://www.citymax-gt.com/122953/En-renta-Ofibodega-dentro-de-complejo--San-Jose-Pinula", 
"https://www.citymax-gt.com/123504/Rento-Apartamento-Amueblado-2-habitaciones,-zona-10", 
"https://www.citymax-gt.com/126114/Terreno-en-Alquiler-en-la-Zona-14-Guatemala", 
"https://www.citymax-gt.com/126431/Ofibodega-en-Alquiler-en-Amatitlán-de-5,887-m2", 
"https://www.citymax-gt.com/128444/Apartamento-Amueblado-en-renta-Viro-zona-11-Mariscal", 
"https://www.citymax-gt.com/59825/Oficina-en-renta-en-zona-10-Guatemala", 
"https://www.citymax-gt.com/60613/Alquilo-Apartamento-en-zona-14-Guatemala", 
"https://www.citymax-gt.com/60787/Alquilo-Apartamento-con-164.18m2-en-Zona-14-PAA-047-11-10", 
"https://www.citymax-gt.com/74856/BODEGA-EN-ALQUILER-ZONA-17-CENTRO-DE-NEGOCIOS-LA-PAZ", 
"https://www.citymax-gt.com/76228/Alquiler-oficinas-en-zona-16-Cayala", 
"https://www.citymax-gt.com/124180/APARTAMENTO-AMUEBLADO-EN-RENTA-EN-ZONA-13", 
"https://www.citymax-gt.com/124474/Apartamento-NUEVO-en-Renta-en-Zona-15-", 
"https://www.citymax-gt.com/124475/Apartamento-Nuevo-en-Zona-15-para-Alquiler", 
"https://www.citymax-gt.com/124476/Alquilo-Apartamento-Nuevo-en-Zona-15-Vista-Hermosa", 
"https://www.citymax-gt.com/124480/Renta-de-Apartamento-en-Edificio-Nuevo-de-la-Zona-15", 
"https://www.citymax-gt.com/124481/Alquiler-en-Edificio-Nuevo-de-la-zona-15-Apartamento-", 
"https://www.citymax-gt.com/124485/Alquiler-Edificio-Baden-Z.15-Apartamento-2-habitaciones", 
"https://www.citymax-gt.com/124486/Apartamento-con-3-habitaciones-en-Renta-zona-15", 
"https://www.citymax-gt.com/124489/Apartamento-en-Renta-Zona-15-+-habitación-de-servicio", 
"https://www.citymax-gt.com/124490/Apartamento-en-Renta-con-3-habitaciones-en-zona-15", 
"https://www.citymax-gt.com/87133/Citymax-Renta-Apartamento-En-Muxbal-Km-8.8-con-E.-Vista", 
"https://www.citymax-gt.com/92437/Casa-Comercial-en-Alquiler-Final-Hincapie", 
"https://www.citymax-gt.com/93852/En-renta-oficina-en-Zona-Pradera-zona-10-Guatemala-", 
"https://www.citymax-gt.com/94589/Rento-apartamento-tipo-estudio-en-zona-15", 
"https://www.citymax-gt.com/98530/Apartamento-en-venta-o-alquiler-Z15-%C2%A1proyecto-nuevo", 
"https://www.citymax-gt.com/99672/Apartamento-Amueblado-1-habitacion-Zona-15-Guatemala", 
"https://www.citymax-gt.com/100973/Edificio-en-alquiler-Boulevard-Los-Pr%C3%B3ceres-Z10", 
"https://www.citymax-gt.com/101323/Aparta-Estudio-amueblado-en-alquiler-zona-15-Guatemala", 
"https://www.citymax-gt.com/103075/Bodega-Industrial-en-Alquiler-Autopista-Puerto-Quetzal", 
"https://www.citymax-gt.com/105827/Oficina-en-Renta-enZona-10-Avenida-Reforma-Guatemala", 
"https://www.citymax-gt.com/76232/Alquiler-OFICINA-EN-RENTA-EN-ZONA-16-", 
"https://www.citymax-gt.com/76233/Oficina-en-renta-en-zona-16-Blvd.-Landivar-Cayala", 
"https://www.citymax-gt.com/76234/Oficinas-en-renta-en-zona-16-Guatemala", 
"https://www.citymax-gt.com/76236/Oficina-en-alquiler-Zona-16-Ciudad-de-Guatemala", 
"https://www.citymax-gt.com/76240/Rento-oficina-en-Cayala-zona-16", 
"https://www.citymax-gt.com/86472/BODEGA-DE-510MT-EN-ALQUILER-ZONA-4-MIXCO-EL-NARANJO", 
"https://www.citymax-gt.com/86645/Oficina-en-renta-zona-15-Vista-Hermosa-edificio-nuevo", 
"https://www.citymax-gt.com/86990/Oficina-en-renta-en-Distrito-Moda-zona-16-Guatemala", 
"https://www.citymax-gt.com/87445/Oficina-en-renta-en-Insigne-zona-15-Guatemala", 
"https://www.citymax-gt.com/90113/Alquiler-Oficina-a-estrenar-en-la-Zona-15-V.-H.", 
"https://www.citymax-gt.com/124593/Renta-Apartamento-Amueblado-nuevo-en-AIRALI-ZONA-10", 
"https://www.citymax-gt.com/124594/APARTAMENTO-EN-RENTA-EN-EDIFICIO-BADEN-ZONA-15", 
"https://www.citymax-gt.com/126463/APARTAMENTO-AMUEBLADO-EN-ATTICA-ZONA-14", 
"https://www.citymax-gt.com/126687/Alquiler-de-oficinas-en-Domani-zona-15", 
"https://www.citymax-gt.com/126867/APARTAMENTO-EN-RENTA-EN-TIFANNY-CAÑADA-ZONA-14", 
"https://www.citymax-gt.com/127271/Nuevo-apartamento-amueblado-en-Américas-zona-13", 
"https://www.citymax-gt.com/128405/Apartamento-en-Renta-Milenia-zona-10-Guatemala", 
"https://www.citymax-gt.com/105830/Alquilo-Oficina-Tabicada-en-Zona-10-Avenida-Reforma", 
"https://www.citymax-gt.com/106270/Oficina-en-Renta-en-Zona-11-", 
"https://www.citymax-gt.com/107779/Local-comercial-en-renta-en-zona-7-Calzada-San-Juan", 
"https://www.citymax-gt.com/111486/Alquilo-oficina-ubicada-en-zona-15-", 
"https://www.citymax-gt.com/112615/Rento-Apartamento-tipo-estudio-z.15-Col.-El-Maestro", 
"https://www.citymax-gt.com/112726/Apartamento-en-Renta-en-Tiffany-Zona-14", 
"https://www.citymax-gt.com/112733/Casa-en-renta-con-uso-suelo-comercial-zona-14-", 
"https://www.citymax-gt.com/112749/Alquiler-de-bodega-en-carretera-a-Puerto-Quetzal-", 
"https://www.citymax-gt.com/112794/Rento-Terreno-para-uso-comercial-San-Jose-Pinula-", 
"https://www.citymax-gt.com/114629/Apartamento-en-Renta-de-1-habitación-en-zona-16-", 
"https://www.citymax-gt.com/90803/Oficina-en-Alquiler-con-Acabados-Insigne-Vista-Hermosa", 
"https://www.citymax-gt.com/93000/Oficina-Edificio-INSIGNE", 
"https://www.citymax-gt.com/95944/Oficinaen-renta-Distrito-Moda-zona-16-Guatemala", 
"https://www.citymax-gt.com/95945/Alquilo-oficina-Distrito-Moda-zona-16-Guatemala", 
"https://www.citymax-gt.com/95946/Oficinaen-renta-Distrito-Moda-zona-16-Guatemala", 
"https://www.citymax-gt.com/95982/Oficina-en-renta-ubicadas-en-zona-16", 
"https://www.citymax-gt.com/108445/Oficinas-en-venta-en-zona-15-Boulevard-Vista-Hermosa", 
"https://www.citymax-gt.com/112513/Rento-oficina-en-zona-15-Guatemala", 
"https://www.citymax-gt.com/112514/Alquilo-lindo-espacio-para-oficina-en-zona-15", 
"https://www.citymax-gt.com/112516/Oficina-virtual-en-renta-ubicada-en-zona-15-Guatemala", 
"https://www.citymax-gt.com/115108/Apartamento-en-renta-en-Cupertino-Muxbal-", 
"https://www.citymax-gt.com/119064/Oficina-en-Alquiler-Zona-10-cerca-Fontabella", 
"https://www.citymax-gt.com/119198/Ofibodega-en-ZENTRO-PLAZA-SUR,-zona-12-", 
"https://www.citymax-gt.com/122494/Alquilo-apartamento-amueblado-en-zona-10", 
"https://www.citymax-gt.com/122943/Rento-Ofibodega-en-ntrada-San-José-Pinula-391.95mts2", 
"https://www.citymax-gt.com/122946/Alquilo-Ofibodega-en-San-Jose-Pinula-km-18----------", 
"https://www.citymax-gt.com/122948/En-Alquiler-Bodega-343.80mts2-entrada-San-Jose-Pinula-", 
"https://www.citymax-gt.com/122949/Ofibodega-en-renta-en-CAES-San-Jose-Pinula-", 
"https://www.citymax-gt.com/122951/Alquilo-Ofibodega-de-366.45mts2-en-San-Jose-Pinula-km18", 
"https://www.citymax-gt.com/122952/Ofibodega-en-Alquiler-de-352.25mts-con-Mezzanine-", 
"https://www.citymax-gt.com/112528/Linda-oficina-en-renta-en-zona-15-", 
"https://www.citymax-gt.com/112529/Oficina-en-alquiler-zona-15-Insigne-", 
"https://www.citymax-gt.com/114881/OFICINA-EN-ALQUILER-EN-ZONA-16-CAYALA", 
"https://www.citymax-gt.com/114887/Oficina-en-alquiler-en-edificio-zona-16-Cayala-", 
"https://www.citymax-gt.com/114895/Oficina-Comercial-Renta-zona-16-Cayala", 
"https://www.citymax-gt.com/114922/Alquiler-de-Apartamento-en-MIXCO-Guatemala", 
"https://www.citymax-gt.com/115545/Oficina-en-alquiler-en-Domani-Zona-15", 
"https://www.citymax-gt.com/116465/OFICINA-EN-RENTA-EN-ZONA-15-EN-TORRE-TIGO", 
"https://www.citymax-gt.com/116469/RENTA-DE-OFICINA-EN-TORRE-TIGO-KM-9.5", 
"https://www.citymax-gt.com/120596/OFICINA-PARA-ESTRENAR-EN-EDIFICIO-SPAZIO-ZONA-15", 

]
# Captures data for a specific page with provided url
def load_urls(pageUrl):

    print("Getting page: {} - Items: {}".format(pageUrl.split("page/")[1], len(urls)))
    print("------------------------------------------------------------------------")

    source = requests.get(
        url=pageUrl,
        allow_redirects=True,
        headers={"User-Agent": "PostmanRuntime/7.28.4"},
    )

    soup = bs.BeautifulSoup(source.text, "html.parser")

    items = soup.find_all("h3", {"class": "property-title"})

    for item in items:
        url = item.find("a")["href"]

        with open("./scan-{}.txt".format(date.today()), "a") as scan:
            scan.writelines('"{}", \n'.format(str(url)))
            scan.close()


# Captures data for a specific entry/item with provided url
def load_item_data(item_url):
    print("loading {}".format(item_url))
    source = requests.get(
        url=item_url,
        allow_redirects=True,
        headers={"User-Agent": "PostmanRuntime/7.28.4"},
    )

    soup = bs.BeautifulSoup(source.text, "html.parser")

    items = soup.find_all("div", {"class": "alert" })[1]

    params = items.find_all("li")

    metaitems = soup.find_all("ul", {"class": "list-three-col"})[1]
    metaparams = metaitems.find_all("li")


    param_index = {}

    for item in params:
        name = str(item).split("</strong>")[0].split("<strong>")[1].strip()
        value = str(item).split("</strong>")[1].split("</li>")[0].strip()

        param_index[name] = value

    for item in metaparams:
        name = str(item).split("<strong>")[1].split("</strong>")[0].strip()
        value = str(item).split("<strong>")[1].split("</strong>")[1].split("</li>")[0].strip()

        param_index[name] = value




    mt2 = "none"
    sector = "none"
    precio = "none"
    habitaciones = "none"
    banos = "none"
    parqueos = "none"
    nombre_agente = "none"
    numero_agente = "latest"

    try:
        sector = param_index["Sector:"]
    except (IndexError, AttributeError, KeyError):
        pass

    try:
        precio = param_index["Precio:"].split("\">")[1].split("</span>")[0].strip()
    except (IndexError, AttributeError, KeyError):
        pass

    try:
        habitaciones = param_index["Habitaciones/Ambientes:"]
    except (IndexError, AttributeError, KeyError):
        pass

    try:
        banos = param_index["Baños:"]
    except (IndexError, AttributeError, KeyError):
        pass

    try:
        parqueos = param_index["Estacionamientos:"]
    except (IndexError, AttributeError, KeyError):
        pass

    try:
        mt2 = param_index["Área Construcción"]
    except (IndexError, AttributeError, KeyError):
        pass

    item = {
        "eventType": "index_item",
        "available_timestamp": str(date.today()),
        "id": item_url,
        "url": item_url,
        "module": "citymaxgt-gt",
        "mt2": mt2.strip(),
        "sector": sector.strip(),
        "precio": precio.strip(),
        "habitaciones": habitaciones.strip(),
        "banos": banos.strip(),
        "parqueos": parqueos.strip(),
        "nombre_agente": nombre_agente.strip(),
        "numero_agente": numero_agente.strip(),
        "type": "rent",
        "extras": [{"parent": "Comodidades", "fields": [{"name": "Piscina"}]}],
    }

    laraIndex(item)


def get():

    p = Pool(10)
    p.map(load_urls, urls_list)
    p.terminate()
    p.join()


def data():
    d = Pool(100)
    d.map(load_item_data, urls)
    d.terminate()
    d.join()


# get()
data()
