import bs4 as bs
import requests
import math
from datetime import date

from datetime import datetime as dt
from halo import Halo
import time
import requests

from multiprocessing import Pool


# apartamentos-en-alquiler
# apartamentos-en-venta

# casas-en-alquiler
# casas-en-venta-guatemala

urls_list = [
    "https://mapainmueble.com/casas-en-alquiler/page/1",
    "https://mapainmueble.com/casas-en-alquiler/page/2",
    "https://mapainmueble.com/casas-en-alquiler/page/3",
    "https://mapainmueble.com/casas-en-alquiler/page/4",
    "https://mapainmueble.com/casas-en-alquiler/page/5",
    "https://mapainmueble.com/casas-en-alquiler/page/6",
    "https://mapainmueble.com/casas-en-alquiler/page/7",
    "https://mapainmueble.com/casas-en-alquiler/page/8",
    "https://mapainmueble.com/casas-en-alquiler/page/9",
    "https://mapainmueble.com/casas-en-alquiler/page/10",
    "https://mapainmueble.com/casas-en-alquiler/page/11",
    "https://mapainmueble.com/casas-en-alquiler/page/12",
    "https://mapainmueble.com/casas-en-alquiler/page/13",
    "https://mapainmueble.com/casas-en-alquiler/page/14",
    "https://mapainmueble.com/casas-en-alquiler/page/15",
    "https://mapainmueble.com/casas-en-alquiler/page/16",
    "https://mapainmueble.com/casas-en-alquiler/page/17",
    "https://mapainmueble.com/casas-en-alquiler/page/18",
    "https://mapainmueble.com/casas-en-alquiler/page/19",
    "https://mapainmueble.com/casas-en-alquiler/page/20",
    "https://mapainmueble.com/casas-en-alquiler/page/21",
    "https://mapainmueble.com/casas-en-alquiler/page/22",
    "https://mapainmueble.com/casas-en-alquiler/page/23",
    "https://mapainmueble.com/casas-en-alquiler/page/24",
    "https://mapainmueble.com/casas-en-alquiler/page/25",
    "https://mapainmueble.com/casas-en-alquiler/page/26",
    "https://mapainmueble.com/casas-en-alquiler/page/27",
    "https://mapainmueble.com/casas-en-alquiler/page/28",
    "https://mapainmueble.com/casas-en-alquiler/page/29",
    "https://mapainmueble.com/casas-en-alquiler/page/30",
    "https://mapainmueble.com/casas-en-alquiler/page/31",
    "https://mapainmueble.com/casas-en-alquiler/page/32",
    "https://mapainmueble.com/casas-en-alquiler/page/33",
    "https://mapainmueble.com/casas-en-alquiler/page/34",
    "https://mapainmueble.com/casas-en-alquiler/page/35",
    "https://mapainmueble.com/casas-en-alquiler/page/36",
    "https://mapainmueble.com/casas-en-alquiler/page/37",
    "https://mapainmueble.com/casas-en-alquiler/page/38",
    "https://mapainmueble.com/casas-en-alquiler/page/39",
    "https://mapainmueble.com/casas-en-alquiler/page/40",
    "https://mapainmueble.com/casas-en-alquiler/page/41",
    "https://mapainmueble.com/casas-en-alquiler/page/42",
    "https://mapainmueble.com/casas-en-alquiler/page/43",
    "https://mapainmueble.com/casas-en-alquiler/page/44",
    "https://mapainmueble.com/casas-en-alquiler/page/45",
    "https://mapainmueble.com/casas-en-alquiler/page/46",
    "https://mapainmueble.com/casas-en-alquiler/page/47",
    "https://mapainmueble.com/casas-en-alquiler/page/48",
    "https://mapainmueble.com/casas-en-alquiler/page/49",
    "https://mapainmueble.com/casas-en-alquiler/page/50",
    "https://mapainmueble.com/casas-en-alquiler/page/51",
    "https://mapainmueble.com/casas-en-alquiler/page/52",
    "https://mapainmueble.com/casas-en-alquiler/page/53",
    "https://mapainmueble.com/casas-en-alquiler/page/54",
    "https://mapainmueble.com/casas-en-alquiler/page/55",
    "https://mapainmueble.com/casas-en-alquiler/page/56",
    "https://mapainmueble.com/casas-en-alquiler/page/57",
    "https://mapainmueble.com/casas-en-alquiler/page/58",
    "https://mapainmueble.com/casas-en-alquiler/page/59",
    "https://mapainmueble.com/casas-en-alquiler/page/60",
    "https://mapainmueble.com/casas-en-alquiler/page/61",
    "https://mapainmueble.com/casas-en-alquiler/page/62",
    "https://mapainmueble.com/casas-en-alquiler/page/63",
    "https://mapainmueble.com/casas-en-alquiler/page/64",
    "https://mapainmueble.com/casas-en-alquiler/page/65",
    "https://mapainmueble.com/casas-en-alquiler/page/66",
    "https://mapainmueble.com/casas-en-alquiler/page/67",
    "https://mapainmueble.com/casas-en-alquiler/page/68",
    "https://mapainmueble.com/casas-en-alquiler/page/69",
    "https://mapainmueble.com/casas-en-alquiler/page/70",
    "https://mapainmueble.com/casas-en-alquiler/page/71",
    "https://mapainmueble.com/casas-en-alquiler/page/72",
    "https://mapainmueble.com/casas-en-alquiler/page/73",
    "https://mapainmueble.com/casas-en-alquiler/page/74",
    "https://mapainmueble.com/casas-en-alquiler/page/75",
    "https://mapainmueble.com/casas-en-alquiler/page/76",
    "https://mapainmueble.com/casas-en-alquiler/page/77",
    "https://mapainmueble.com/casas-en-alquiler/page/78",
    "https://mapainmueble.com/casas-en-alquiler/page/79",
    "https://mapainmueble.com/casas-en-alquiler/page/80",
    "https://mapainmueble.com/casas-en-alquiler/page/81",
    "https://mapainmueble.com/casas-en-alquiler/page/82",
    "https://mapainmueble.com/casas-en-alquiler/page/83",
    "https://mapainmueble.com/casas-en-alquiler/page/84",
    "https://mapainmueble.com/casas-en-alquiler/page/85",
    "https://mapainmueble.com/casas-en-alquiler/page/86",
    "https://mapainmueble.com/casas-en-alquiler/page/87",
    "https://mapainmueble.com/casas-en-alquiler/page/88",
    "https://mapainmueble.com/casas-en-alquiler/page/89",
    "https://mapainmueble.com/casas-en-alquiler/page/90",
    "https://mapainmueble.com/casas-en-alquiler/page/91",
    "https://mapainmueble.com/casas-en-alquiler/page/92",
    "https://mapainmueble.com/casas-en-alquiler/page/93",
    "https://mapainmueble.com/casas-en-alquiler/page/94",
    "https://mapainmueble.com/casas-en-alquiler/page/95",
    "https://mapainmueble.com/casas-en-alquiler/page/96",
    "https://mapainmueble.com/casas-en-alquiler/page/97",
    "https://mapainmueble.com/casas-en-alquiler/page/98",
    "https://mapainmueble.com/casas-en-alquiler/page/99",
    "https://mapainmueble.com/casas-en-alquiler/page/100",
    "https://mapainmueble.com/casas-en-alquiler/page/101",
    "https://mapainmueble.com/casas-en-alquiler/page/102",
    "https://mapainmueble.com/casas-en-alquiler/page/103",
    "https://mapainmueble.com/casas-en-alquiler/page/104",
    "https://mapainmueble.com/casas-en-alquiler/page/105",
    "https://mapainmueble.com/casas-en-alquiler/page/106",
    "https://mapainmueble.com/casas-en-alquiler/page/107",
    "https://mapainmueble.com/casas-en-alquiler/page/108",
    "https://mapainmueble.com/casas-en-alquiler/page/109",
    "https://mapainmueble.com/casas-en-alquiler/page/110",
    "https://mapainmueble.com/casas-en-alquiler/page/111",
    "https://mapainmueble.com/casas-en-alquiler/page/112",
    "https://mapainmueble.com/casas-en-alquiler/page/113",
    "https://mapainmueble.com/casas-en-alquiler/page/114",
    "https://mapainmueble.com/casas-en-alquiler/page/115",
    "https://mapainmueble.com/casas-en-alquiler/page/116",
    "https://mapainmueble.com/casas-en-alquiler/page/117",
    "https://mapainmueble.com/casas-en-alquiler/page/118",
    "https://mapainmueble.com/casas-en-alquiler/page/119",
    "https://mapainmueble.com/casas-en-alquiler/page/120",
    "https://mapainmueble.com/casas-en-alquiler/page/121",
    "https://mapainmueble.com/casas-en-alquiler/page/122",
    "https://mapainmueble.com/casas-en-alquiler/page/123",
    "https://mapainmueble.com/casas-en-alquiler/page/124",
    "https://mapainmueble.com/casas-en-alquiler/page/125",
    "https://mapainmueble.com/casas-en-alquiler/page/126",
    "https://mapainmueble.com/casas-en-alquiler/page/127",
    "https://mapainmueble.com/casas-en-alquiler/page/128",
    "https://mapainmueble.com/casas-en-alquiler/page/129",
    "https://mapainmueble.com/casas-en-alquiler/page/130",
    "https://mapainmueble.com/casas-en-alquiler/page/131",
    "https://mapainmueble.com/casas-en-alquiler/page/132",
    "https://mapainmueble.com/casas-en-alquiler/page/133",
    "https://mapainmueble.com/casas-en-alquiler/page/134",
    "https://mapainmueble.com/casas-en-alquiler/page/135",
    "https://mapainmueble.com/casas-en-alquiler/page/136",
    "https://mapainmueble.com/casas-en-alquiler/page/137",
    "https://mapainmueble.com/casas-en-alquiler/page/138",
    "https://mapainmueble.com/casas-en-alquiler/page/139",
    "https://mapainmueble.com/casas-en-alquiler/page/140",
    "https://mapainmueble.com/casas-en-alquiler/page/141",
    "https://mapainmueble.com/casas-en-alquiler/page/142",
    "https://mapainmueble.com/casas-en-alquiler/page/143",
    "https://mapainmueble.com/casas-en-alquiler/page/144",
    "https://mapainmueble.com/casas-en-alquiler/page/145",
    "https://mapainmueble.com/casas-en-alquiler/page/146",
    "https://mapainmueble.com/casas-en-alquiler/page/147",
    "https://mapainmueble.com/casas-en-alquiler/page/148",
    "https://mapainmueble.com/casas-en-alquiler/page/149",
    "https://mapainmueble.com/casas-en-alquiler/page/150",
    "https://mapainmueble.com/casas-en-alquiler/page/151",
    "https://mapainmueble.com/casas-en-alquiler/page/152",
    "https://mapainmueble.com/casas-en-alquiler/page/153",
    "https://mapainmueble.com/casas-en-alquiler/page/154",
    "https://mapainmueble.com/casas-en-alquiler/page/155",
    "https://mapainmueble.com/casas-en-alquiler/page/156",
    "https://mapainmueble.com/casas-en-alquiler/page/157",
    "https://mapainmueble.com/casas-en-alquiler/page/158",
    "https://mapainmueble.com/casas-en-alquiler/page/159",
    "https://mapainmueble.com/casas-en-alquiler/page/160",
    "https://mapainmueble.com/casas-en-alquiler/page/161",
    "https://mapainmueble.com/casas-en-alquiler/page/162",
    "https://mapainmueble.com/casas-en-alquiler/page/163",
    "https://mapainmueble.com/casas-en-alquiler/page/164",
    "https://mapainmueble.com/casas-en-alquiler/page/165",
    "https://mapainmueble.com/casas-en-alquiler/page/166",
    "https://mapainmueble.com/casas-en-alquiler/page/167",
    "https://mapainmueble.com/casas-en-alquiler/page/168",
    "https://mapainmueble.com/casas-en-alquiler/page/169",
    "https://mapainmueble.com/casas-en-alquiler/page/170",
    "https://mapainmueble.com/casas-en-alquiler/page/171",
    "https://mapainmueble.com/casas-en-alquiler/page/172",
    "https://mapainmueble.com/casas-en-alquiler/page/173",
    "https://mapainmueble.com/casas-en-alquiler/page/174",
    "https://mapainmueble.com/casas-en-alquiler/page/175",
    "https://mapainmueble.com/casas-en-alquiler/page/176",
    "https://mapainmueble.com/casas-en-alquiler/page/177",
    "https://mapainmueble.com/casas-en-alquiler/page/178",
    "https://mapainmueble.com/casas-en-alquiler/page/179",
    "https://mapainmueble.com/casas-en-alquiler/page/180",
    "https://mapainmueble.com/casas-en-alquiler/page/181",
    "https://mapainmueble.com/casas-en-alquiler/page/182",
    "https://mapainmueble.com/casas-en-alquiler/page/183",
    "https://mapainmueble.com/casas-en-alquiler/page/184",
    "https://mapainmueble.com/casas-en-alquiler/page/185",
    "https://mapainmueble.com/casas-en-alquiler/page/186",
    "https://mapainmueble.com/casas-en-alquiler/page/187",
    "https://mapainmueble.com/casas-en-alquiler/page/188",
    "https://mapainmueble.com/casas-en-alquiler/page/189",
    "https://mapainmueble.com/casas-en-alquiler/page/190",
    "https://mapainmueble.com/casas-en-alquiler/page/191",
    "https://mapainmueble.com/casas-en-alquiler/page/192",
    "https://mapainmueble.com/casas-en-alquiler/page/193",
    "https://mapainmueble.com/casas-en-alquiler/page/194",
    "https://mapainmueble.com/casas-en-alquiler/page/195",
    "https://mapainmueble.com/casas-en-alquiler/page/196",
    "https://mapainmueble.com/casas-en-alquiler/page/197",
    "https://mapainmueble.com/casas-en-alquiler/page/198",
    "https://mapainmueble.com/casas-en-alquiler/page/199",
    "https://mapainmueble.com/casas-en-alquiler/page/200",
    "https://mapainmueble.com/casas-en-alquiler/page/201",
    "https://mapainmueble.com/casas-en-alquiler/page/202",
    "https://mapainmueble.com/casas-en-alquiler/page/203",
    "https://mapainmueble.com/casas-en-alquiler/page/204",
    "https://mapainmueble.com/casas-en-alquiler/page/205",
    "https://mapainmueble.com/casas-en-alquiler/page/206",
    "https://mapainmueble.com/casas-en-alquiler/page/207",
    "https://mapainmueble.com/casas-en-alquiler/page/208",
    "https://mapainmueble.com/casas-en-alquiler/page/209",
    "https://mapainmueble.com/casas-en-alquiler/page/210",
    "https://mapainmueble.com/casas-en-alquiler/page/211",
    "https://mapainmueble.com/casas-en-alquiler/page/212",
    "https://mapainmueble.com/casas-en-alquiler/page/213",
    "https://mapainmueble.com/casas-en-alquiler/page/214",
    "https://mapainmueble.com/casas-en-alquiler/page/215",
    "https://mapainmueble.com/casas-en-alquiler/page/216",
    "https://mapainmueble.com/casas-en-alquiler/page/217",
    "https://mapainmueble.com/casas-en-alquiler/page/218",
    "https://mapainmueble.com/casas-en-alquiler/page/219",
    "https://mapainmueble.com/casas-en-alquiler/page/220",
    "https://mapainmueble.com/casas-en-alquiler/page/221",
    "https://mapainmueble.com/casas-en-alquiler/page/222",
    "https://mapainmueble.com/casas-en-alquiler/page/223",
    "https://mapainmueble.com/casas-en-alquiler/page/224",
    "https://mapainmueble.com/casas-en-alquiler/page/225",
    "https://mapainmueble.com/casas-en-alquiler/page/226",
    "https://mapainmueble.com/casas-en-alquiler/page/227",
    "https://mapainmueble.com/casas-en-alquiler/page/228",
    "https://mapainmueble.com/casas-en-alquiler/page/229",
    "https://mapainmueble.com/casas-en-alquiler/page/230",
    "https://mapainmueble.com/casas-en-alquiler/page/231",
    "https://mapainmueble.com/casas-en-alquiler/page/232",
    "https://mapainmueble.com/casas-en-alquiler/page/233",
    "https://mapainmueble.com/casas-en-alquiler/page/234",
    "https://mapainmueble.com/casas-en-alquiler/page/235",
    "https://mapainmueble.com/casas-en-alquiler/page/236",
    "https://mapainmueble.com/casas-en-alquiler/page/237",
    "https://mapainmueble.com/casas-en-alquiler/page/238",
    "https://mapainmueble.com/casas-en-alquiler/page/239",
    "https://mapainmueble.com/casas-en-alquiler/page/240",
    "https://mapainmueble.com/casas-en-alquiler/page/241",
    "https://mapainmueble.com/casas-en-alquiler/page/242",
    "https://mapainmueble.com/casas-en-alquiler/page/243",
    "https://mapainmueble.com/casas-en-alquiler/page/244",
    "https://mapainmueble.com/casas-en-alquiler/page/245",
    "https://mapainmueble.com/casas-en-alquiler/page/246",
    "https://mapainmueble.com/casas-en-alquiler/page/247",
    "https://mapainmueble.com/casas-en-alquiler/page/248",
    "https://mapainmueble.com/casas-en-alquiler/page/249",
    "https://mapainmueble.com/casas-en-alquiler/page/250",
    "https://mapainmueble.com/casas-en-alquiler/page/251",
    "https://mapainmueble.com/casas-en-alquiler/page/252",
    "https://mapainmueble.com/casas-en-alquiler/page/253",
    "https://mapainmueble.com/casas-en-alquiler/page/254",
    "https://mapainmueble.com/casas-en-alquiler/page/255",
    "https://mapainmueble.com/casas-en-alquiler/page/256",
    "https://mapainmueble.com/casas-en-alquiler/page/257",
    "https://mapainmueble.com/casas-en-alquiler/page/258",
    "https://mapainmueble.com/casas-en-alquiler/page/259",
    "https://mapainmueble.com/casas-en-alquiler/page/260",
    "https://mapainmueble.com/casas-en-alquiler/page/261",
    "https://mapainmueble.com/casas-en-alquiler/page/262",
    "https://mapainmueble.com/casas-en-alquiler/page/263",
    "https://mapainmueble.com/casas-en-alquiler/page/264",
    "https://mapainmueble.com/casas-en-alquiler/page/265",
    "https://mapainmueble.com/casas-en-alquiler/page/266",
    "https://mapainmueble.com/casas-en-alquiler/page/267",
    "https://mapainmueble.com/casas-en-alquiler/page/268",
    "https://mapainmueble.com/casas-en-alquiler/page/269",
    "https://mapainmueble.com/casas-en-alquiler/page/270",
    "https://mapainmueble.com/casas-en-alquiler/page/271",
    "https://mapainmueble.com/casas-en-alquiler/page/272",
    "https://mapainmueble.com/casas-en-alquiler/page/273",
    "https://mapainmueble.com/casas-en-alquiler/page/274",
    "https://mapainmueble.com/casas-en-alquiler/page/275",
    "https://mapainmueble.com/casas-en-alquiler/page/276",
    "https://mapainmueble.com/casas-en-alquiler/page/277",
    "https://mapainmueble.com/casas-en-alquiler/page/278",
    "https://mapainmueble.com/casas-en-alquiler/page/279",
    "https://mapainmueble.com/casas-en-alquiler/page/280",
    "https://mapainmueble.com/casas-en-alquiler/page/281",
    "https://mapainmueble.com/casas-en-alquiler/page/282",
    "https://mapainmueble.com/casas-en-alquiler/page/283",
    "https://mapainmueble.com/casas-en-alquiler/page/284",
    "https://mapainmueble.com/casas-en-alquiler/page/285",
    "https://mapainmueble.com/casas-en-alquiler/page/286",
    "https://mapainmueble.com/casas-en-alquiler/page/287",
    "https://mapainmueble.com/casas-en-alquiler/page/288",
    "https://mapainmueble.com/casas-en-alquiler/page/289",
    "https://mapainmueble.com/casas-en-alquiler/page/290",
    "https://mapainmueble.com/casas-en-alquiler/page/291",
    "https://mapainmueble.com/casas-en-alquiler/page/292",
    "https://mapainmueble.com/casas-en-alquiler/page/293",
    "https://mapainmueble.com/casas-en-alquiler/page/294",
    "https://mapainmueble.com/casas-en-alquiler/page/295",
    "https://mapainmueble.com/casas-en-alquiler/page/296",
    "https://mapainmueble.com/casas-en-alquiler/page/297",
    "https://mapainmueble.com/casas-en-alquiler/page/298",
    "https://mapainmueble.com/casas-en-alquiler/page/299",
    "https://mapainmueble.com/casas-en-alquiler/page/300",
    "https://mapainmueble.com/casas-en-alquiler/page/301",
    "https://mapainmueble.com/casas-en-alquiler/page/302",
    "https://mapainmueble.com/casas-en-alquiler/page/303",
    "https://mapainmueble.com/casas-en-alquiler/page/304",
    "https://mapainmueble.com/casas-en-alquiler/page/305",
    "https://mapainmueble.com/casas-en-alquiler/page/306",
    "https://mapainmueble.com/casas-en-alquiler/page/307",
    "https://mapainmueble.com/casas-en-alquiler/page/308",
    "https://mapainmueble.com/casas-en-alquiler/page/309",
    "https://mapainmueble.com/casas-en-alquiler/page/310",
    "https://mapainmueble.com/casas-en-alquiler/page/311",
    "https://mapainmueble.com/casas-en-alquiler/page/312",
    "https://mapainmueble.com/casas-en-alquiler/page/313",
    "https://mapainmueble.com/casas-en-alquiler/page/314",
    "https://mapainmueble.com/casas-en-alquiler/page/315",
    "https://mapainmueble.com/casas-en-alquiler/page/316",
    "https://mapainmueble.com/casas-en-alquiler/page/317",
    "https://mapainmueble.com/casas-en-alquiler/page/318",
    "https://mapainmueble.com/casas-en-alquiler/page/319",
    "https://mapainmueble.com/casas-en-alquiler/page/320",
    "https://mapainmueble.com/casas-en-alquiler/page/321",
    "https://mapainmueble.com/casas-en-alquiler/page/322",
    "https://mapainmueble.com/casas-en-alquiler/page/323",
    "https://mapainmueble.com/casas-en-alquiler/page/324",
    "https://mapainmueble.com/casas-en-alquiler/page/325",
    "https://mapainmueble.com/casas-en-alquiler/page/326",
    "https://mapainmueble.com/casas-en-alquiler/page/327",
    "https://mapainmueble.com/casas-en-alquiler/page/328",
    "https://mapainmueble.com/casas-en-alquiler/page/329",
    "https://mapainmueble.com/casas-en-alquiler/page/330",
    "https://mapainmueble.com/casas-en-alquiler/page/331",
    "https://mapainmueble.com/casas-en-alquiler/page/332",
    "https://mapainmueble.com/casas-en-alquiler/page/333",
]
url = "http://localhost:1337/v2/kazas"


def laraIndex(item):
    req = requests.post(url, json=item)
    print(req.text)


urls = [
    "https://mapainmueble.com/properties/amplia-casa-en-renta-en-san-lazaro-zona-15-dac7785/", 
"https://mapainmueble.com/properties/casa-en-alquiler-z-10-cac3151/", 
"https://mapainmueble.com/properties/alquilo-casa-en-carretera-al-salvador-bosque-escondido-DAC7782/", 
"https://mapainmueble.com/properties/rento-casa-en-ziona-16-DAC7781/", 
"https://mapainmueble.com/properties/casa-en-km-25-5-carretera-a-el-salvador-villa-venetto-DAC7773/", 
"https://mapainmueble.com/properties/linda-casa-en-renta-en-condominio-exclusivo-zona-15-dac7772/", 
"https://mapainmueble.com/properties/casa-en-venta-en-jardines-de-san-lazaro-santa-catarina-pinula-DAC7770/", 
"https://mapainmueble.com/properties/casa-tipo-townhouse-de-200-m2-de-construccion-en-renta-zona-15-DAC7767/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-la-montana-DAC7764/", 
"https://mapainmueble.com/properties/casa-de-220-m2-de-construccion-en-renta-zona-12-DAC7954/", 
"https://mapainmueble.com/properties/alquilo-casa-santa-rosalia-amplia-de-cuatro-dormitorios-dac7961/", 
"https://mapainmueble.com/properties/hermosa-propiedad-en-renta-zona-2-dac7958/", 
"https://mapainmueble.com/properties/casa-en-canadas-de-san-isidro-zona-16-dac7952/", 
"https://mapainmueble.com/properties/alquilo-hermosa-casa-en-carretera-al-salvador-DAC7949/", 
"https://mapainmueble.com/properties/rento-amplia-casa-en-carretera-al-salvador-DAC7948/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-10-dentro-de-condominio-de-cuatro-dormitorios-dac7945/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-colonia-mirador-1-DAC7941/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-10-de-mixco-la-comunidad-DAC7934/", 
"https://mapainmueble.com/properties/casas-en-zona-16-alquilo-casa-con-amplio-jardin-y-oficina-dac8038/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-10-sector-oakland-2-cac3190/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-canadas-de-san-isidro-dac7977/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-buganvilias-de-cayala-dac7975/", 
"https://mapainmueble.com/properties/casa-en-renta-con-jardin-zona-13-CAC3156/", 
"https://mapainmueble.com/properties/casa-en-renta-zona14-DAC7466/", 
"https://mapainmueble.com/properties/alquiler-de-casa-zona-15-amueblada-cac3048/", 
"https://mapainmueble.com/properties/casa-en-renta-km-18-5-codigo-cc30072-CAC3241/", 
"https://mapainmueble.com/properties/casa-en-renta-km-17-5-cod-cc30071-cac3240/", 
"https://mapainmueble.com/properties/hermosa-casa-en-alquiler-zona-15-2/", 
"https://mapainmueble.com/properties/casa-zona-15-amueblada/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-15-vh-ii/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-15-3/", 
"https://mapainmueble.com/properties/casa-en-renta-reina-sofa-zona-10/", 
"https://mapainmueble.com/properties/casa-en-zona-10-dentro-de-garita-para-oficinas-o-vivienda/", 
"https://mapainmueble.com/properties/renta-de-casa-en-zona-16-codigocc23871/", 
"https://mapainmueble.com/properties/casa-en-renta-km-13-ces-3/", 
"https://mapainmueble.com/properties/casa-en-venta-km-13-carretera-a-el-salvador-3-o-4-dormitorios/", 
"https://mapainmueble.com/properties/alquilo-bonita-casa-en-condominio-zona-14-la-villa-DAC8184/", 
"https://mapainmueble.com/properties/el-prado-DAC8183/", 
"https://mapainmueble.com/properties/en-venta-bella-casa-en-carretera-a-el-salvador-cac3238/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-carretera-a-el-salvador-CAC3236/", 
"https://mapainmueble.com/properties/alquiler-de-casa-fuera-de-garita-zona-11-mariscal-DAC8182/", 
"https://mapainmueble.com/properties/en-renta-townhouse-zona-14-el-campo-DAC8181/", 
"https://mapainmueble.com/properties/casa-en-residencial-los-diamantes-dac8180/", 
"https://mapainmueble.com/properties/casa-en-renta-villas-de-entreverdes-carretera-a-el-salvador-DAC8178/", 
"https://mapainmueble.com/properties/casa-en-renta-bellas-luces-santa-catarina-pinula-DAC8176/", 
"https://mapainmueble.com/properties/casa-en-renta-para-negocio-en-zona-15-dac7570/", 
"https://mapainmueble.com/properties/casa-amueblada-en-renta-en-santa-catarina-pinula-dac7569/", 
"https://mapainmueble.com/properties/casa-grande-en-renta-para-comercio-en-zona-15-vh1-dac7568/", 
"https://mapainmueble.com/properties/casa-en-alquiler-condominio-santa-anita-2-en-directo-3/", 
"https://mapainmueble.com/properties/preciosa-casa-en-renta-en-ramblas-de-cayala-dac7566/", 
"https://mapainmueble.com/properties/casa-en-renta-en-jardines-de-providencia-caes-DAC7560/", 
"https://mapainmueble.com/properties/vendo-casa-en-colonia-castillo-lara-zona-7-DAC7559/", 
"https://mapainmueble.com/properties/zona-16-sector-cayala-alquilo-casa-DAC7556/", 
"https://mapainmueble.com/properties/en-alquiler-casa-villas-del-campo-ces-DAC7553/", 
"https://mapainmueble.com/properties/casa-en-renta-condominio-ensenada-de-san-isidro-zona-16-DAC8163/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-13-dac8162/", 
"https://mapainmueble.com/properties/rento-amplia-casa-en-el-mejor-sector-de-zona-5-dac8159/", 
"https://mapainmueble.com/properties/casa-para-vivienda-u-oficina-zona-15-vista-hermosa-ii-DAC8158/", 
"https://mapainmueble.com/properties/casa-de-1-nivel-en-renta-zona-14-cod-dc9405-DAC8156/", 
"https://mapainmueble.com/properties/townhouse-en-alquiler-oakland-zona-10-dac8155/", 
"https://mapainmueble.com/properties/montebello-km-9-al-salvador-DAC8154/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-13-elgin-ii-DAC8153/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-10-para-vivienda-u-oficina-DAC8152/", 
"https://mapainmueble.com/properties/se-renta-hermosa-casa-en-condado-naranjo-DAC8076/", 
"https://mapainmueble.com/properties/casa-en-renta-DAC8074/", 
"https://mapainmueble.com/properties/casa-en-renta-ideal-para-oficina-DAC8073/", 
"https://mapainmueble.com/properties/se-renta-casa-en-condado-naranjo-DAC8072/", 
"https://mapainmueble.com/properties/ideal-oficinas-casa-de-un-nivel-en-renta-zona-11-cod-cc29952-CAC3204/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-13-elgin-2-DAC8070/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-10-sector-embajada-de-mexico-DAC8069/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-en-renta-en-km-24-2-caes-DAC8068/", 
"https://mapainmueble.com/properties/rento-casa-amueblada-km-12-5-ces-jardines-de-santa-rosalia-ref-5999-estudio-sala-familiar-3-hab-6-parqueos-5-banos-CAC3203/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-carretera-a-el-salvador-4/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-carretera-a-el-salvador-3/", 
"https://mapainmueble.com/properties/casa-residencial-para-estrenar-en-renta-en-oakland-dac5256/", 
"https://mapainmueble.com/properties/casa-en-alquiler-la-caada-zona-14-en-directo/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-la-caada-zona-14/", 
"https://mapainmueble.com/properties/casas-en-condominio-monterrosa-zona-14-dac5227/", 
"https://mapainmueble.com/properties/renta-de-casa-en-zona-10-codigocc24808/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-13-2/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-15/", 
"https://mapainmueble.com/properties/townhouse-en-renta-condominio-exclusivo-la-escalada-san-lazaro-zona-15-DAC8141/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-codig-cc30013-cac3223/", 
"https://mapainmueble.com/properties/alquilo-propiedad-casa-con-terreno-comerciale-DAC8139/", 
"https://mapainmueble.com/properties/casa-de-1-nivel-en-zona-15-CAC3222/", 
"https://mapainmueble.com/properties/casa-en-renta-km-19-a-san-jose-pinula-codig-cc30011-CAC3221/", 
"https://mapainmueble.com/properties/townhouse-en-renta-condominio-exclusivo-la-escalada-san-lazaro-zona-15-dac8138/", 
"https://mapainmueble.com/properties/se-alquila-primer-nivel-de-casa-colonia-centro-america-zona-7-cerca-periferico-DAC8137/", 
"https://mapainmueble.com/properties/alquilo-casa-de-3-dormitorios-en-puerta-grande-km-14-carretera-a-el-salvador-dac8136/", 
"https://mapainmueble.com/properties/preciosa-casa-en-las-rotondas-caes-km-18-5-caes-DAC8133/", 
"https://mapainmueble.com/properties/casa-amueblada-de-un-nivel-en-renta-zona-16-cod-cc30032a-CAC3230/", 
"https://mapainmueble.com/properties/casa-de-un-nivel-en-renta-zona-16-cod-cc30032-CAC3229/", 
"https://mapainmueble.com/properties/townhouse-en-alquiler-en-oakland-dac5553/", 
"https://mapainmueble.com/properties/casa-amueblada-en-renta-zona-11-cod-cc30030a-cac3228/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-11-codig-cc30030-CAC3227/", 
"https://mapainmueble.com/properties/rento-casa-z-13-col-elgin-ii-ref-6011-400-m2-4-hab-4-banos-3-parqueo-estudio-2200-CAC3226/", 
"https://mapainmueble.com/properties/townhouse-la-escalada-zona-15-DAC8143/", 
"https://mapainmueble.com/properties/zona-10-oakland-colonia-CAC3224/", 
"https://mapainmueble.com/properties/zona-10-ideal-kinder-agencias-de-publicidad-oficinas-en-general-dac8142/", 
"https://mapainmueble.com/properties/amplia-casa-en-renta-km-15-8-DAC8193/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-10-dac8192/", 
"https://mapainmueble.com/properties/casa-en-renta-villa-nueva-el-prado-de-linda-vista-DAC8191/", 
"https://mapainmueble.com/properties/casa-comercial-en-renta-excelente-punto-en-zona-9-DAC8189/", 
"https://mapainmueble.com/properties/alquiler-casa-en-colonia-oakland-remodelada-DAC8188/", 
"https://mapainmueble.com/properties/casa-en-renta-villas-del-campo-km-carretera-a-el-salvador-DAC8187/", 
"https://mapainmueble.com/properties/casa-en-renta-adentro-de-garita-en-bulevar-san-cristobal-DAC8186/", 
"https://mapainmueble.com/properties/casa-en-oakland-zona-10-DAC8185/", 
"https://mapainmueble.com/properties/casa-comercial-en-mateo-flores-zona-7-1-CAC3239/", 
"https://mapainmueble.com/properties/town-house-en-renta-zona-10-DAC8130/", 
"https://mapainmueble.com/properties/casa-en-renta-sector-a-10-dac8128/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-7-CAC3220/", 
"https://mapainmueble.com/properties/casa-en-venta-zona-14-dac8124/", 
"https://mapainmueble.com/properties/alquilo-amplia-casa-en-el-prado-zona-10-DAC8123/", 
"https://mapainmueble.com/properties/townhouse-en-renta-zona-10-codig-dc30007-DAC8122/", 
"https://mapainmueble.com/properties/alquilo-townhouse-en-zona-10-diagonal-6-dac8121/", 
"https://mapainmueble.com/properties/casa-en-la-canada-zona-14-dac8119/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-CAC3219/", 
"https://mapainmueble.com/properties/casa-en-colonia-el-campo/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-16-9/", 
"https://mapainmueble.com/properties/casa-en-renta-encanto-de-san-isidro-zona-16/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-16-8/", 
"https://mapainmueble.com/properties/casa-en-renta-villas-del-campo-caes-km-13-2/", 
"https://mapainmueble.com/properties/casa-en-renta-portal-del-cortijo-zona-10-bulevar-los-proceres/", 
"https://mapainmueble.com/properties/linda-casa-en-santa-rosalia/", 
"https://mapainmueble.com/properties/renta-de-townhouse-en-zona-14-codigocc26550/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-14/", 
"https://mapainmueble.com/properties/zona-7-mixco-quinta-los-encinos-casa-de-3-dormitorios-en-renta-DAC8092/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-elgin-ii-DAC8091/", 
"https://mapainmueble.com/properties/rento-casa-en-portal-del-bosques-1-en-km-22-carretera-al-salvador-DAC8089/", 
"https://mapainmueble.com/properties/casa-colonia-el-campo-zona-14-DAC8085/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-12-mundo-inmobiliario-DAC8083/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-13-codigo-1702-DAC8082/", 
"https://mapainmueble.com/properties/rento-casa-villas-entre-verdes-fraijanes-ref-6002-4-parqueos-estudio-3-hab-5-banos-CAC3206/", 
"https://mapainmueble.com/properties/casa-en-zona-9-para-oficinas-en-alquiler-codigo-849-DAC8081/", 
"https://mapainmueble.com/properties/alquiler-casa-colonia-el-campo-zona-14-cac3210/", 
"https://mapainmueble.com/properties/casa-en-renta-cercana-a-san-lucas-guatemala-DAC7609/", 
"https://mapainmueble.com/properties/casa-condominio-villas-de-entre-verdes-DAC7607/", 
"https://mapainmueble.com/properties/alquilo-casa-en-zona-16-vistas-de-san-isidro-cac3088/", 
"https://mapainmueble.com/properties/casa-en-renta-km-18-5-carretera-a-el-salvador-dac7606/", 
"https://mapainmueble.com/properties/alquiler-santa-anita-carretera-dac7537/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-jacarandas-de-cayala-DAC7605/", 
"https://mapainmueble.com/properties/renta-casa-la-canada-DAC7533/", 
"https://mapainmueble.com/properties/casa-en-renta-jacarandas-de-cayala-zona-16-con-4-dormitorios-dac7604/", 
"https://mapainmueble.com/properties/en-renta-casa-zona-15-vista-hermosa-2-dac7530/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-la-canada-DAC7603/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-DAC7526/", 
"https://mapainmueble.com/properties/casa-en-renta-santa-anita-ii-km-18-6-carretera-a-el-salvador-DAC7602/", 
"https://mapainmueble.com/properties/rento-casa-cond-villas-del-bosque-ref-5899-2-parqueos-4-hab-5-banos-250-mts-estudio-cuarto-servicio-CAC3085/", 
"https://mapainmueble.com/properties/alquiler-de-casa-caes-km-14-5-DAC7520/", 
"https://mapainmueble.com/properties/casa-en-renta-cayala-zona-16-DAC7601/", 
"https://mapainmueble.com/properties/rento-casa-en-zona-15-vista-hermosa-ii-dentro-de-garita-dac7519/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-15-vista-hermosa-ii-dac7599/", 
"https://mapainmueble.com/properties/renta-casa-carretera-a-el-salvador-1-400-DAC7518/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-10-mundo-inmobiliario-dac6489/", 
"https://mapainmueble.com/properties/preciosa-casa-en-renta-en-santa-catarina-pinula-dac6446/", 
"https://mapainmueble.com/properties/amplia-casa-en-alquiler-p-oficinas-1-000-mts2-bien-ubicada-en-zona-13-cac2762/", 
"https://mapainmueble.com/properties/casa-con-espacios-amplios-en-el-km-13-5-dac6442/", 
"https://mapainmueble.com/properties/casa-con-jardin-en-venta-o-alquiler-en-zona-1-por-av-elena-dac6439/", 
"https://mapainmueble.com/properties/casa-en-renta-villas-del-campo-km-13-carretera-a-el-salvador-dac6414/", 
"https://mapainmueble.com/properties/casa-tipo-apartamdnto-DAC6376/", 
"https://mapainmueble.com/properties/alquilo-cayala-propiedad-con-amplio-jardin-4-dormitorios-dac6375/", 
"https://mapainmueble.com/properties/casa-en-oakland-zona-10-dac7793/", 
"https://mapainmueble.com/properties/en-renta-casa-zona-16-la-montana-de-un-nivel-dac7150/", 
"https://mapainmueble.com/properties/casa-en-renta-condominio-broken-sound-zona-10-dac7140/", 
"https://mapainmueble.com/properties/rento-amplia-casa-en-zona-2-residencial-el-roble-dac7127/", 
"https://mapainmueble.com/properties/alquilo-casa-en-carretera-al-salvador-a-buen-precio-DAC7122/", 
"https://mapainmueble.com/properties/preciosa-casa-en-renta-km-8-5-carretera-a-santa-catarina-pinula-dac7114/", 
"https://mapainmueble.com/properties/casa-amueblada-en-renta-en-km-8-5-carretera-a-santa-catarina-pinula-dac7113/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-07-de-tres-dormitorios-y-dormitorio-de-servicio-dac7112/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-8-de-mixco-san-cristobal-dac7096/", 
"https://mapainmueble.com/properties/alquilo-casa-km-16-5-carretera-olmeca-con-amplio-jard-iacute-n-fuera-de-garita-dac7093/", 
"https://mapainmueble.com/properties/alquiler-de-casa-peque-ntilde-a-km-16-carretera-a-el-salvador-de-2-dormitorios-dac7225/", 
"https://mapainmueble.com/properties/townhouse-en-renta-zona-14-cod-cc29217-CAC2995/", 
"https://mapainmueble.com/properties/z-15-vista-hermosa-1-cerca-metro-15-cac2990/", 
"https://mapainmueble.com/properties/rento-exclusiva-casa-en-bougambilias-de-cayala-zona-16-dac7204/", 
"https://mapainmueble.com/properties/townhouse-en-alquiler-zona-10-atras-de-fontabella-cac2987/", 
"https://mapainmueble.com/properties/casa-en-renta-km-25-5-caes-res-villas-europeas-cac2986/", 
"https://mapainmueble.com/properties/casa-en-renta-estilo-colonial-en-san-rafael-i-DAC7196/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-16-cayal-aacute-de-cuatro-dormitorios-DAC7191/", 
"https://mapainmueble.com/properties/alquiler-de-casa-amueblada-santa-rosalia-km-12-5-al-salvador-cac2973/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-de-4-dormitorios-con-club-privado-DAC6262/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-dentro-de-condominio-DAC6260/", 
"https://mapainmueble.com/properties/casa-en-renta-area-cementerio-las-flores-zona-7-mixco-DAC6256/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-portal-de-san-isidro-3-DAC6254/", 
"https://mapainmueble.com/properties/amplia-casa-en-alquiler-en-zona-15-excelente-ubicacion-dac6231/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-11-miraflores-sur-DAC6222/", 
"https://mapainmueble.com/properties/alquilo-amplia-casa-amueblada-en-muxbal-DAC6219/", 
"https://mapainmueble.com/properties/casa-en-renta-dac6214/", 
"https://mapainmueble.com/properties/casa-condado-naranjo-condominio-san-daniel-DAC6213/", 
"https://mapainmueble.com/properties/casa-en-la-canada-zona-14-dac8119/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-CAC3219/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-13-elgin-2-CAC3218/", 
"https://mapainmueble.com/properties/elegante-casa-en-renta-en-z14-DAC8115/", 
"https://mapainmueble.com/properties/casa-en-renta-condominio-bakara-san-cristobal-zona-8-de-mixco-DAC8112/", 
"https://mapainmueble.com/properties/casa-amplia-en-alquiler-en-la-montana-z-16-CAC3217/", 
"https://mapainmueble.com/properties/las-dalias-z-7-calz-mateo-flores-3-dormitorios-2-etacionamientos-q6-500-mant-incluido-DAC8109/", 
"https://mapainmueble.com/properties/zona-13-elgin-ii-alquilo-casa-de-4-dormitorios-DAC8108/", 
"https://mapainmueble.com/properties/casa-de-255-m2-de-construccion-en-renta-zona-15-DAC8107/", 
"https://mapainmueble.com/properties/lujosa-casa-de-4-habs-estudio-en-alquiler-en-zona-16-dac6769/", 
"https://mapainmueble.com/properties/espectacular-casa-de-4-habs-en-alquiler-en-zona-10-dac6754/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-13-dac3105/", 
"https://mapainmueble.com/properties/casa-en-alquiler-dac6719/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-9-para-oficinas-restaurantes-etc-dac6701/", 
"https://mapainmueble.com/properties/zona-16-sector-cayala-alquilo-casa-un-nivel-dac6699/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-16-bouganvilias-de-cayal-aacute-de-cuatro-dormitorios-y-dormitorio-de-servicio-dac6686/", 
"https://mapainmueble.com/properties/santuaria-muxbal-cipreses-casa-amueblada-en-renta-dac6676/", 
"https://mapainmueble.com/properties/casa-en-la-canada-en-renta-zona-14-dac6651/", 
"https://mapainmueble.com/properties/casa-en-alquiler-villa-vermont-ii/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-santa-rosalia-la-laguna-049castd/", 
"https://mapainmueble.com/properties/alquiler-casa-amplia-con-jardn-en-condominio-zona-10-2/", 
"https://mapainmueble.com/properties/casa-en-renta-san-gaspar-1-zona-16/", 
"https://mapainmueble.com/properties/town-house-zona-10-alquiler/", 
"https://mapainmueble.com/properties/casa-en-alquiler-kanajuy-zona-16/", 
"https://mapainmueble.com/properties/casa-en-alquiler-con-piscina-en-santa-catarina-pinula/", 
"https://mapainmueble.com/properties/casa-en-renta-en-bosque-escondido-fraijanes/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-condominio-km-8-carretera-el-salvador-044cacd/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-12-DAC8037/", 
"https://mapainmueble.com/properties/casa-en-vista-hermosa-ii-zona-15-DAC8034/", 
"https://mapainmueble.com/properties/se-alquila-casa-ideal-para-oficinas-o-vivienda-en-zona-7-DAC8022/", 
"https://mapainmueble.com/properties/casa-en-renta-la-canada-zona-14-DAC8019/", 
"https://mapainmueble.com/properties/casa-en-renta-la-canada-zona-14-DAC8018/", 
"https://mapainmueble.com/properties/rento-casa-de-1-nivel-para-oficinas-zona-10-sector-ciudad-vieja-cerca-del-mac-de-diagonal-6-DAC8015/", 
"https://mapainmueble.com/properties/casa-en-colonia-miraflores-zona-11-dentro-de-garita-dac8012/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-en-alquiler-zona-16-DAC8011/", 
"https://mapainmueble.com/properties/linda-casa-de-un-nivel-en-renta-dac8010/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-13-elgin-ii-DAC8153/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-10-para-vivienda-u-oficina-DAC8152/", 
"https://mapainmueble.com/properties/casa-en-renta-en-avenida-simeon-canas-dac8151/", 
"https://mapainmueble.com/properties/hermosa-casa-en-alquiler-zona-14-la-canada-DAC8150/", 
"https://mapainmueble.com/properties/amplia-casa-con-4-dormitorios-en-alquiler-zona-9-mixco-labor-de-castilla-2-DAC8149/", 
"https://mapainmueble.com/properties/casa-amueblada-en-renta-zona-11-codig-cc30034a-CAC3234/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-11-codigo-cc30034-CAC3233/", 
"https://mapainmueble.com/properties/casa-amueblada-en-renta-zona-11-codig-cc30033a-CAC3232/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-11-codig-cc30033-CAC3231/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-olmos-de-cayala-de-4-habitaciones-dac5762/", 
"https://mapainmueble.com/properties/hermosa-casa-en-renta-4-hab-y-espectacular-jardin-dac5704/", 
"https://mapainmueble.com/properties/alquilo-casas-en-villa-del-campo-carretera-a-el-salvador-dac5585/", 
"https://mapainmueble.com/properties/alquilo-casa-comercial-en-zona-15-ciudad-dac5542/", 
"https://mapainmueble.com/properties/casa-en-renta-dac5503/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-10-dac6558/", 
"https://mapainmueble.com/properties/rento-casa-san-rafael-1-km-9-carr-salvador-ces-dac5427/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-13-elgin-DAC6554/", 
"https://mapainmueble.com/properties/tradicional-con-finos-detalles/", 
"https://mapainmueble.com/properties/renta-casa-en-bougambilias-de-cayala-dac6542/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-4-para-oficinas-o-vivienda-dac5378/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-10-dac6534/", 
"https://mapainmueble.com/properties/alquilo-casa-en-zona-2-simeon-canas-dac5349/", 
"https://mapainmueble.com/properties/amplia-casa-para-oficinas-en-renta-zona-10-dac6532/", 
"https://mapainmueble.com/properties/casa-para-remodelar-en-zona-16-dac6521/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-15-vhiii-dentro-de-garita-DAC6517/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-13-elgin-ii-dac6511/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-4-de-mixco-colonia-monte-verde-cac2779/", 
"https://mapainmueble.com/properties/casa-en-renta-km-13-carretera-a-el-salvador-DAC8175/", 
"https://mapainmueble.com/properties/casa-3-dormitorios-en-alquiler-zona-16-ensenadas-de-san-isidro-DAC8174/", 
"https://mapainmueble.com/properties/casa-comercial-en-renta-en-zona-9-sobre-avenida-principal-dac8172/", 
"https://mapainmueble.com/properties/casa-en-alquiler-dentro-de-garita-de-3-dormitorios-zona-10-DAC8173/", 
"https://mapainmueble.com/properties/casa-en-alquiler-con-amplio-jardin-san-cristobal-zona-8-de-mixco-DAC8171/", 
"https://mapainmueble.com/properties/casa-en-renta-san-cristobal-zona-8-de-mixco-DAC8169/", 
"https://mapainmueble.com/properties/casa-en-renta-en-colonia-oakland-zona-10-dac8168/", 
"https://mapainmueble.com/properties/casa-en-renta-en-terravista-carretera-a-el-salvador-DAC8167/", 
"https://mapainmueble.com/properties/casa-en-renta-el-lomas-del-rodeo-zona-3-DAC7931/", 
"https://mapainmueble.com/properties/alquiler-de-casa-en-zona-12-dentro-de-garita-DAC8166/", 
"https://mapainmueble.com/properties/casa-en-renta-en-col-lomas-del-rodeo-zona-3-de-mixco-DAC7929/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-06-de-villa-nueva-en-condado-catalina-DAC7928/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-13-de-tres-dormitorios-y-dormitorio-de-servicio-dac3936/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-15-vhi-cod-cc29851-cac3184/", 
"https://mapainmueble.com/properties/renta-de-casa-en-encinos-4/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-en-renta-cumbres-de-la-arboleda-DAC7922/", 
"https://mapainmueble.com/properties/casa-en-renta-santa-clara-km-18-5-DAC7915/", 
"https://mapainmueble.com/properties/casa-en-condominio-el-jardin-de-san-lazaro-dac7821/", 
"https://mapainmueble.com/properties/rento-chalet-amueblado-amatitlan-ref-5771b-4-hab-3-banos-990m2-6-parqueos-CAC3178/", 
"https://mapainmueble.com/properties/casa-en-renta-lazos-de-fraijanes-lindo-condominio-y-casa-DAC7820/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condominio-zona-10-DAC7818/", 
"https://mapainmueble.com/properties/casa-en-alquiler-encinos-de-cayala-zona-16-DAC7816/", 
"https://mapainmueble.com/properties/casa-en-jacarandas-de-cayala-zona-16-dac7813/", 
"https://mapainmueble.com/properties/casa-en-renta-san-lazaro-zona-15-dac7794/", 
"https://mapainmueble.com/properties/alquiler-de-casa-alamedas-de-santa-rita-DAC7791/", 
"https://mapainmueble.com/properties/casa-en-renta-tipo-townhouse-con-finos-acabados-en-zona-10-ref-2362-DAC7787/", 
"https://mapainmueble.com/properties/renta-de-townhouse-en-zona-15-sector-san-lazaro-dac7786/", 
"https://mapainmueble.com/properties/casa-con-piscina-en-jardines-de-san-isidro-cac3110/", 
"https://mapainmueble.com/properties/rento-preciosa-casa-en-un-entorno-natural-muy-cerca-de-zona-10-en-el-prado-a-pasos-del-nuevo-paso-a-desnivel-en-20-calle-final-dac7596/", 
"https://mapainmueble.com/properties/villa-magnonolia-en-renta-DAC4313/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-dentro-de-condominio-CAC3107/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condominio-villas-de-entreverdes-fraijanes-caes-DAC7591/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-14-residenciales-el-campo-cac3104/", 
"https://mapainmueble.com/properties/alquiler-de-casa-en-zona-16-bouganvilias-de-cayala-dac7588/", 
"https://mapainmueble.com/properties/alquiler-de-apartamento-tipo-townhouse-en-zona-15-dac7586/", 
"https://mapainmueble.com/properties/alquilo-o-vendo-casa-en-utatlan-z-11-vivienda-u-oficinas-cac3117/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-en-renta-zona-15-DAC7724/", 
"https://mapainmueble.com/properties/casa-en-alquiler-resienciales-santa-monica-km-16-5-carretera-a-el-salvador-calle-de-olmeca-fraijanes-ciudad-de-guatemala-cac3139/", 
"https://mapainmueble.com/properties/casa-de-un-nivel-en-alquiler-residencial-jacarandas-de-cayala-zona-16-CAC3132/", 
"https://mapainmueble.com/properties/casa-grande-en-renta-zona-16-canadas-de-san-isidro-dac7711/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-bouganvilias-de-cayala-dac7710/", 
"https://mapainmueble.com/properties/casa-en-renta-entrada-a-fraijanes-km-21-ces-DAC7709/", 
"https://mapainmueble.com/properties/alquiler-de-casa-en-san-cristobal-dac7705/", 
"https://mapainmueble.com/properties/casa-en-zona-16-dac7704/", 
"https://mapainmueble.com/properties/se-renta-casa-en-zona-16-DAC7703/", 
"https://mapainmueble.com/properties/casa-para-oficina-negocio-area-centro-medico-dac7274/", 
"https://mapainmueble.com/properties/zona-10-sobre-20-calle-alquilo-propiedad-de-2400-varas-dac7256/", 
"https://mapainmueble.com/properties/rento-casa-z-12-fuera-garita-ref-5838-3-hab-2-bano-1-parqueo-CAC3003/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-dac7237/", 
"https://mapainmueble.com/properties/casa-en-zona-16-en-alquiler-dac7209/", 
"https://mapainmueble.com/properties/vendo-o-rento-una-propiedad-muy-exclusiva-en-foresta-cayala-con-piscina-al-frente-de-nueva-embajada-americana-dac7234/", 
"https://mapainmueble.com/properties/casa-en-renta-vistas-de-san-isidro-zona-16-dac7876/", 
"https://mapainmueble.com/properties/alquiler-de-casa-peque-ntilde-a-km-16-carretera-a-el-salvador-de-2-dormitorios-dac7225/", 
"https://mapainmueble.com/properties/townhouse-en-renta-zona-14-cod-cc29217-CAC2995/", 
"https://mapainmueble.com/properties/en-renta-casa-bosques-de-vila-verde/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-5/", 
"https://mapainmueble.com/properties/renta-de-casa-en-zona-16-mundo-inmobiliario-2/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condominio-darue-zona-14/", 
"https://mapainmueble.com/properties/alquilo-casa-en-ces-pet-friendly/", 
"https://mapainmueble.com/properties/citymax-renta-casa-en-condominio-el-prado-z-10/", 
"https://mapainmueble.com/properties/casa-en-renta-de-3-dormitorios-en-zona-15-2/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-km-18-5-DAC7427/", 
"https://mapainmueble.com/properties/casa-en-cond-las-luces-carretera-el-salvador/", 
"https://mapainmueble.com/properties/casa-en-renta-en-km-18-5-caes-DAC7426/", 
"https://mapainmueble.com/properties/casa-en-zona-13-elgin-2/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-lomas-de-san-isidro-DAC7420/", 
"https://mapainmueble.com/properties/casa-en-renta-con-jardin-varios-accesos-ces-km13-dac7405/", 
"https://mapainmueble.com/properties/alquilo-casa-villa-nueva-dentro-de-condominio-de-cuatro-dormitorios-dac7402/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-11-las-charcas-dentro-de-residencial-de-muy-pocas-casas-completamente-amoblada-cac3040/", 
"https://mapainmueble.com/properties/alquilo-casa-carretera-a-el-salvador-cumbres-de-la-arboleda-DAC7382/", 
"https://mapainmueble.com/properties/alquilo-casa-en-canadas-de-san-isidro-z-16-dac7381/", 
"https://mapainmueble.com/properties/rento-casa-z-11-ref-5872-250-mts2-3-parqueos-3-hab-3-5-banos-CAC3036/", 
"https://mapainmueble.com/properties/renta-de-casa-en-condominio-las-delicias-dac5272/", 
"https://mapainmueble.com/properties/zona-14-alquilo-casa-en-condominio-la-villa-cac3201/", 
"https://mapainmueble.com/properties/casa-remodelada-en-zona-14-dac5169/", 
"https://mapainmueble.com/properties/rentamos-casa-ideal-para-restaurante-u-oficinas-dac5153/", 
"https://mapainmueble.com/properties/alquilo-casa-carretera-a-el-salvador-km-13-5-bosques-de-las-luces-con-finos-acabados-dac5135/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-13-dac5115/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-10-oakland-remodelada-de-un-nivel-dac5027/", 
"https://mapainmueble.com/properties/alquilo-cassa-zona-16-villas-de-cantabria-de-tres-dormitorios-y-dormitorio-de-servicio-dac5007/", 
"https://mapainmueble.com/properties/casa-en-alquiler-residencial-la-montana-dac4988/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-10-de-mixco-san-jacinto-CAC2910/", 
"https://mapainmueble.com/properties/casa-en-renta-carretera-salvador-km-12-7-dac6968/", 
"https://mapainmueble.com/properties/casa-para-oficina-o-clinica-en-zona-10-dac6959/", 
"https://mapainmueble.com/properties/casa-en-condominio-magandi-muxbal-dac4993/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-10-dac6944/", 
"https://mapainmueble.com/properties/se-renta-casa-en-vh2-zona-15-dac6943/", 
"https://mapainmueble.com/properties/linda-casa-en-renta-sector-a-3-san-cristobal-DAC6934/", 
"https://mapainmueble.com/properties/casa-en-renta-acantos-de-cayala-zona-16-dac6929/", 
"https://mapainmueble.com/properties/casa-u-oficina-en-zona-10-por-novex-dac6928/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-10-cerca-de-oakland-de-tres-dormitorios-estudio-y-sala-familiar-dac7082/", 
"https://mapainmueble.com/properties/casa-en-el-encinal-mixco-dac7072/", 
"https://mapainmueble.com/properties/z16-casa-en-renta-con-bonito-jardin-dac7046/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-montesano-cac2939/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-montesano-cac2938/", 
"https://mapainmueble.com/properties/alquiler-casa-ideal-para-comercio-u-oficinas-zona-10-dac7040/", 
"https://mapainmueble.com/properties/casa-en-renta-puerta-grande-km-14-ces-dac7039/", 
"https://mapainmueble.com/properties/casa-en-elgin-ii-zona-13-dac7010/", 
"https://mapainmueble.com/properties/z-7-mateo-flores-calle-cac3164/", 
"https://mapainmueble.com/properties/alquiler-de-casa-zona-14-la-villa-DAC7517/", 
"https://mapainmueble.com/properties/linda-casa-en-santa-monica-vi-carr-a-el-salvador-DAC7515/", 
"https://mapainmueble.com/properties/alquiler-de-casa-en-muxbal-santa-catarina-pinula-DAC7512/", 
"https://mapainmueble.com/properties/casa-un-nivel-dentro-de-garita-zona-14-dac7510/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-en-renta-zona-15-dac7508/", 
"https://mapainmueble.com/properties/alquilo-casa-en-carretera-a-el-salvador-km-13-DAC7624/", 
"https://mapainmueble.com/properties/casa-grande-en-zona-1-venta-o-renta-ubicacion-comercial-DAC7507/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condominio-de-san-lazaro-zona-15-remodelada-banos-y-cocina-DAC7623/", 
"https://mapainmueble.com/properties/casa-de-un-nivel-cayala-zona-16-dac7503/", 
"https://mapainmueble.com/properties/casa-alquiler-zona-15-DAC7622/", 
"https://mapainmueble.com/properties/se-renta-casa-en-carretera-a-el-salvador-km-13-5-DAC7499/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-15-dentro-de-garita-DAC7621/", 
"https://mapainmueble.com/properties/alquiler-de-amplia-casa-en-zona-1-DAC7495/", 
"https://mapainmueble.com/properties/casa-en-la-canada-dentro-de-condominio-zona-14-dac7620/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-15-vista-hermosa-uno-CAC3114/", 
"https://mapainmueble.com/properties/casa-en-renta-en-canadas-de-elgin-zona-13-dac7616/", 
"https://mapainmueble.com/properties/se-renta-casa-en-broken-sound-zona-10-DAC7612/", 
"https://mapainmueble.com/properties/casa-en-renta-en-santa-elena-barillas-DAC7610/", 
"https://mapainmueble.com/properties/casa-en-renta-la-canada-zona-14-dac6843/", 
"https://mapainmueble.com/properties/en-renta-casa-zona-15-vista-hermosa-ii-cac2862/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-kanajuyu-con-3-habitaciones-dac6820/", 
"https://mapainmueble.com/properties/casa-en-renta-encinos-de-cayala-zona-16-cac2858/", 
"https://mapainmueble.com/properties/casa-en-renta-encinos-de-cayala-zona-16-dac6814/", 
"https://mapainmueble.com/properties/bella-casa-en-alquiler-en-zona-10-dac6812/", 
"https://mapainmueble.com/properties/casa-en-renta-carretera-a-el-salvador-cod-cc28824-CAC2852/", 
"https://mapainmueble.com/properties/casa-en-zona-14-dac6789/", 
"https://mapainmueble.com/properties/amplia-casa-con-gran-jardin-de-4-habs-en-venta-en-zona-12-dac6782/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-cayala-de-4-dormitorios-dac6926/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-10-oakland-de-4-habitaciones-dac6923/", 
"https://mapainmueble.com/properties/en-renta-casa-zona-15-vh-2-dac6921/", 
"https://mapainmueble.com/properties/linda-casa-amueblada-equipada-en-alquiler-zona-15-vista-hermosa-dac6906/", 
"https://mapainmueble.com/properties/casa-en-alquiler-con-espacios-amplios-para-oficina-o-vivienda-z10-dac6898/", 
"https://mapainmueble.com/properties/casa-para-negocios-u-oficinas-en-alquiler-z-10-35-parqueos-cac2884/", 
"https://mapainmueble.com/properties/casa-amoblada-y-equipada-en-renta-en-pinos-de-muxbal-km-13-5-mundo-inmobiliario-dac6872/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-13-DAC6866/", 
"https://mapainmueble.com/properties/casa-en-renta-en-villas-de-la-meseta-mundo-inmobiliario-dac6847/", 
"https://mapainmueble.com/properties/casa-grande-en-residencial-en-renta-zona-2-CAC2810/", 
"https://mapainmueble.com/properties/casa-en-la-montana-zona-16-dac6626/", 
"https://mapainmueble.com/properties/linda-casa-en-zona-14-en-alquiler-dac6607/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-condominio-con-4-dormitorios-y-bonita-casa-club-dac6587/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-14-la-villa-no-garita-dac6586/", 
"https://mapainmueble.com/properties/casa-en-las-conchas-zona-14-cac2795/", 
"https://mapainmueble.com/properties/alquilo-casa-carretera-a-el-salvador-km-30-DAC6562/", 
"https://mapainmueble.com/properties/alquiler-casa-zn-16-DAC6561/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-1-mundo-inmobiliario-DAC6559/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-15-ideal-para-oficina/", 
"https://mapainmueble.com/properties/casa-de-250-m2-de-construccin-en-renta-zona-10-3/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-4/", 
"https://mapainmueble.com/properties/casa-en-renta-ces-km-13/", 
"https://mapainmueble.com/properties/town-house-en-renta-zona-15-vh-i/", 
"https://mapainmueble.com/properties/alquilo-casa-en-san-jorge-muxbal/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-la-zona-16-dentro-de-condominio/", 
"https://mapainmueble.com/properties/rento-casa-en-zona-11/", 
"https://mapainmueble.com/properties/rento-casa-ubicada-en-zona-4-de-mixco/", 
"https://mapainmueble.com/properties/z-16-cayala-dac7892/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-santa-rosalia-la-laguna-dac7883/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-1-con-parqueo-aledano-cac3169/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-12-DAC7880/", 
"https://mapainmueble.com/properties/linda-casa-con-jardin-en-alquiler-en-vista-hermosa-2-fuera-de-garita-DAC7879/", 
"https://mapainmueble.com/properties/casa-para-estrenar-dalias-residencias-concepcion-dac7878/", 
"https://mapainmueble.com/properties/amplia-casa-para-oficinas-en-alquiler-los-proceres-zona-10-DAC7872/", 
"https://mapainmueble.com/properties/rento-casa-km-18-5-entrada-a-fraijanes-cod-dc29798-DAC7871/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-10-de-3-dormitorios-en-3-000-codigo-1681-DAC7868/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-dentro-de-residencial-privado-cac3033/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-alamedas-de-san-isidro-DAC7357/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-alamedas-de-san-isidro-dac7356/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-16-sobre-boulevard-la-monta-ntilde-a-pot-g5-DAC7340/", 
"https://mapainmueble.com/properties/casas-en-remodelacion-en-renta-la-canada-zona-14-dac7327/", 
"https://mapainmueble.com/properties/casa-en-renta-estilo-colonial-en-san-rafael-i-mundo-inmobiliario-DAC7339/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-sobre-boulevard-acatan-san-isidro-cuatro-habitaciones-DAC7333/", 
"https://mapainmueble.com/properties/alquiler-de-casa-en-renta-zona-15-vista-hermosa-con-4-habitaciones-con-bano-DAC7313/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-bosques-de-las-luces-dac7289/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-en-renta-en-km-24-2-caes-DAC8068/", 
"https://mapainmueble.com/properties/rento-casa-amueblada-km-12-5-ces-jardines-de-santa-rosalia-ref-5999-estudio-sala-familiar-3-hab-6-parqueos-5-banos-CAC3203/", 
"https://mapainmueble.com/properties/casa-en-encinos-de-muxbal-dac8065/", 
"https://mapainmueble.com/properties/en-alquiler-casa-comercial-sobre-blvd-los-proceres-zona-10-DAC8061/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condominio-carr-a-fraijanes-dac8058/", 
"https://mapainmueble.com/properties/alquilo-casa-carretera-a-santa-catarina-pinula-km-18-5-ideal-para-colegio-DAC8057/", 
"https://mapainmueble.com/properties/casa-en-via-siete-zona-10-dac8056/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-arrazola-iii-km-17-ces-en-directo-DAC8053/", 
"https://mapainmueble.com/properties/se-renta-casa-grande-en-zona-14-DAC8051/", 
"https://mapainmueble.com/properties/casa-remodelada-montebello-2-4-habitaciones-2300-dac8075/", 
"https://mapainmueble.com/properties/rento-casa-amueblada-en-zona-15-dac6683/", 
"https://mapainmueble.com/properties/renta-citymax-casa-zona-15-vista-hermosa-iii/", 
"https://mapainmueble.com/properties/citymax-alquila-amplia-casa-puerta-grande-km-14-de-ces/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-13-dentro-de-condominio/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-avenida-mariscal-dentro-de-garita-de-tres-dormitorios/", 
"https://mapainmueble.com/properties/casa-en-renta-z15-vh3/", 
"https://mapainmueble.com/properties/casa-en-venta-san-miguel-buenavista-zona-10/", 
"https://mapainmueble.com/properties/alquilo-casa-km-14-5-carretera-a-el-salvador-en-residencias-concepcin/", 
"https://mapainmueble.com/properties/casa-un-nivel-en-zona-14-cerca-a-20-calle-dac7674/", 
"https://mapainmueble.com/properties/casa-fuera-de-condominio-de-420-m2-de-construccion-en-renta-zona-17-DAC7673/", 
"https://mapainmueble.com/properties/casa-de-300-m2-de-construccion-en-renta-zona-10-DAC7672/", 
"https://mapainmueble.com/properties/ofibodega-en-zona-4-de-mixco-DAC7668/", 
"https://mapainmueble.com/properties/casa-en-alquiler-encinos-de-cayala-zona-16-dac7666/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-5-DAC7662/", 
"https://mapainmueble.com/properties/casa-en-condominio-de-255-m2-de-construccion-en-renta-muxbal-DAC7660/", 
"https://mapainmueble.com/properties/casa-nueva-en-renta-kanajuyu-z16-DAC7653/", 
"https://mapainmueble.com/properties/casa-alamedas-de-santo-domingo-km-30-dac7651/", 
"https://mapainmueble.com/properties/casa-en-alquiler-lomas-de-san-isidro-zona-16-DAC6108/", 
"https://mapainmueble.com/properties/casa-en-renta-carretera-al-salvador-DAC6090/", 
"https://mapainmueble.com/properties/renta-de-casa-en-muxbal-cod-dc27000-cac2683/", 
"https://mapainmueble.com/properties/vendo-casa-residencial-en-zona-2-de-villa-nueva-con-doble-garita-de-seguridad-dac6201/", 
"https://mapainmueble.com/properties/casa-en-renta-km-10-carretera-a-el-salvador-dac6086/", 
"https://mapainmueble.com/properties/z-16-acantos-de-cayala-preciosa-dac6179/", 
"https://mapainmueble.com/properties/casa-en-villas-pomona-zona-10-DAC6022/", 
"https://mapainmueble.com/properties/casa-en-lazos-de-fraijanes-CAC2668/", 
"https://mapainmueble.com/properties/casa-fuera-de-garita-zona-10-dac6021/", 
"https://mapainmueble.com/properties/casa-zona-15-vista-hermosa-ii-dac6161/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-13-avenida-hincapie-ideal-para-vivienda-oficinas-o-negocios-dac6020/", 
"https://mapainmueble.com/properties/alquilo-townhouse-col-el-campo-zona-14-dac6143/", 
"https://mapainmueble.com/properties/casa-en-renta-elgin-2-zona-13-dac6002/", 
"https://mapainmueble.com/properties/lujosa-casa-en-renta-en-santa-catarina-pinula-dac6133/", 
"https://mapainmueble.com/properties/casa-en-alquiler-ubicada-en-el-km-12-7-de-ces-dac5976/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-10-dac6122/", 
"https://mapainmueble.com/properties/casa-en-alquiler-ideal-para-oficinas-ubicada-en-zona-13-cac2587/", 
"https://mapainmueble.com/properties/casa-en-renta-de-03-dormitorios-en-zona-15-DAC6121/", 
"https://mapainmueble.com/properties/casa-zona-11-condominio-villas-de-las-charcas-DAC8048/", 
"https://mapainmueble.com/properties/casa-de-3-dormitorios-en-renta-condominio-los-cedros-zona-14-la-villa-DAC8047/", 
"https://mapainmueble.com/properties/portal-del-bosque-DAC7911/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-12-dac8046/", 
"https://mapainmueble.com/properties/rento-casa-en-residenciales-el-roble-zona-11-las-charcas-DAC7910/", 
"https://mapainmueble.com/properties/rento-casa-z-13-canadas-de-elgin-ref-5993-224m2-3-parqueos-sala-fam-cuarto-servicio-3-hab-4-banos-CAC3199/", 
"https://mapainmueble.com/properties/se-renta-casa-en-condominio-zona-10-guatemala-DAC7909/", 
"https://mapainmueble.com/properties/townhouse-en-venta-z-14-terraza-panales-solares-dac8079/", 
"https://mapainmueble.com/properties/alquiler-de-casa-zona-10-suelo-comercial-DAC8045/", 
"https://mapainmueble.com/properties/alquiler-de-casa-en-el-naranjo-DAC7903/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-16-la-montana-mundo-inmobiliario-DAC8041/", 
"https://mapainmueble.com/properties/casa-oficina-renta-zona-13-DAC7896/", 
"https://mapainmueble.com/properties/alquiler-casa-colonia-el-campo-zona-14-cac3197/", 
"https://mapainmueble.com/properties/jacarandas-de-cayala-DAC7901/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-condominio-de-muxbal-DAC8040/", 
"https://mapainmueble.com/properties/casa-tipo-townhouse-de-200-m2-de-construccion-en-renta-zona-15-dac7902/", 
"https://mapainmueble.com/properties/alquilo-casa-santa-catarina-pinula-scp01-r-237-DAC7895/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-10-1001-pa-r-234-CAC3172/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-condominio-en-santa-rosalia-la-laguna-047castd/", 
"https://mapainmueble.com/properties/casa-en-renta-km-9-carretera-sta-catarina-pinula-lotificacion-la-cruz/", 
"https://mapainmueble.com/properties/casa-premium-en-zona-14/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-carretera-a-el-salvador/", 
"https://mapainmueble.com/properties/casa-en-condominio-san-francisco-de-126m2-z-14-la-villa/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-en-renta-condominio-exclusivo-zona-14/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-14-4/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-14-3/", 
"https://mapainmueble.com/properties/alquilo-townhouse-zona-13-elgin-ii-de-tres-dormitorios/", 
"https://mapainmueble.com/properties/casa-en-zona-13-dac7848/", 
"https://mapainmueble.com/properties/hermosa-casa-en-renta-en-las-luces-ces-km-13-5-dac7846/", 
"https://mapainmueble.com/properties/casa-para-negocio-en-renta-en-zona-13-dac7844/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-10-en-directo-DAC2658/", 
"https://mapainmueble.com/properties/casa-en-renta-carretera-a-fraijanes-CAC3160/", 
"https://mapainmueble.com/properties/casa-en-venta-km-17-carretera-a-san-jose-pinula-ciudad-de-guatemala-dac7841/", 
"https://mapainmueble.com/properties/casa-en-renta-en-oakland-zona-10-DAC7839/", 
"https://mapainmueble.com/properties/rento-casa-en-boulevard-los-proceres-zona-10-fuera-de-garita-DAC7828/", 
"https://mapainmueble.com/properties/casa-en-renta-villas-magnolia-zona-7-mixco-cac3157/", 
"https://mapainmueble.com/properties/alquilo-casa-carretera-san-jos-eacute-pinula-hacienda-las-mercedes-DAC7979/", 
"https://mapainmueble.com/properties/casa-en-alquiler-carretera-al-salvador-cruce-san-jose-pinula-DAC7978/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-buganvilias-de-cayala-dac7976/", 
"https://mapainmueble.com/properties/casa-en-alquiler-encinos-de-cayala-zona-16-dac7974/", 
"https://mapainmueble.com/properties/casa-en-alquiler-jacarandas-de-cayala-zona-16-DAC7973/", 
"https://mapainmueble.com/properties/casa-en-alquiler-nova-cayala-zona-16-dac7972/", 
"https://mapainmueble.com/properties/alquilo-casa-en-zona-14-sector-la-villa-balcon-lindos-acabados-cac3189/", 
"https://mapainmueble.com/properties/renta-de-casa-en-zona-16-kanajuyu-DAC7970/", 
"https://mapainmueble.com/properties/casa-en-alquiler-condominio-zona-10-guatemala-DAC7968/", 
"https://mapainmueble.com/properties/rento-muxbal-1-nivel-incluye-apartamento/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-2/", 
"https://mapainmueble.com/properties/casa-en-renta-carretera-a-el-salvador-km-12-5/", 
"https://mapainmueble.com/properties/lujosa-casa-en-alquiler-en-elgin-zona-13/", 
"https://mapainmueble.com/properties/casa-en-renta-en-eucaliptos-mundo-inmobiliario/", 
"https://mapainmueble.com/properties/casa-en-renta-para-oficinas-o-clnicas/", 
"https://mapainmueble.com/properties/casa-en-alquiler-3/", 
"https://mapainmueble.com/properties/alquiler-villas-de-entreverdes/", 
"https://mapainmueble.com/properties/casa-en-zona-10-9/", 
"https://mapainmueble.com/properties/casa-en-renta-villas-del-bosque-carretera-el-salvador-DAC7494/", 
"https://mapainmueble.com/properties/vendo-o-rento-espaciosa-casa-balcones-3-san-cristobal-DAC7492/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-9-excelente-ubicacion-cac3081/", 
"https://mapainmueble.com/properties/residencia-en-alquiler-en-condominio-de-muxbal-dac7490/", 
"https://mapainmueble.com/properties/casa-en-alquiler-de-un-nivel-en-santa-rosalia-la-laguna-058castc-CAC3079/", 
"https://mapainmueble.com/properties/townhouse-san-lazaro-zona-15-dac7484/", 
"https://mapainmueble.com/properties/san-lazaro-zona-15-cac3077/", 
"https://mapainmueble.com/properties/casa-en-renta-encinos-de-cayala-zona-16-DAC7483/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-cayala-DAC7482/", 
"https://mapainmueble.com/properties/casa-en-nova-cayala-zona-16-dac7635/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-carretera-a-el-salvador-de-4-dormitorios-de-900-mts-codigo-1393-DAC7633/", 
"https://mapainmueble.com/properties/townhouse-en-alquiler-zona-15-san-lazaro-cac3115/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-10-dac7628/", 
"https://mapainmueble.com/properties/townhouse-de-2-niveles-en-renta-en-zona-15-dac7627/", 
"https://mapainmueble.com/properties/rento-casa-para-estrenar-en-san-jose-pinula-DAC7626/", 
"https://mapainmueble.com/properties/rento-casa-en-zona-16-a-5-minutos-de-cayala-DAC7625/", 
"https://mapainmueble.com/properties/alquilo-casa-en-carretera-a-el-salvador-km-13-DAC7624/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condominio-de-san-lazaro-zona-15-remodelada-banos-y-cocina-DAC7623/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-10-oakland-cac3102/", 
"https://mapainmueble.com/properties/hermosa-casa-en-renta-santa-elena-barillas-dac7581/", 
"https://mapainmueble.com/properties/townhouse-san-lazaro-zona-15-DAC7580/", 
"https://mapainmueble.com/properties/alquiler-casa-en-complejo-providencia-km18-5-carretera-a-san-jose-pinula-DAC7578/", 
"https://mapainmueble.com/properties/alquiler-casa-en-condominio-la-escalada-zona-15-DAC7577/", 
"https://mapainmueble.com/properties/casa-en-alquiler-km-12-carretera-a-el-salvador-santa-rosalia-cac3100/", 
"https://mapainmueble.com/properties/propiedad-grande-en-renta-ideal-spa-dentro-de-garita-del-km-21-5-fraijanes-DAC7576/", 
"https://mapainmueble.com/properties/casa-en-alquiler-z-16-4-dormitorios-con-bano-c-uno-dac7574/", 
"https://mapainmueble.com/properties/altos-del-encinal-en-renta-DAC7571/", 
"https://mapainmueble.com/properties/alquiler-casa-zona-9-cac3128/", 
"https://mapainmueble.com/properties/casa-en-carretera-al-salvador-dac7714/", 
"https://mapainmueble.com/properties/casa-en-condominio-el-prado-dac7686/", 
"https://mapainmueble.com/properties/casa-de-225-92-m2-de-construccion-en-renta-mixco-DAC7685/", 
"https://mapainmueble.com/properties/casa-para-oficina-en-zona-10-DAC7684/", 
"https://mapainmueble.com/properties/casa-en-renta-muxbal-cod-dc29597-DAC7683/", 
"https://mapainmueble.com/properties/casa-de-1-nivel-el-prado-dac7682/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-15-vista-hermosa-i-en-directo-DAC7681/", 
"https://mapainmueble.com/properties/casa-la-montana-dac7677/", 
"https://mapainmueble.com/properties/linda-casa-en-renta-con-jardin-3-hab-y-estudio-z15-dac7761/", 
"https://mapainmueble.com/properties/hermosa-casa-en-renta-4-hab-estudio-y-sala-fam-lindo-jardin-z16-dac7759/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-la-montana-zona-16-en-directo-DAC7758/", 
"https://mapainmueble.com/properties/casa-en-renta-en-la-canada-zona-14-dac7757/", 
"https://mapainmueble.com/properties/casa-para-remodelar-zona-14-dac7756/", 
"https://mapainmueble.com/properties/casa-en-20-calle-para-uso-comercial-sobre-via-principal-en-zona-10-dac7755/", 
"https://mapainmueble.com/properties/alquilo-casa-fraijanes-villa-capelo-de-cuatro-dormitorios-dac7754/", 
"https://mapainmueble.com/properties/alquiler-casa-el-jardin-de-san-lazaro-sta-catarina-pinula-dac7753/", 
"https://mapainmueble.com/properties/casa-en-renta-o-venta-el-socorro-dac7745/", 
"https://mapainmueble.com/properties/casa-en-condominio-villas-del-campo-DAC7478/", 
"https://mapainmueble.com/properties/linda-casa-en-alquiler-en-san-lazaro-z-15-cac3075/", 
"https://mapainmueble.com/properties/casa-en-renta-en-santa-anita-ii-carreterra-a-el-salvador-dac7475/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-el-campo-DAC7472/", 
"https://mapainmueble.com/properties/casa-en-renta-san-lazaro-zona-15-dac7471/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-cerca-de-sporta-km-17-5-DAC7470/", 
"https://mapainmueble.com/properties/casa-comercial-zona-14-dac7461/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-14-dentro-de-garita-de-1-nivel-CAC3068/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-sala-familiar-estudio-en-condado-naranjo-q7-200-00-cac3065/", 
"https://mapainmueble.com/properties/zona-14-cerca-de-la-canada-casa-de-1-nivel-dentro-de-condominio-dac7550/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-km-18-5-DAC7548/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-1-DAC7534/", 
"https://mapainmueble.com/properties/casa-en-renta-en-jardines-de-providencia-carretera-a-san-jose-pinula-dac7547/", 
"https://mapainmueble.com/properties/casa-remodelada-a-pocos-minutos-de-cayala-dac7545/", 
"https://mapainmueble.com/properties/residencia-en-alquiler-en-condominio-de-muxbal-DAC7544/", 
"https://mapainmueble.com/properties/casa-en-renta-en-san-lazaro-zona-15-dac7542/", 
"https://mapainmueble.com/properties/rento-casa-amueblada-dentro-de-condominio-en-zona-11-ref-2295-CAC3091/", 
"https://mapainmueble.com/properties/casa-para-oficinas-zona-10-DAC7538/", 
"https://mapainmueble.com/properties/casa-en-renta-para-oficinas-o-clinicas-en-zona-10-DAC7997/", 
"https://mapainmueble.com/properties/casa-en-renta-en-colonia-oakland-zona-10-DAC7994/", 
"https://mapainmueble.com/properties/casa-residencial-en-renta-en-san-cristobal-sector-b-4-DAC7993/", 
"https://mapainmueble.com/properties/casa-en-renta-en-col-lomas-del-rodeo-zona-3-de-mixco-DAC7992/", 
"https://mapainmueble.com/properties/casa-en-renta-de-5-habitaciones-en-country-club-z11-DAC7991/", 
"https://mapainmueble.com/properties/casa-en-renta-de-3-niveles-en-oakland-zona-10-ref-2394-DAC7985/", 
"https://mapainmueble.com/properties/santa-rosalia-DAC7984/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-condominio-en-el-km-14-excelente-ubicacionsector-plaza-san-sebastian-046cacd-DAC7983/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condado-naranjo-DAC7980/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-14-de-4-dormitorios-en-3-200-codigo-1676-DAC7867/", 
"https://mapainmueble.com/properties/rento-casa-grande-en-zona-10-DAC7863/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-14-de-5-dormitorios-y-estudio-dac7862/", 
"https://mapainmueble.com/properties/casa-en-renta-en-alameda-providencia-km-18-5-caes-DAC7861/", 
"https://mapainmueble.com/properties/casa-en-posadas-lomas-de-san-isidro-zona-16-dac7857/", 
"https://mapainmueble.com/properties/alquilo-casa-villa-nueva-santa-rita-DAC7855/", 
"https://mapainmueble.com/properties/casa-en-alquiler-carretera-a-san-jose-pinula-km-17-cercana-al-faro-ciudad-de-guatemala-cac3163/", 
"https://mapainmueble.com/properties/preciosa-casa-en-renta-en-zona-10-dac7853/", 
"https://mapainmueble.com/properties/oakland-ii-casa-en-renta-zona-10-DAC7849/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-DAC8100/", 
"https://mapainmueble.com/properties/casa-dentro-de-garita-zona-14-DAC8099/", 
"https://mapainmueble.com/properties/alquilo-casa-condominio-alamedas-de-san-gabriel-zona-2-capital-cac3216/", 
"https://mapainmueble.com/properties/zona-1-alquilo-casa-de-4-niveles-ideal-oficinas-o-vivienda-DAC8097/", 
"https://mapainmueble.com/properties/alquilo-casa-para-oficina-zona-1-DAC8096/", 
"https://mapainmueble.com/properties/rento-casa-con-linea-blanca-en-zona-13-dac8094/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-10-vivienda-o-comercio-DAC8093/", 
"https://mapainmueble.com/properties/zona-7-mixco-quinta-los-encinos-casa-de-3-dormitorios-en-renta-DAC8092/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-elgin-ii-DAC8091/", 
"https://mapainmueble.com/properties/rento-casa-en-condominio-villa-del-campo-km-13-caes-DAC7744/", 
"https://mapainmueble.com/properties/casa-en-renta-km-18-5-carretera-a-el-salvador-santa-anita-dac7743/", 
"https://mapainmueble.com/properties/rc001-22-lomas-verdes-DAC7739/", 
"https://mapainmueble.com/properties/casa-residencial-en-renta-en-san-cristobal-sector-b-4-DAC7736/", 
"https://mapainmueble.com/properties/casa-en-condominio-de-330-m2-de-construccion-en-renta-fraijanes-DAC7735/", 
"https://mapainmueble.com/properties/rento-casa-nueva-en-carretera-a-el-salvador-dac7731/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-14-amplia-con-18-parqueos-dac7728/", 
"https://mapainmueble.com/properties/alquiler-de-casa-en-bosques-de-las-luces-con-4-dormitorios-dac7727/", 
"https://mapainmueble.com/properties/casa-en-renta-en-villas-de-entre-verdes-DAC7726/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-15-completamente-amueblada-dac6337/", 
"https://mapainmueble.com/properties/renta-de-casa-en-zona-16-portales-de-san-isidro-DAC6313/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-lomas-de-san-isidro-de-lujo-DAC6310/", 
"https://mapainmueble.com/properties/casa-en-renta-dac6296/", 
"https://mapainmueble.com/properties/amplia-casa-en-renta-en-zona-9-para-uso-comercial-cac2709/", 
"https://mapainmueble.com/properties/casa-en-renta-en-zona-14-dentro-de-2-garitas-dac6280/", 
"https://mapainmueble.com/properties/alquiler-casa-las-cumbres-zona-16-dac6277/", 
"https://mapainmueble.com/properties/casa-en-alquiler-cayala-zona-16-de-5-habitaciones-DAC6271/", 
"https://mapainmueble.com/properties/vendo-o-rento-casa-grande-con-piscina-en-san-cristobal-dac6233/", 
"https://mapainmueble.com/properties/casa-en-zona-16-dac7704/", 
"https://mapainmueble.com/properties/se-renta-casa-en-zona-16-DAC7703/", 
"https://mapainmueble.com/properties/casa-en-renta-en-villas-de-miraflores-DAC7701/", 
"https://mapainmueble.com/properties/hermosa-casa-de-esquina-en-renta-en-zona-15-dac7699/", 
"https://mapainmueble.com/properties/renta-casa-zona-10-1-600-DAC7698/", 
"https://mapainmueble.com/properties/casa-renta-o-venta-zona-15-CAC3129/", 
"https://mapainmueble.com/properties/renta-casa-zona-10-DAC7694/", 
"https://mapainmueble.com/properties/casa-en-san-rafael-i-dac7692/", 
"https://mapainmueble.com/properties/casa-dentro-de-garita-en-renta-fraijanes-amplio-jardin-ideal-spa-DAC7690/", 
"https://mapainmueble.com/properties/renta-de-casa-en-zona-16-mundo-inmobiliario/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-ramblas-de-cayala-zona-16/", 
"https://mapainmueble.com/properties/alquiler-de-casa-en-acantos-de-cayala-zona-16/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-10-reina-sofia/", 
"https://mapainmueble.com/properties/casa-en-renta-ubicado-en-zona-16-8/", 
"https://mapainmueble.com/properties/casa-en-renta-ubicado-en-ces-2/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-4/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-3/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-2/", 
"https://mapainmueble.com/properties/casa-de-4-habitaciones-estudio-sala-familir-4-parqueos-1-300-dac7442/", 
"https://mapainmueble.com/properties/preciosa-casa-en-alquiler-en-santa-anita-carr-salvador-km-18-5-dac7441/", 
"https://mapainmueble.com/properties/preciosa-casa-en-renta-en-ces-km-18-5-dac7439/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-km-18-5-DAC7435/", 
"https://mapainmueble.com/properties/casa-en-renta-cayala-zona-16-DAC7432/", 
"https://mapainmueble.com/properties/casa-en-alquiler-nova-cayala-zona-16-de-3-dormitorios-dac7431/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-11-mariscal-para-comercio-o-vivienda-CAC3063/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-16-acantos-de-cayala-DAC7430/", 
"https://mapainmueble.com/properties/casa-en-renta-en-carretera-a-el-salvador-km-18-5-DAC7428/", 
"https://mapainmueble.com/properties/casas-en-renta-oakland-zona-10-dac5969/", 
"https://mapainmueble.com/properties/casa-en-renta-km-13-ces-3hab-dac5968/", 
"https://mapainmueble.com/properties/alquilo-casa-en-km-13-5-carretera-a-el-salvador-dac5966/", 
"https://mapainmueble.com/properties/casa-terreno-en-venta-zona-10-dac5926/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-14-la-villa-dac5886/", 
"https://mapainmueble.com/properties/casa-zona-16-las-cumbres-dac5819/", 
"https://mapainmueble.com/properties/413-casa-amueblada-en-renta-en-santa-rosalia-km-12-5-dac5792/", 
"https://mapainmueble.com/properties/casa-para-negocio-zona-9-en-alquiler-dac5766/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-16-de-4-habitaciones-ramblas-de-cayala-dac5764/", 
"https://mapainmueble.com/properties/town-house-en-zona-14/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-13/", 
"https://mapainmueble.com/properties/casa-en-renta-zona-15-9/", 
"https://mapainmueble.com/properties/casa-en-alquiler-zona-10/", 
"https://mapainmueble.com/properties/alquilo-casa-en-mariscal-zona-11/", 
"https://mapainmueble.com/properties/casa-en-alquiler-a-minutos-de-zona-10/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-zona-14/", 
"https://mapainmueble.com/properties/casa-en-alquiler-amoblada-en-zona-13/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-san-cristobal/", 
"https://mapainmueble.com/properties/casa-zona-1-dac6362/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condominio-zona-10-DAC6359/", 
"https://mapainmueble.com/properties/casa-comercial-zona-10-dac6357/", 
"https://mapainmueble.com/properties/casa-en-renta-con-acceso-a-20-calle-zona-10-ces-y-boca-del-monte-dac6355/", 
"https://mapainmueble.com/properties/casa-en-alquiler-en-san-lazaro-zona-15-guatemala-DAC6354/", 
"https://mapainmueble.com/properties/alquilo-casa-zona-15-en-vista-hermosa-2-semi-amueblada-dac6351/", 
"https://mapainmueble.com/properties/casa-en-renta-en-condominio-de-zona-10-guatemala-DAC6350/", 
"https://mapainmueble.com/properties/casa-en-elgin-ii-zona-13-dac6339/", 
"https://mapainmueble.com/properties/casa-en-oakland-i-zona-10-dac6338/", 

]
max_items = 3000


# Captures data for a specific page with provided url
def load_urls(pageUrl):

    print("Getting page: {} - Items: {}".format(pageUrl.split("page/")[1], len(urls)))
    print("------------------------------------------------------------------------")

    source = requests.get(url=pageUrl)

    soup = bs.BeautifulSoup(source.text, "html.parser")

    items = soup.find("div", {"id": "listing_ajax_container"})

    articles = items.find_all("div", {"class": "listing_wrapper"})

    for item in articles:
        try:
            url = str(item).split("data-modal-link=")[1].split(" ")[0]
            urls.append(url.split('"')[1])

            with open("./scan-{}.txt".format(date.today()), "a") as scan:
                scan.writelines("{}, \n".format(url))
                scan.close()
        except IndexError:
            with open("./scan-{}.txt".format(date.today()), "a") as scan:
                scan.writelines("Errored., \n".format(url))
                scan.close()


# Captures data for a specific entry/item with provided url
def load_item_data(item_url):
    print("loading {}".format(item_url))
    source = requests.get(url=item_url)

    soup = bs.BeautifulSoup(source.text, "html.parser")

    data = soup.find_all("div", {"class": "panel-body"})[1]
    details = data.find_all("div", {"class": "listing_detail"})

    metadata = soup.find_all("div", {"class": "panel-body"})[0]
    metadetails = metadata.find_all("div", {"class": "listing_detail"})

    mt2 = "none"
    sector = "none"
    precio = "none"
    habitaciones = "none"
    banos = "none"
    parqueos = "none"
    nombre_agente = "none"
    numero_agente = "latest"

    try:
        sector = str(metadetails[1]).split("</a>")[0].split('tag">')[1]
    except IndexError:
        pass

    try:
        precio = str(details[0]).split("</strong>")[1].split("<")[0].replace(" ", "")
    except IndexError:
        pass

    try:
        habitaciones = (
            str(details[4]).split("</strong>")[1].split("<")[0].replace(" ", "")
        )
    except IndexError:
        pass

    try:
        banos = str(details[5]).split("</strong>")[1].split("<")[0].replace(" ", "")
    except IndexError:
        pass

    try:
        parqueos = str(details[3]).split("</strong>")[1].split("<")[0].replace(" ", "")
    except IndexError:
        pass

    try:
        mt2 = str(details[1]).split("</strong>")[1].split("<")[0].replace(" ", "")
    except IndexError:
        pass

    item = {
        "eventType": "index_item",
        "available_timestamp": str(date.today()),
        "id": item_url,
        "url": item_url,
        "module": "mapainmueble-gt",
        "mt2": mt2,
        "sector": sector,
        "precio": precio,
        "habitaciones": habitaciones,
        "banos": banos,
        "parqueos": parqueos,
        "nombre_agente": nombre_agente,
        "numero_agente": numero_agente,
        "type": "rent",
        "extras": [{"parent": "Comodidades", "fields": [{"name": "Piscina"}]}],
    }

    laraIndex(item)


def get():

    p = Pool(100)
    p.map(load_urls, urls_list)
    p.terminate()
    p.join()


def data():
    d = Pool(500)
    d.map(load_item_data, urls)
    d.terminate()
    d.join()


# get()
data()
