import bs4 as bs
import requests
import math
from datetime import date

from datetime import datetime as dt
from halo import Halo
import time
import requests

from multiprocessing import Pool


#renta-alquiler
#venta

urls_list = [
    "https://puntourbanogt.com/buscar-propiedades/page/1/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/2/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/3/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/4/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/5/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/6/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/7/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/8/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/9/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/10/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/11/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/12/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/13/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/14/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/15/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/16/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/17/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/18/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/19/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/20/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/21/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/22/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/23/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/24/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/25/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/26/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/27/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/28/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/29/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/30/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/31/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/32/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/33/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/34/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/35/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/36/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/37/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/38/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/39/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/40/?status=venta",
    "https://puntourbanogt.com/buscar-propiedades/page/41/?status=venta",
]
url = "http://localhost:1337/v2/kazas"


def laraIndex(item):
    req = requests.post(url, json=item)
    print(req.text)




max_items = 616
urls = [
    "https://puntourbanogt.com/propiedad/en-venta-casa-de-dos-nivel-canadas-del-rio-colonial-z-13-s-m-p/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-en-condominio-en-zona-8-de-mixco/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-sobre-aguilar-batres-zona-11/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-las-cumbres-zona-16/", 
"https://puntourbanogt.com/propiedad/terreno-residencial-en-venta-zona-4-mixco-condado-naranjo/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-zona-17-residenciales-del-norte/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-15-guatemala-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-prados-de-santa-rita-z-2-de-mixco/", 
"https://puntourbanogt.com/propiedad/local-comercia-en-venta-en-zona-11/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-km-9-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-zona-11/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-en-condominio-en-km-14-1-caes/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-10/", 
"https://puntourbanogt.com/propiedad/venta-de-apartamento-en-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-15-guatemala/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-zona-11-mariscal-sobre-avenida-principal/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-linda-en-terravista-en-carretera-el-salvador/", 
"https://puntourbanogt.com/propiedad/apartamento-nuevo-en-venta-en-zona-1/", 
"https://puntourbanogt.com/propiedad/casa-exclusiva-en-venta-en-zona-16-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-residencial-en-hacienda-del-comendador-san-miguel-duenas/", 
"https://puntourbanogt.com/propiedad/terreno-de-1760-68-m2-en-venta-alotenango-sacatepequez/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-1/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-residencial-zona-11/", 
"https://puntourbanogt.com/propiedad/en-venta-apartamento-en-alquiler-zona-13-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-apartamento-en-renta-de-2-dormitorios-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-16-cayala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10-2/", 
"https://puntourbanogt.com/propiedad/oficina-en-venta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/hermosa-oficina-en-venta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-14-5/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-residenciales-villas-de-alcala-zona-18/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-carreter-a-lo-de-dieguez-3-habitaciones/", 
"https://puntourbanogt.com/propiedad/casa-comercial-en-venta-en-zona-13/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-12-villa-florencia/", 
"https://puntourbanogt.com/propiedad/venta-casa-zona-11-colonia-mirador-1/", 
"https://puntourbanogt.com/propiedad/venta-apartamento-zona-11-aralia-mariscal/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-zona-3-huehuetenango/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-o-renta-en-zona-16/", 
"https://puntourbanogt.com/propiedad/en-venta-condominio-san-pedro-las-huertas-barrios-coloniales/", 
"https://puntourbanogt.com/propiedad/bodega-en-venta-ofibodegas-del-lago/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-carretera-a-el-salvador-pontevedra/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-carretera-a-el-salvador-villas-capri/", 
"https://puntourbanogt.com/propiedad/en-venta-valle-navarra-san-jose-pinula/", 
"https://puntourbanogt.com/propiedad/en-venta-terreno-en-las-hojarascas-zona-1-de-mixco/", 
"https://puntourbanogt.com/propiedad/en-venta-atencion-inversionistas-vendo-casa-en-villa-hermosa-2/", 
"https://puntourbanogt.com/propiedad/preciosa-casa-amueblada-en-venta-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-casa-en-santa-catarina-pinula/", 
"https://puntourbanogt.com/propiedad/oficina-en-venta-plaza-portal-del-bosque/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-lotificacion-la-montana-edificio-santa-fe/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-valle-nuevo-ii/", 
"https://puntourbanogt.com/propiedad/oficina-en-venta-edificio-intercargo-oficina-508/", 
"https://puntourbanogt.com/propiedad/venta-de-terreno-en-san-bartolome-milpas-altas/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-villas-campestre-i-casa-11/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-aldea-el-pajon-casa-373-b/", 
"https://puntourbanogt.com/propiedad/casa-amplia-en-venta-condominio-de-san-jose-pinula/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-lotificacion-el-refugio-lote-14/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-lotificacion-el-encinal-lote-26/", 
"https://puntourbanogt.com/propiedad/apartamento-exclusivo-nuevo-en-venta-zona-16-ciudad-de-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-hacienda-nueva-country-club-lote-1i/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-la-reserva-casa-d6/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-15-liv/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-vila-verde-1/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-zona-8-santa-catarina-pinula-los-diamantes/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10-4/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-antigua-vende-terreno-en-jocotenango-sacatepequez/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-15-vista-hermosa-2-castalia/", 
"https://puntourbanogt.com/propiedad/casa-de-3-y-4-habitaciones-en-venta-hacienda-real-zona-16/", 
"https://puntourbanogt.com/propiedad/apartamento-en-pre-venta-en-avenida-petapa-zona-12/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-venta-en-zona-1/", 
"https://puntourbanogt.com/propiedad/venta-apartamento-en-zona-10-tiffany-1/", 
"https://puntourbanogt.com/propiedad/venta-de-apartamento-en-zona-10-oakland/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-vista-hermosa-2-zona-15-guatemala/", 
"https://puntourbanogt.com/propiedad/residencia-en-venta-en-condado-concepcion-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-10-en-350000-de-3-dormitorios-codigo-1557/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-14-en-450000-de-2-dormitorios-codigo-1550/", 
"https://puntourbanogt.com/propiedad/en-venta-finca-terreno-extenso-aldeas-los-platanos-quiche/", 
"https://puntourbanogt.com/propiedad/apartamentos-en-venta-cerca-de-oakland-z10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-y-o-renta-la-montana-zona-16/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-en-residencial-en-colinas-de-monte-maria/", 
"https://puntourbanogt.com/propiedad/apartamento-nuevo-en-venta-en-zona-4/", 
"https://puntourbanogt.com/propiedad/apartamento-de-137-m2-de-construccion-en-venta-zona-16/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-condominio-zona-16/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-en-zona-4-de-mixco-el-naranjo/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-exclusiva-zona-16/", 
"https://puntourbanogt.com/propiedad/en-venta-complejo-de-8-ofibodegas-con-mezanninie-de-570-mts-cada-una/", 
"https://puntourbanogt.com/propiedad/lindas-casas-en-venta-ciudad-vieja-sacatepequez/", 
"https://puntourbanogt.com/propiedad/en-venta-edificio-sobre-la-avenida-centroamerica-zona-1/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-zona-1-de-mixco-el-roconal/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-14-2/", 
"https://puntourbanogt.com/propiedad/venta-y-renta-de-apartamento-en-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-y-renta-area-condado-concepcion/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-finca-santa-delfina-la-reserva/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-10-city-haus/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-las-clarisas-de-san-pedro-las-huertas/", 
"https://puntourbanogt.com/propiedad/preventa-de-apartamento-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-de-1-habitacion-en-preventa/", 
"https://puntourbanogt.com/propiedad/vista-hermosa-ii-casa-en-venta/", 
"https://puntourbanogt.com/propiedad/casa-de-2-niveles-en-venta-en-san-pedro-las-huertas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-16-vh-4/", 
"https://puntourbanogt.com/propiedad/apartamento-de-1-dormitorio-en-venta-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-celajes-de-navarra-san-jose-pinula/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-en-zona-12-colonia-javier-de-4-dormitorios/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10-7/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-a-5-minutos-de-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-15/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamentos-en-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-carretera-a-el-salvador-en-193600-de-3-dormitorios-codigo-1653/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-16-la-vista/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-10-edificio-milenia/", 
"https://puntourbanogt.com/propiedad/terrenos-en-venta-villas-innsbruck/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-villas-europeas-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-arrazola-panorama-2/", 
"https://puntourbanogt.com/propiedad/en-venta-aparamento-vista-hermosa-ii-amueblado/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-amplia-en-zona-5/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-santa-catarina-pinula-san-antonio/", 
"https://puntourbanogt.com/propiedad/apartamento-moderno-en-venta-en-zona-10-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-gold-vende-apartamento-en-zona-11/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-11-mariscal/", 
"https://puntourbanogt.com/propiedad/en-venta-se-vende-casa-de-dos-niveles-en-sector-brasilia/", 
"https://puntourbanogt.com/propiedad/en-venta-homepro-inmobiliaria-vende-apartamento-nuevo-en-zona-2-2/", 
"https://puntourbanogt.com/propiedad/apartamento-de-60-m2-de-construccion-en-venta-zona-01/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-en-condominio-zona-8-de-mixco/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-colinas-de-monte-maria-sur-villa-nueva/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-14-2/", 
"https://puntourbanogt.com/propiedad/preciosa-casa-en-monterrico-en-venta/", 
"https://puntourbanogt.com/propiedad/preciosa-casa-amueblada-en-venta-cercana-a-antigua-gt/", 
"https://puntourbanogt.com/propiedad/preciosa-casa-en-venta-dentro-de-condominio-en-zona-16/", 
"https://puntourbanogt.com/propiedad/casa-en-la-playa-en-venta-monterrico/", 
"https://puntourbanogt.com/propiedad/venta-de-apartamento-en-el-edificio-centrico-zona-5/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-a-orilla-del-mar-en-atitancito-iztapa/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-gold-vende-casa-en-residencias-san-marino/", 
"https://puntourbanogt.com/propiedad/ofibodegas-en-venta-con-enganche-fraccionado-sin-interes/", 
"https://puntourbanogt.com/propiedad/venta-apartamento-zona-16-edificio-solaria/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-huertas-de-san-pedro-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-10-santa-catarina-pinula/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-zona-14-la-canada-de-4-dormitorios-1100000-codigo-723/", 
"https://puntourbanogt.com/propiedad/en-venta-homepro-inmobiliaria-vende-hermoso-apartamento-en-san-miguel-petapa/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-para-estrenar-balcones-san-cristobal/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-fraijanes-en-casa-y-campo/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-12-usac/", 
"https://puntourbanogt.com/propiedad/en-venta-homepro-inmobiliaria-vende-hermoso-apartamento-en-zona-15/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-10-3/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-apartamento-en-altture-zona-16/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-oficina-en-dubai-center-zona-10/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-casa-en-las-cumbres-zona-16/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-en-escuintla/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-carretera-al-pacifico/", 
"https://puntourbanogt.com/propiedad/en-alquiler-invierta-en-propiedad-comercial-en-san-lucas-sacatepequez/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-area-multimedica-1-habitacion/", 
"https://puntourbanogt.com/propiedad/preventa-apartamento-de-3-habitaciones-en-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-planos-zona-15/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-cortijo-de-las-flores/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-13/", 
"https://puntourbanogt.com/propiedad/venta-de-oficina-en-edificio-en-zona-12/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-venta-complejo-industrial-michatoya-pacifico-escuintla/", 
"https://puntourbanogt.com/propiedad/vendo-ofibodega-zona-4-mixco-final-naranjo-entrega-inmediata/", 
"https://puntourbanogt.com/propiedad/venta-de-edificio-en-puerto-barrios/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-condominio-zona-8-san-cristobal/", 
"https://puntourbanogt.com/propiedad/lindo-apartamento-para-estrenar-en-zona-4-en-venta/", 
"https://puntourbanogt.com/propiedad/excelente-apartamento-en-venta-en-zona-4/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-con-hermosos-acabados-en-zona-15/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-en-asuncion-mita-jutiapa-c-financiamiento-propio-cel-40288047/", 
"https://puntourbanogt.com/propiedad/en-venta-terrenos-cerca-de-playa-en-puerto-san-jose-cel-40288047/", 
"https://puntourbanogt.com/propiedad/en-venta-terrenos-industriales-en-michatoya-pacifico-escuintla/", 
"https://puntourbanogt.com/propiedad/en-venta-hermosa-casa-carretera-el-salvador-26-5-3-habitaciones/", 
"https://puntourbanogt.com/propiedad/chalet-en-amatitlan-venta-o-renta/", 
"https://puntourbanogt.com/propiedad/casas-en-venta-san-pedro-las-huertas-barrio-san-miguel/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-bosques-del-eden-aldea-el-canchon/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-9/", 
"https://puntourbanogt.com/propiedad/apartamentos-en-venta-zona-14-segheria/", 
"https://puntourbanogt.com/propiedad/casa-venta-zona-11-mariscal/", 
"https://puntourbanogt.com/propiedad/propiedad-en-venta-zona-11-colonia-el-progreso/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-mariscal-uno-uno-zona-11/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-san-jose-pinula-santa-ines/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-13-narama/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-santa-catarina-pinula-miraloma/", 
"https://puntourbanogt.com/propiedad/en-venta-terrenos-en-excelente-ubicacion-zona-1/", 
"https://puntourbanogt.com/propiedad/en-venta-terreno-de-48408-15-metros-cuadrados-son-120-cuerdas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10-5/", 
"https://puntourbanogt.com/propiedad/venta-finca-en-uspantan-el-quiche-excelente-para-produccion/", 
"https://puntourbanogt.com/propiedad/polideportivo-en-venta-las-arcadias/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-terreno-en-uspantan-el-quiche-14-caballerias-negociable/", 
"https://puntourbanogt.com/propiedad/propiedad-en-venta-lo-de-coy-mixco/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-ribera-del-rio/", 
"https://puntourbanogt.com/propiedad/venta-apartamento-zona-15-vista-hermosa-1/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-14-de-3-dormitorios-en-325000-codigo-1628/", 
"https://puntourbanogt.com/propiedad/venta-apartamento-zona-10-en-planos-inversionistas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-15-4/", 
"https://puntourbanogt.com/propiedad/inversion-apartamento-en-venta-zona-10-en-planos/", 
"https://puntourbanogt.com/propiedad/casas-en-venta-condominio-barrio-las-campanas/", 
"https://puntourbanogt.com/propiedad/casas-en-venta-arcos-de-santa-maria-fase-1/", 
"https://puntourbanogt.com/propiedad/linda-casa-con-hermosas-vistas-en-venta-santa-lucia-milpas-altas/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-12/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-lote-en-atanasio-tzul-zona-12/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-km-19-3-carretera-a-san-jose-pinula-manantiales/", 
"https://puntourbanogt.com/propiedad/apartamento-de-4-habitaciones-preventa-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-152-mtrs-klm-8-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-12-2/", 
"https://puntourbanogt.com/propiedad/en-venta-homepro-inmobiliaria-vende-casa-en-san-cristobal/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamentos-en-zona-9/", 
"https://puntourbanogt.com/propiedad/casas-en-venta-villas-santa-delfina/", 
"https://puntourbanogt.com/propiedad/zona-16-portal-de-san-isidro-hacienda-real-venta-de-casa/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-semi-nueva-san-cristobal/", 
"https://puntourbanogt.com/propiedad/apartamento-nuevo-en-venta-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-el-frutal-ii-villa-nueva-zona-5/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-15-guatemala-3/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-15-vista-hermosa-2-la-hondonada/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-las-clarisas-san-pedro-las-huertas/", 
"https://puntourbanogt.com/propiedad/apartamento-con-terraza-en-venta-en-zona-15/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-villa-nueva-fuera-de-garita/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-zona-2-mixco-residenciales-los-angeles/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-zona-4-mixco-bosques-de-san-nicolas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-vista-hermosa-ii/", 
"https://puntourbanogt.com/propiedad/residencia-de-lujo-en-venta-en-zona-14-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-hacienda-nueva-country-club/", 
"https://puntourbanogt.com/propiedad/en-venta-homepro-inmobiliaria-vende-penthouse-en-villa-los-cabos-monterrico/", 
"https://puntourbanogt.com/propiedad/en-venta-homepro-inmobiliaria-vende-o-renta-apartamento-en-zona-15/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-vista-hermosa-1-zona-15-en-pot-g4-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-oficina-en-zona-pradera/", 
"https://puntourbanogt.com/propiedad/apartamento-en-pre-venta-en-zona-12/", 
"https://puntourbanogt.com/propiedad/venta-de-apartamento-en-zona-16-vista-hermosa-iv/", 
"https://puntourbanogt.com/propiedad/en-venta-homepro-inmobiliaria-vende-apartamento-nuevo-en-zona-2/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/residencia-de-lujo-en-venta-zona-14-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-antigua-vende-finca-en-sector-de-sumpango-sacatepequez/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-venta-en-villa-canales/", 
"https://puntourbanogt.com/propiedad/en-venta-finca-en-coban-7-66-caballerias-rubelsanto-alta-verapaz/", 
"https://puntourbanogt.com/propiedad/citymax-gold-venta-de-casa-en-caes/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-km-19-5-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-10-2/", 
"https://puntourbanogt.com/propiedad/en-venta-homepro-inmobiliaria-vende-casa-en-condominio-en-villa-nueva/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-ofibodega-zona-4-mixco-para-estrenar/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-ofibodega-en-barcenas/", 
"https://puntourbanogt.com/propiedad/en-venta-apartamento-en-jardines-de-san-rafael-km-9-5-c-e-s/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-14/", 
"https://puntourbanogt.com/propiedad/en-venta-linda-casa-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-4/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-apartamento-2-habitaciones-zona-12-petapa/", 
"https://puntourbanogt.com/propiedad/en-venta-terreno-plano-en-sector-residencial-de-parramos-chimaltenango/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-san-lazaro-z-15-220-mtrs/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-y-renta-en-san-lucas/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-fresnos-zona-8-mixco-san-cristobal/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-amplia-casa-zona-16-jardines-de-san-isisdro/", 
"https://puntourbanogt.com/propiedad/casa-de-3-habitaciones-en-venta-en-ciudad-vieja/", 
"https://puntourbanogt.com/propiedad/casa-de-un-nivel-en-venta-en-ciudad-vieja/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-monte-maria-ii/", 
"https://puntourbanogt.com/propiedad/hermosa-casa-en-venta-en-san-pedro-las-huertas-con-finos-acabados/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-4-de-mixco/", 
"https://puntourbanogt.com/propiedad/en-venta-hermosa-propiedad-en-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-vh-ii-zona-15/", 
"https://puntourbanogt.com/propiedad/en-venta-excelente-propiedad-en-area-comercial-residencial-de-zona-9/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-5-villa-nueva/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-10-villa-nueva/", 
"https://puntourbanogt.com/propiedad/finca-en-venta-santo-tomas-milpas-altas-sacatepequez/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamentos-en-zona-12-2/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-apartamento-en-nogales-de-cayala-zona-16/", 
"https://puntourbanogt.com/propiedad/venta-de-apto-zona-16-shift-cayala-1-habitacion/", 
"https://puntourbanogt.com/propiedad/vendo-amplia-exclusiva-y-hermosa-casa-de-4-dormitorios-km-22-carretera-a-el-salvador-monte-pinasco-diseno-moderno/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10-6/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-las-luces/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-parajes-del-encinal-zona-6-de-mixco/", 
"https://puntourbanogt.com/propiedad/casa-vacacional-en-venta-en-escuintla/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-16/", 
"https://puntourbanogt.com/propiedad/en-venta-se-vende-casa-en-la-villa-zona-14-280mtrs2/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-casa-en-ciudad-vieja-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-14-en-380000-de-2-dormitorios-codigo-1574/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10-en-331000-de-2-dormitorios-codigo-1572/", 
"https://puntourbanogt.com/propiedad/venta-en-finquita-area-de-cienaga-grande/", 
"https://puntourbanogt.com/propiedad/oficina-en-venta-y-renta-en-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamentos-en-venta-en-el-corazon-de-zona-4-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-apartamento-zona-2-edificio-primium-ii/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10-3/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-con-hermosos-acabados-en-condominio-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-sector-a6-san-cristobal/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-14-6/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-15-ideal-para-inversion/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-san-antonio-carretera-a-el-salvador-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-14-en-695000-de-3-dormitorios-codigo-1543/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-venta-y-renta-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-10-con-garita/", 
"https://puntourbanogt.com/propiedad/casas-en-venta-en-km-9-5-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/apartamenteo-en-venta-en-zona-15-vista-hermosa-ii/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-inversion-en-zona-10-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-venta-y-renta-zona-9/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-amplia-casa-zona-4-mixco-tulam-tzu/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-el-casco-de-antigua/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-sobre-ruta-nacional-14-ciudad-vieja/", 
"https://puntourbanogt.com/propiedad/linda-casa-en-venta-san-cristobal-zona-8-de-mixco/", 
"https://puntourbanogt.com/propiedad/venta-de-oficina-en-zona-4/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-en-zona-4-mazatenango/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-de-playa-ubicada-en-san-marino-i/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-residencial-la-canada-de-san-lucas/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamento-en-zona-10/", 
"https://puntourbanogt.com/propiedad/venta-de-oficina-en-zona-4-de-mixco/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-cerca-de-universidad-de-san-carlos/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-en-zona-15/", 
"https://puntourbanogt.com/propiedad/venta-apartamento-de-dos-niveles-zona-11/", 
"https://puntourbanogt.com/propiedad/bodega-en-venta-zona-13-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-14-3-habitaciones-280-mtrs-5-parqueos/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-km-17-carretera-a-san-jose-pinula/", 
"https://puntourbanogt.com/propiedad/oficina-en-venta-en-zona-14-2/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-con-terreno-extra-en-hacienda-de-las-flores-vn/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta/", 
"https://puntourbanogt.com/propiedad/venta-edificio-zona-9-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-equipado-en-venta-zona-10-edificio-casa-margarita/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-san-cristobal-loma-real/", 
"https://puntourbanogt.com/propiedad/en-venta-terreno-1039-metros-cuadrados/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-7-di-fiori/", 
"https://puntourbanogt.com/propiedad/terreno-vacacional-en-venta-quinta-la-ponderosa-escuitla/", 
"https://puntourbanogt.com/propiedad/venta-de-terreno-residencial-en-zona-16/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-16-edificio-cadoro/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-13-en-250000-de-3-dormitorios-codigo-1705/", 
"https://puntourbanogt.com/propiedad/en-venta-apartamento-en-zona-14-las-conchas-3-habitaciones/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-venta-santorini-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-zona-10/", 
"https://puntourbanogt.com/propiedad/en-venta-apartamento-en-condominio-juan-pablo-practicamente-sobre-calzada-san-juan-y-contiguo-plaza-florida/", 
"https://puntourbanogt.com/propiedad/citymax-gold-venta-de-casa-de-playa-el-ahumado-santa-rosa/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-7-mateo-flores-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-4-en-140000-de-2-dormitorios-codigo-1536/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-antigua-vende-terreno-en-residencial-santo-tomas-milpas-altas/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-antigua-vende-casa-san-miguel-escobar/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-carretera-al-salvador-bosque-escondido/", 
"https://puntourbanogt.com/propiedad/hermosa-casa-en-venta-las-luces-del-encinal/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-20-calle-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-8-de-mixco-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-km-9-ces-cercano-a-zona-15/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-carretera-a-el-salvador-4-dormitorios-en-345000/", 
"https://puntourbanogt.com/propiedad/en-venta-km-25-real-del-campo-vendo-amplia-casa-por-colegio-village/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-4-de-mixco-el-naranjo/", 
"https://puntourbanogt.com/propiedad/casa-3-habitaciones-en-venta-km-14-ces/", 
"https://puntourbanogt.com/propiedad/citymax-gold-preventa-apartamento-en-zona-13/", 
"https://puntourbanogt.com/propiedad/pre-venta-apartamento-en-zona-10-2/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-en-zona-11-3/", 
"https://puntourbanogt.com/propiedad/vendo-preciosa-casa-en-san-cristobal-condominio-vista-al-valle/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-residencial-zona-5-villa-nueva/", 
"https://puntourbanogt.com/propiedad/citymax-gold-pre-venta-apartamento-en-sector-mas-exclusivos-de-zona-16/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-san-gaspar-zona-16/", 
"https://puntourbanogt.com/propiedad/oficina-en-venta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-o-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/zona-5-vendo-propiedad-a-pocos-metros-del-munecon/", 
"https://puntourbanogt.com/propiedad/vendo-46290-vr2-de-terreno-a-orilla-de-carretera-km-23-ces/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-4-habitaciones-km-16-5-ces/", 
"https://puntourbanogt.com/propiedad/apartamentos-en-preventa-terradelfines-zona-14/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-venta-renta-casa-grande-en-ciudad-vieja-sacatepequez/", 
"https://puntourbanogt.com/propiedad/ganga-casa-en-venta-sector-villa-hermosa-ii/", 
"https://puntourbanogt.com/propiedad/terreno-para-inversion-en-venta-zona-10-de-mixco-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-las-charcas-zona-11/", 
"https://puntourbanogt.com/propiedad/en-venta-se-vende-casa-en-bananera-morales-izabal/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-16-2/", 
"https://puntourbanogt.com/propiedad/linda-casa-en-venta-san-lucas-sacatepequez/", 
"https://puntourbanogt.com/propiedad/casa-para-estrenar-en-venta-a-5-min-de-antigua/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-oportunidad-terreno-en-venta-carretera-a-yepocapa/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-km-22-7-ces/", 
"https://puntourbanogt.com/propiedad/en-venta-apartamentos-en-zona-14-desde-q476200/", 
"https://puntourbanogt.com/propiedad/citymax-gold-venta-apartamento-en-zona-16/", 
"https://puntourbanogt.com/propiedad/citymax-gold-venta-casa-km-22-caes/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamentos-en-zona-4/", 
"https://puntourbanogt.com/propiedad/casa-de-275-m2-de-construccion-en-venta-carretera-a-el-salvador-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-12-cerca-usac/", 
"https://puntourbanogt.com/propiedad/apartamento-de-98-m2-de-construccion-en-venta-zona-16-2/", 
"https://puntourbanogt.com/propiedad/apartamentos-en-venta-en-zona-9/", 
"https://puntourbanogt.com/propiedad/citymax-gold-pre-venta-apartamento-en-zona-4/", 
"https://puntourbanogt.com/propiedad/pre-venta-apartamento-en-zona-10/", 
"https://puntourbanogt.com/propiedad/en-venta-apartamento-386-metros-zona-14-la-canada/", 
"https://puntourbanogt.com/propiedad/en-venta-km-10-ces-vendo-terreno-en-vistalvalle-825-mts2-2/", 
"https://puntourbanogt.com/propiedad/oficina-de-157-26-m2-de-construccion-en-venta-zona-15/", 
"https://puntourbanogt.com/propiedad/terrenos-en-venta-en-escuintla-masagua/", 
"https://puntourbanogt.com/propiedad/propiedad-pot-g4-en-venta-en-vista-hermosa-1-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-zona-4-de-mixco-guatemala/", 
"https://puntourbanogt.com/propiedad/citymax-gold-venta-de-casa-ciudad-san-cristobal/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-en-km-33-5-san-lucas/", 
"https://puntourbanogt.com/propiedad/en-venta-km-30-san-jose-pinula-vendo-linda-casa-campestre/", 
"https://puntourbanogt.com/propiedad/casas-en-venta-lomas-de-san-isidro-zona-16-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/en-venta-terrenos-empresariales-e-industriales-en-el-naranjo/", 
"https://puntourbanogt.com/propiedad/casa-de-175-m2-de-construccion-en-venta-mixco/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-casa-tipo-granja-de-venta-en-tecpan-dentro-residencial/", 
"https://puntourbanogt.com/propiedad/apartamentos-en-venta-en-zona-13/", 
"https://puntourbanogt.com/propiedad/en-venta-superate-a-ti-mismo-suena-invierte-vive-en-zona-10/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-gold-vendo-casa-en-zona-1-guatemala-c-a/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-exclusivo-condominio-oakland-zona-10/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-casa-bosques-de-san-nicolas/", 
"https://puntourbanogt.com/propiedad/en-venta-atencion-inversionistas-bodega-con-inquilino-incluido/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-oakland-zona-10-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-carretera-a-el-salvador-de-4-dormitorios-en-800000/", 
"https://puntourbanogt.com/propiedad/apartamento-amplio-en-venta-vista-hermosa-2-zona-15-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-vista-hermosa-i-zona-15-guatemala-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-12-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-lote-cementerio-los-parques/", 
"https://puntourbanogt.com/propiedad/apartamento-de-126-m2-de-construccion-en-venta-zona-14/", 
"https://puntourbanogt.com/propiedad/terreno-de-182-65-m2-en-venta-carretera-a-olmeca-pavon/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-venta-en-zona-4-mixco-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-16-canajuyu-vendo-linda-propiedad-2/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-4-de-mixco-vendo-casa-dentro-de-garita-por-el-igss-19-10-2/", 
"https://puntourbanogt.com/propiedad/casa-de-370-m2-de-construccion-en-venta-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/local-de-53-55-m2-de-construccion-en-venta-zona-13-2/", 
"https://puntourbanogt.com/propiedad/venta-de-terreno-en-terravista-fraijanes-guatemala/", 
"https://puntourbanogt.com/propiedad/venta-de-terreno-en-los-manantiales-san-jose-pinula/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-pequena-en-la-zona-12-reformita/", 
"https://puntourbanogt.com/propiedad/venta-de-inmueble-para-inversionesitas-en-zona-8-de-la-ciudad-capital/", 
"https://puntourbanogt.com/propiedad/venta-de-terreno-en-km-33-chacaya-santiago-sacatepequez/", 
"https://puntourbanogt.com/propiedad/venta-o-renta-de-apartamento-en-altture-zona-16/", 
"https://puntourbanogt.com/propiedad/zona-4-de-mixco-vendo-casa-dentro-de-garita-por-el-igss-19-10/", 
"https://puntourbanogt.com/propiedad/venta-de-townhouse-en-zona-11/", 
"https://puntourbanogt.com/propiedad/en-venta-centro-empresarial-pacifico-sur-puerto-de-san-jose/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-a-una-cuadra-calzada-roosevelt/", 
"https://puntourbanogt.com/propiedad/venta-apartamento-santa-catarina-pinula/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-villas-granada-2/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-carretera-a-el-salvador-cumbres-de-la-arboleda/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-amplia-la-montana-zona-16-villas-de-la-montana/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-ofiespacio-zona-4-mixco/", 
"https://puntourbanogt.com/propiedad/lujoso-y-exclusivo-apartamento-en-venta-zona-14/", 
"https://puntourbanogt.com/propiedad/pre-venta-de-apartamentos-en-zona-12/", 
"https://puntourbanogt.com/propiedad/terreno-plano-en-venta-en-el-centro-de-chimaltenango/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-casa-en-venta-en-zona-2-de-coatepeque/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-el-centro-de-san-lucas/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-condominio-de-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/oficina-en-venta-en-zona-13-guatemala/", 
"https://puntourbanogt.com/propiedad/zona-4-de-mixco-vendo-casa-dentro-de-garita-por-el-igss-19-10-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-1-edificio-el-prado/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-para-inversion-en-edificio-ikonia-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-zona-11-guatemala/", 
"https://puntourbanogt.com/propiedad/lindo-terreno-en-venta-en-miralvalle-sumpango-sacatepequez/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-san-miguel-petapa/", 
"https://puntourbanogt.com/propiedad/linda-casa-en-venta-en-ces-con-muebles-y-linea-blanca-incluida/", 
"https://puntourbanogt.com/propiedad/apartamento-de-221-7-m2-de-construccion-en-venta-zona-15/", 
"https://puntourbanogt.com/propiedad/en-venta-km-8-ces-vendo-amplio-apartamento-vista-real-300-mts-3/", 
"https://puntourbanogt.com/propiedad/residencia-premium-en-venta-en-muxbal-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/mausoleo-en-venta-zona-14-cementerio-la-villa-area-vip/", 
"https://puntourbanogt.com/propiedad/casa-grande-en-venta-en-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/oficina-de-60-m2-de-construccion-en-venta-zona-15/", 
"https://puntourbanogt.com/propiedad/en-venta-amplio-edificio-en-renta-en-zona-1/", 
"https://puntourbanogt.com/propiedad/apartamento-de-97-m2-de-construccion-en-venta-zona-10-2/", 
"https://puntourbanogt.com/propiedad/en-venta-lindos-terrenos-en-jardines-de-marbella-san-lucas-sacatepequez/", 
"https://puntourbanogt.com/propiedad/viviendas-en-condominio-en-venta/", 
"https://puntourbanogt.com/propiedad/zona-10-centrica-casa-en-venta-cercana-centro-medico-y-la-universidad/", 
"https://puntourbanogt.com/propiedad/en-venta-viviendas-con-parqueo-4-vehiculos/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-antigua-vende-terreno-residencial-en-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/casas-en-venta-en-zona-8-de-mixco-pinares/", 
"https://puntourbanogt.com/propiedad/apartamentos-en-pre-venta-zona-4/", 
"https://puntourbanogt.com/propiedad/terreno-en-venta-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/casa-vacacional-en-venta-en-likin/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-km-16-c-s-santa-anita/", 
"https://puntourbanogt.com/propiedad/bodega-en-venta-en-zona-13-de-200-mts-en-585000-codigo-1571/", 
"https://puntourbanogt.com/propiedad/en-venta-lindos-terrenos-en-venta-el-ensueno-san-lucas/", 
"https://puntourbanogt.com/propiedad/vendo-apartamento-parque-7-con-alquiler-y-muebles/", 
"https://puntourbanogt.com/propiedad/apartamento-en-pre-venta-zona-16/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-venta-casa-en-zona-1-san-lucas/", 
"https://puntourbanogt.com/propiedad/edificio-en-venta-en-ciudad-vieja-sacatepequez-ideal-para-colegio/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-vende-casa-en-el-ronconal-mixco-gt/", 
"https://puntourbanogt.com/propiedad/terreno-residencial-en-venta-bella-vista-jocotenango-sacatepequez/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-11-las-gemas-apartamento-de-3-dormitorios/", 
"https://puntourbanogt.com/propiedad/citymax-gold-venta-apartamento-en-4grados-norte-zona-4/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-zona-4-de-mixco-el-naranjo-en-condominio/", 
"https://puntourbanogt.com/propiedad/apartamento-de-188-m2-de-construccion-en-venta-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-11-excelente-ubicacion/", 
"https://puntourbanogt.com/propiedad/terreno-de-190-m2-de-construccion-en-venta-fraijanes/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-casa-con-piscina-en-cortijo-las-flores/", 
"https://puntourbanogt.com/propiedad/en-venta-cupertino-muxbal-apartamento-2-dormitorios/", 
"https://puntourbanogt.com/propiedad/casa-de-lujo-con-piscina-en-venta-a-5-min-de-antigua/", 
"https://puntourbanogt.com/propiedad/zona-14-en-venta-attica-de-2-dormitorios/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-8-de-san-cristobal-vendo-casa-dentro-de-garita/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-15-botticelli-2-vendo-apartamento-2/", 
"https://puntourbanogt.com/propiedad/exclusivo-terreno-en-venta-a-5-cuadras-del-parque-de-antigua/", 
"https://puntourbanogt.com/propiedad/finca-en-venta-en-puerto-san-jose-escuintla/", 
"https://puntourbanogt.com/propiedad/edificio-en-venta-zona-1-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/zona-10-grupo-neo-apartamento-en-venta-2/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-exclusivo-condominio-zona-16/", 
"https://puntourbanogt.com/propiedad/oficina-de-53-46-m2-de-construccion-en-venta-zona-15/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-10-plaza-buro-vendo-oficina-de-41-mts2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-10-en-220000-de-2-dormitorio-cod-1426/", 
"https://puntourbanogt.com/propiedad/citymax-gold-pre-venta-ofi-bodega-en-complejo-industrial-el-naranjo/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-zona-4-de-mixco-guatemala-2/", 
"https://puntourbanogt.com/propiedad/zona-13-vendo-derecho-de-llave-para-negocio-de-alquiler-de-vestidos/", 
"https://puntourbanogt.com/propiedad/terrenos-en-venta-en-zona-4-de-villa-nueva/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-vende-casa-en-el-casco-de-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-11-torre-once/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-2-vendo-amplia-casa-en-ciudad-nueva/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-nueva-de-esquina-en-la-serenisima-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/casas-en-venta-en-zona-8-de-mixco/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-9-oficinas-para-estrenar-desde-35-mts-ascend/", 
"https://puntourbanogt.com/propiedad/terreno-de-530-34-en-venta-zona-16/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-terreno-en-venta-en-el-hato-la-antigua-ganga/", 
"https://puntourbanogt.com/propiedad/en-venta-km-21-loma-point-vendo-terreno-359-mts-plano/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-km-21-5-carretera-fraijanes-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/apartamentos-en-venta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/citymax-terreno-venta-a-metros-ca-interamericana-santiago-sacatepequez/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-apartamento-en-planos-zona-14-la-villa/", 
"https://puntourbanogt.com/propiedad/apartamento-de-100-m2-de-construccion-en-venta-zona-14-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-14-en-297237-de-2-dormitorio-cod-1513/", 
"https://puntourbanogt.com/propiedad/bodega-en-venta-en-mixco-de-300-mts-en-521671-codigo-1509/", 
"https://puntourbanogt.com/propiedad/bodega-en-venta-en-mixco-de-650-mts-en-733708-codigo-1527/", 
"https://puntourbanogt.com/propiedad/apartamento-en-pre-venta-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-12-calzada-atanasio-tzul/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-para-estrenar-en-zona-4/", 
"https://puntourbanogt.com/propiedad/casa-de-116-m2-de-construccion-en-venta-santa-catarina-pinula-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-zona-10-para-inversion/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-7-villa-nueva/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-condominio-zona-16/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-11-granai/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-grande-en-planes-de-barcenas/", 
"https://puntourbanogt.com/propiedad/clinica-medicas-en-preventa-en-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-km-21-5-carretera-a-fraijanes-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/terreno-de-420-m2-en-venta-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-zona-16-la-montana-ciudad-de-guatemala/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-antigua-vende-casa-a-metros-de-ca-interamericana-santiago-sac/", 
"https://puntourbanogt.com/propiedad/mausoleo-en-venta-zona-14-cementerio-la-villa-area-vip-2/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-11-torre-once-vendo-apartamento-para-estrenar-3-dormitorios/", 
"https://puntourbanogt.com/propiedad/venta-de-casa-de-3-niveles-en-condominio-de-ciudad-san-cristobal/", 
"https://puntourbanogt.com/propiedad/zona-14-vendo-apartamento-263-mts-edificio-terranova-5-parqueos/", 
"https://puntourbanogt.com/propiedad/venta-ofibodega-en-san-cristobal-sector-a5/", 
"https://puntourbanogt.com/propiedad/zona-10-grupo-neo-apartamento-en-venta/", 
"https://puntourbanogt.com/propiedad/apartamento-de-134-17-m2-de-construccion-en-venta-zona-10/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-terreno-1270-vr2-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-de-59-48-m2-de-construccion-en-venta-zona-04-2/", 
"https://puntourbanogt.com/propiedad/en-venta-casa-en-km-22-carretera-a-el-salvador-loma-point/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-6-dormitorios-en-villa-serena-muxbal/", 
"https://puntourbanogt.com/propiedad/en-venta-vendo-linda-casa-campestre-km-30-san-jose-pinula/", 
"https://puntourbanogt.com/propiedad/en-venta-citymax-vende-ofi-bodega-industrial-en-el-naranjo/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-13-avenida-hincapie/", 
"https://puntourbanogt.com/propiedad/apartamento-de-100-m2-de-construccion-en-venta-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-en-zona-15-vh-ii/", 
"https://puntourbanogt.com/propiedad/terreno-de-2562-28-m2-en-venta-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/en-venta-zona-11-mariscal-vendo-propiedad-2060-varas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-venta-en-zona-1-2/", 
"https://puntourbanogt.com/propiedad/casa-de-340-43-m2-de-construccion-en-venta-zona-16/", 
"https://puntourbanogt.com/propiedad/casa-de-314-27-m2-de-construccion-en-venta-zona-16/",
]
# Captures data for a specific page with provided url
def load_urls(pageUrl):

    print("Getting page: {} - Items: {}".format(pageUrl.split("page/")[1], len(urls)))
    print("------------------------------------------------------------------------")

    source = requests.get(url=pageUrl, allow_redirects=True, headers={  'User-Agent': "PostmanRuntime/7.28.4" })

    soup = bs.BeautifulSoup(source.text, "html.parser")

    items = soup.find_all("div", {"class": "rh_list_card__wrap"})

    for item in items:
        url = item.find("a", href=True)['href']
        with open("./scan-{}.txt".format(date.today()), "a") as scan:
                scan.writelines("{}, \n".format(str(url)))
                scan.close()


# Captures data for a specific entry/item with provided url
def load_item_data(item_url):
    print("loading {}".format(item_url))
    source = requests.get(url=item_url,  allow_redirects=True, headers={  'User-Agent': "PostmanRuntime/7.28.4" })

    soup = bs.BeautifulSoup(source.text, "html.parser")


    mt2 = "none"
    sector = "none"
    precio = "none"
    habitaciones = "none"
    banos = "none"
    parqueos = "none"
    nombre_agente = "none"
    numero_agente = "latest"



    try:
        sector = soup.find("nav", {"class": "property-breadcrumbs"}).find_all("li")[2].find("a").get_text()
    except (IndexError, AttributeError):
        pass

    try:
        precio = soup.find("div", {"class": "rh_page__property_price"}).find("p", {"class": "price"}).get_text()
    except (IndexError, AttributeError):
        pass

    try:
        habitaciones = (
            soup.find("div", {"class": "rh_property__meta prop_bedrooms"}).find("span", {"class": "figure"}).get_text()
        )
    except (IndexError, AttributeError):
        pass

    try:
        banos = soup.find("div", {"class": "rh_property__meta prop_bathrooms"}).find("span", {"class": "figure"}).get_text()
    except (IndexError, AttributeError):
        pass

    try:
        parqueos = soup.find("div", {"class": "rh_property__meta prop_garages"}).find("span", {"class": "figure"}).get_text()
    except (IndexError, AttributeError):
        pass

    try:
        mt2 = soup.find("div", {"class": "rh_property__meta prop_area"}).find("span", {"class": "figure"}).get_text()
    except (IndexError, AttributeError):
        pass

    item = {
        "eventType": "index_item",
        "available_timestamp": str(date.today()),
        "id": item_url,
        "url": item_url,
        "module": "puntourbanogt-gt",
        "mt2": mt2.strip(),
        "sector": sector.strip(),
        "precio": precio.strip(),
        "habitaciones": habitaciones.strip(),
        "banos": banos.strip(),
        "parqueos": parqueos.strip(),
        "nombre_agente": nombre_agente.strip(),
        "numero_agente": numero_agente.strip(),
        "type": "buy",
        "extras": [{"parent": "Comodidades", "fields": [{"name": "Piscina"}]}],
    }

    laraIndex(item)


def get():

    p = Pool(10)
    p.map(load_urls, urls_list)
    p.terminate()
    p.join()


def data():
    d = Pool(100)
    d.map(load_item_data, urls)
    d.terminate()
    d.join()


# get()
data()
