import bs4 as bs
import requests
import math
from datetime import date

from datetime import datetime as dt
from halo import Halo
import time
import requests

from multiprocessing import Pool


#renta-alquiler
#venta

urls_list = [
    "https://puntourbanogt.com/buscar-propiedades/page/1/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/2/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/3/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/4/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/5/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/6/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/7/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/8/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/9/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/10/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/11/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/12/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/13/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/14/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/15/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/16/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/17/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/18/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/19/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/20/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/21/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/22/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/23/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/24/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/25/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/26/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/27/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/28/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/29/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/30/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/31/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/32/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/33/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/34/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/35/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/36/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/37/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/38/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/39/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/40/?status=renta-alquiler",
    "https://puntourbanogt.com/buscar-propiedades/page/41/?status=renta-alquiler",
]
url = "http://localhost:1337/v2/kazas"


def laraIndex(item):
    req = requests.post(url, json=item)
    print(req.text)




max_items = 616
urls = [
    "https://puntourbanogt.com/propiedad/apartamento-tipo-loft-en-alquiler-viu-zona-16/", 
"https://puntourbanogt.com/propiedad/citymax-renta-apartamento-en-santa-lucia-milpas-altas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-zona-15-guatemala/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-zona-pradera-zona-10-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-torres-de-villaflores/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-en-condominio-zona-12-guatemala/", 
"https://puntourbanogt.com/propiedad/alquiler-de-casa-en-zona-15-san-lazaro/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-condominio-de-fraijanes-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-con-jardin-en-renta-fraijanes/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-en-km-20-carretera-a-fraijanes/", 
"https://puntourbanogt.com/propiedad/homepro-inmobiliaria-renta-casa-en-carretera-a-fraijanes/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-zona-15-cerca-de-cayala/", 
"https://puntourbanogt.com/propiedad/en-alquiler-hermoso-apartamento-amueblado-en-zona-10/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-en-bella-vista-jocotenango-sacatepequez/", 
"https://puntourbanogt.com/propiedad/edificio-en-renta-en-zona-4/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-apartamento-amoblado-en-zona-2/", 
"https://puntourbanogt.com/propiedad/casa-comercial-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apto-en-zona-14-en-alquiler-de-3-habitaciones-en-1320-codigo-1154/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-en-zona-9/", 
"https://puntourbanogt.com/propiedad/apto-en-zona-15-en-alquiler-de-2-habitaciones-en-1375-codigo-1266/", 
"https://puntourbanogt.com/propiedad/apto-en-zona-15-en-alquiler-de-2-habitaciones-en-1200-codigo-622/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/apto-en-zona-15-en-alquiler-de-3-habitaciones-en-1100-codigo-1640/", 
"https://puntourbanogt.com/propiedad/apto-en-z-15-en-alquiler-de-2-habitaciones-en-900-codigo-1380/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-sobre-carretera-al-pacifico/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-parque-logistico-amatitlan/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-carretera-al-pacifico/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-en-san-gaspar-vivar/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-14-garces-de-la-villa/", 
"https://puntourbanogt.com/propiedad/apto-z-14-en-alquiler-2-hab-800-cod-1643/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-11-mariscal-uno-uno/", 
"https://puntourbanogt.com/propiedad/local-en-renta-entrada-principal-san-lucas-sacatepequez/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-11-santa-maria-de-las-charcas/", 
"https://puntourbanogt.com/propiedad/casa-en-condominio-en-renta-en-zona-14-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-de-72-m2-de-construccion-en-renta-zona-15/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-condominio-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-condominio-zona-10-guatemala/", 
"https://puntourbanogt.com/propiedad/local-en-renta-en-zona-4/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-amplio-en-venta-en-zona-14-guatemala/", 
"https://puntourbanogt.com/propiedad/alquiler-oficina-comercial-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-precioso-amueblado-en-renta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-nuevo-en-renta-zona-2-statera-apartamentos/", 
"https://puntourbanogt.com/propiedad/%f0%9f%9f%a1apartamento-semi-amoblado-en-renta-zona-10-casalini-%f0%9f%8c%87/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-zona-8-de-mixco/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-oficina-en-zona-9-182mts/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-en-palin-escuintla/", 
"https://puntourbanogt.com/propiedad/ofiespacio-en-renta-en-zona-5/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-zona-10-de-250-mts-en-3657-codigo-1650/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-13/", 
"https://puntourbanogt.com/propiedad/ofiespacio-en-renta-en-zona-12/", 
"https://puntourbanogt.com/propiedad/residencia-en-alquiler-en-condominio-de-muxbal/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-renta-en-zona-15/", 
"https://puntourbanogt.com/propiedad/en-alquiler-lindo-partamento-amueblado-zona-14/", 
"https://puntourbanogt.com/propiedad/ofi-bodega-en-renta-en-zona-12/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-para-estrenar-apartamento-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-de-oficina-o-local-en-edificio-zona-13/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-amueblado-zona-14/", 
"https://puntourbanogt.com/propiedad/oficina-renta-ciudad-guatemala-zona-4-111/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-alquiler-zona-3-de-mixco/", 
"https://puntourbanogt.com/propiedad/citymax-renta-casa-en-labor-de-castilla-mixco/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-zona-1-cerca-de-hospital-los-angeles/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-apartamento-km-17-5-carretera-salvador/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-san-miguel-petapa/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-10-edificio-los-girasoles/", 
"https://puntourbanogt.com/propiedad/venta-y-renta-apartamento-zona-14/", 
"https://puntourbanogt.com/propiedad/alquiler-de-oficinas-ciudad-cayala-zona-16/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-zona-10-dentro-de-condominio/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-dentro-de-condominio-zona-10/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-10-de-83-mts-en-34264-codigo-1596/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-escuintla-de-10000-mts-en-55000-codigo-1587/", 
"https://puntourbanogt.com/propiedad/alquiler-de-casa-en-fraijanes-caes/", 
"https://puntourbanogt.com/propiedad/citymaxgold-alquiler-de-oficina-en-zona-15/", 
"https://puntourbanogt.com/propiedad/venta-renta-apartamento-vista-hermosa-i-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-11-mariscal-2/", 
"https://puntourbanogt.com/propiedad/homepro-inmobiliaria-renta-oficina-en-geminis-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-oficina-en-avia-zona-10/", 
"https://puntourbanogt.com/propiedad/se-renta-local-de-80mt2-en-plaza-comercial-de-mucha-afluencia/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-10-en-1800-de-2-dormitorios-cod-1667/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-zona-12/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-alquiler-zona-10-en-1000-de-2-dorm-cod-1606/", 
"https://puntourbanogt.com/propiedad/alquiler-de-oficina-en-zona-10-plaza-paseo/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-en-caes-km-14-5/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-zona-9-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-de-oficina-comercial-en-zona-10/", 
"https://puntourbanogt.com/propiedad/local-en-renta-en-primer-nivel-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-de-apartamento-en-edificio-moderno-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-local-comercial-en-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-zona-4-mixco-las-tunas/", 
"https://puntourbanogt.com/propiedad/alquiler-de-local-en-zona-10-los-proceres/", 
"https://puntourbanogt.com/propiedad/en-alquiler-citymax-vende-casa-en-arcos-de-santa-maria/", 
"https://puntourbanogt.com/propiedad/alquiler-de-apartamento-en-zona-15/", 
"https://puntourbanogt.com/propiedad/en-renta-apartamento-tipo-estudio-km-14-5-ces/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-en-zona-10-4/", 
"https://puntourbanogt.com/propiedad/en-alquiler-local-comercial-en-zona-9/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-zona-16-distrito-mod/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-zona-14-columbus-center/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-10-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-km8-8-antigua-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-paseo-del-obispo-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/homepro-inmobiliaria-renta-apartamento-nuevo-en-nagano/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-zona-9/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-13-mirador-elgin/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-bonavita-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-16-solverde/", 
"https://puntourbanogt.com/propiedad/lindo-apartamento-en-renta-ancona-zona-1-de-mixco/", 
"https://puntourbanogt.com/propiedad/se-rentan-locales-comerciales-san-lucas-sacatepequez-segundo-nivel/", 
"https://puntourbanogt.com/propiedad/homepro-inmobiliaria-renta-oficina-en-zona-9/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-los-alamos-de-1000-mts-en-5600-codigo-1679/", 
"https://puntourbanogt.com/propiedad/alquiler-de-propiedad-para-oficina-o-clinicas-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-vista-hermosa-2-zona-15/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-apartamento-en-casa-asuncion-zona-5-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-condominio-zona-10-guatemala-2/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-los-celajes-de-santa-cruz-del-quiche/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-amatitlan-de-4000-mts-en-23196-30-codigo-1704/", 
"https://puntourbanogt.com/propiedad/en-renta-amplia-oficina-zona-14-sector-americas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-zona-15-guatemala-3/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-renta-en-zona-15-guatemala/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-382-metros-3-habitaciones-amueblado/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-renta-en-cayala-zona-16-guatemala/", 
"https://puntourbanogt.com/propiedad/local-en-renta-en-segundo-nivel-66mt2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-de-apartamento-en-zona-13/", 
"https://puntourbanogt.com/propiedad/en-alquiler-bonita-casa-zona-14-dentro-de-residenciales-darue/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-1-edificio-lido/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-y-venta-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-de-oficina-en-zona-9/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-amueblado-zona-10/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-condominio-las-clarisas/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-apartamento-en-zona-14-la-villa/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-vista-hermosa-i/", 
"https://puntourbanogt.com/propiedad/en-alquiler-%e2%80%bc%ef%b8%8falquilo-precioso-apartamento-amueblado-en-zona-14-%e2%80%bc%ef%b8%8f/", 
"https://puntourbanogt.com/propiedad/en-alquiler-%e2%80%bc%ef%b8%8falquilo-apartamento-en-zona-13%e2%80%bc%ef%b8%8f/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-zona-1/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-apartamento-en-zona-4-de-mixco/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-iztapa/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-condominio-vertical-zona-13/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-zona-15/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-amatitlan-de-4000-mts-en-16410-codigo-1706/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-zona-12-de-175-mts-en-2719-15-codigo-1689/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-5-centrico/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-vista-hermosa-i-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-15-vista-hermosa-i-edificio-fontainebleau/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-10-de-125-mts-en-1470-codigo-1707/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-10-de-700-mts-en-8530-74-codigo-1695/", 
"https://puntourbanogt.com/propiedad/alquiler-de-clinicas-en-edificio-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-14-edificio-albero-14/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-caes-edificio-scena-2/", 
"https://puntourbanogt.com/propiedad/zona-11-mariscal-alquiler-de-bodega-de-2244-mts2-con-oficinas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-15-vista-hermosa-i-edificio-los-rincones/", 
"https://puntourbanogt.com/propiedad/casa-exclusiva-en-renta-zona-16-guatemala/", 
"https://puntourbanogt.com/propiedad/casa-tipo-townhouse-de-136-m2-de-construccion-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-alquiler-zona-10-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-segheria-zona-14/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-10-de-125-mts-en-1484-codigo-1598/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-amatitlan-de-1000-mts-en-3495-codigo-1599/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-amueblado-y-equipado-en-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-condominio-zona-10-2/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-en-san-lazaro-zona-15-guatemala/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-apartamento-amueblado-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-para-estrenar-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-condominio-zona-franca-en-km-29-5-carretera-al-pacifico/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-apartamento-de-2-habitaciones-amueblado-zona-15/", 
"https://puntourbanogt.com/propiedad/casa-de-330-m2-de-construccion-en-renta-fraijanes/", 
"https://puntourbanogt.com/propiedad/apartamento-de-122-m2-de-construccion-en-renta-zona-16/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-en-san-lucas-sacatepequez/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-en-zona-1/", 
"https://puntourbanogt.com/propiedad/casa-con-giro-comercial-en-renta-en-zona-1-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/apartamento-a-estrenar-en-renta-en-zona-14-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/en-alquiler-%f0%9f%93%a2-rento-apartamento-zona-14-edificio-casa-once-%f0%9f%8c%83/", 
"https://puntourbanogt.com/propiedad/%f0%9f%92%a5apartamento-en-renta-zona-11-parque-11-%f0%9f%8f%99%ef%b8%8f/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-apartamento-2-habitaciones-zona-15-vh1/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-carretera-a-el-salvador-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-vh1/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-16-3/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-oficina-c-c-de-zona-4-torre-ii/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-en-zona-10-3/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-16-kanajuyu/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-en-zona-10-2/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-en-el-cortijo-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-edificio-con-bodega-zona-4/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-edificio-comercial-en-zona-9/", 
"https://puntourbanogt.com/propiedad/en-renta-bodeguita-sobre-calzada-san-juan/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-zona-16-guatemala/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-en-centro-de-negocios-la-paz/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-escuintla/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-en-zona-10-5/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-parque-san-angel-zona-2/", 
"https://puntourbanogt.com/propiedad/apartamento-amoblado-en-renta-parque-san-angel-zona-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-nuevo-ideal-para-estudiantes-a-5-minutos-de-cayala/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-escuintla-de-1500-mts-en-7337-94-codigo-954/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-amatitlan-de-1700-mts-en-5252-64-codigo-1024/", 
"https://puntourbanogt.com/propiedad/edificio-completo-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-apartamento-de-2-dorm-zona-13-listo-para-estrenar/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-vistas-de-san-isidro-zona-16/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-terreno-comercial-en-zona-6/", 
"https://puntourbanogt.com/propiedad/en-renta-apartamento-nuevo-en-zona-15/", 
"https://puntourbanogt.com/propiedad/se-renta-local-area-food-court-centro-comercial-san-lucas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-5/", 
"https://puntourbanogt.com/propiedad/apartamento-nuevo-en-renta-en-el-maestro-zona-15/", 
"https://puntourbanogt.com/propiedad/local-en-alquiler-en-zona-15-de-70-mts2-en-1568-codigo-1143/", 
"https://puntourbanogt.com/propiedad/local-en-alquiler-en-zona-10-de-150-mts2-en-3000-codigo-1472/", 
"https://puntourbanogt.com/propiedad/en-renta-local-comercial-san-lucas-60-mtrs2/", 
"https://puntourbanogt.com/propiedad/apartamento%e2%80%afen%e2%80%afrenta-%e2%80%afventa%e2%80%afzona%e2%80%af10%e2%80%afoakland/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-14-2/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-10-de-400-metros-en-4944-codigo-1241/", 
"https://puntourbanogt.com/propiedad/ofi-amueblada-en-alquiler-en-z-14-de-262-mts-en-4270-codigo-348/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-exclusivo-aptoph-3-o-4-hab-3-banos-zona-14-edificio-torre-14/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-amueblado-en-zona-11/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-de-apartamento-amueblado-en-zona-16/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-nordic-zona-15/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-en-zona-9-3/", 
"https://puntourbanogt.com/propiedad/en-renta-hermoso-apartamento-de-dos-niveles-en-sector-cayala-zona-16/", 
"https://puntourbanogt.com/propiedad/en-renta-apartamento-en-nivel-alto-en-vista-hermosa-i/", 
"https://puntourbanogt.com/propiedad/oficina-amueblada-en-renta-zona-9/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-en-zona-9-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-apartamento-en-calzada-mateo-flores-zona-7/", 
"https://puntourbanogt.com/propiedad/edificio-en-renta-sobre-boulevard-los-proceres-zona-10/", 
"https://puntourbanogt.com/propiedad/local-en-renta-carretera-a-el-salvador-km-14-5/", 
"https://puntourbanogt.com/propiedad/townhouse-en-renta-de-3-habitaciones-en-zona-15/", 
"https://puntourbanogt.com/propiedad/local-en-renta-pinula-market-san-jose-pinula/", 
"https://puntourbanogt.com/propiedad/oficina-tabicada-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-apartamento-de-2-habitaciones-en-zona-15/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-san-antonio-carretera-a-el-salvador-2/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-en-col-toledo-zona-11/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-local-zona-10-frente-a-hospital-herrera-llerandi/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-avia-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-zona-10-las-delicias/", 
"https://puntourbanogt.com/propiedad/en-renta-ofibodega-con-mezzanine-puerto-san-jose-escuintla/", 
"https://puntourbanogt.com/propiedad/alquiler-apartamento-en-zona-15-el-maestro/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-zona-15-guatemala-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-centro-historico-zona-1/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-alquiler-zona-10-en-1200-de-2-dormitorios/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-alquiler-en-zona-10-en-2000-de-3-dormitorio-codigo-1561/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-a-5-min-de-cayala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-1/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-16/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-renta-zona-14/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-zona-7-acceso-inmediato-calzada-mateo-flores/", 
"https://puntourbanogt.com/propiedad/apartamento-tipo-loft-en-alquiler-zona-16-cayala/", 
"https://puntourbanogt.com/propiedad/townhouse-en-renta-en-zona-15-dentro-de-condominio/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-sobre-diagonal-6/", 
"https://puntourbanogt.com/propiedad/en-alquiler-propiedad-carretera-a-el-salvador-km-14-5/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-5/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-vh-1/", 
"https://puntourbanogt.com/propiedad/alquiler-de-casa-en-condominio-zona-10-diagonal-6/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-9-de-1000-mts-en-15680-codigo-1673/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-casa-en-villas-de-cantabria-zona-16/", 
"https://puntourbanogt.com/propiedad/en-alquiler-z-10-apartamento-amueblado/", 
"https://puntourbanogt.com/propiedad/apartamento-3-habitaciones-en-renta-sobre-avenida-las-americas/", 
"https://puntourbanogt.com/propiedad/alquiler-de-edificio-en-zona-9/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-apartamento-con-o-sin-muebles-en-torre-elgin-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-condominio-zona-10-3/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-zona-4-de-mixco-colonia-monte-verde/", 
"https://puntourbanogt.com/propiedad/precioso-apartamento-nuevo-en-renta-en-zona-10-amueblado/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-mariscal-zona-11/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-10-amueblado-de-1-dormitorio/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-14-en-3360-de-3-dormitorios-cod-1541/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-zona-10-con-garita/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-zona-16-en-condominio/", 
"https://puntourbanogt.com/propiedad/alquiler-citymax-gold-apartamento-tipo-loft-en-zona-4-guatemala/", 
"https://puntourbanogt.com/propiedad/alquiler-de-bodega-en-barcenas-villa-nueva/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-10-6/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-km-9-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-10-4/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-zona-10-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-de-3-habitaciones-zona-16/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-casa-en-km-8-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-10-5/", 
"https://puntourbanogt.com/propiedad/amplio-local-en-renta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-condominio-en-renta-en-zona-14-guatemala-3/", 
"https://puntourbanogt.com/propiedad/oficina-re-modelada-en-alquiler/", 
"https://puntourbanogt.com/propiedad/alquiler-de-oficina-en-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-apartamento-montesano-zona-16/", 
"https://puntourbanogt.com/propiedad/casa-en-condominio-en-renta-en-zona-14-guatemala-2/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-condominio-cercano-a-la-pradera-zona-14/", 
"https://puntourbanogt.com/propiedad/homepro-inmobiliaria-renta-apartamento-nuevo-en-nagano-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-amueblado-zona-14-edificio-villa-risho/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-nuevo-en-zona-12/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-vh2/", 
"https://puntourbanogt.com/propiedad/alquiler-apartamento-en-zona-10-tiffany-1/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-zona-12-de-350-mts-en-3780-codigo-1624/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-caes-edificio-scena/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-oficina-para-clinica/", 
"https://puntourbanogt.com/propiedad/oficina-amueblada-en-renta-en-zona-9/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-edificio/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-dubai-center-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-de-3-habitaciones-zona-14/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-bodega-zona-5/", 
"https://puntourbanogt.com/propiedad/amplia-oficina-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-en-condominio-de-muxbal/", 
"https://puntourbanogt.com/propiedad/edificio-comercial-en-alquiler-en-zona-9-guatemala/", 
"https://puntourbanogt.com/propiedad/edificio-completo-en-renta-en-zona-10-2/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-remodelada-en-santa-rosalia-km-12-5-ces/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-vh-1-2/", 
"https://puntourbanogt.com/propiedad/apartamento-amplio-en-alquiler-vista-hermosa-1-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-zona-15-guatemala-4/", 
"https://puntourbanogt.com/propiedad/local-en-renta-zona-6-capitalina/", 
"https://puntourbanogt.com/propiedad/rento-apartamento-de-3-habitaciones-con-terraza-en-zona-15/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-ofibodega-zona-12/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-renta-en-zona-10-3/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-apartamento-amueblado-renta-en-gravileas/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-zona-14-la-villa/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-casa-en-san-jose-pinula-doble-garita-de-seguridad/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-13-de-225-mts-en-1200-codigo-1545/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-9-de-155-mts-en-1350-codigo-1533/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-de-3-habitaciones-en-zona-10/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-escuintla-de-2000-mts-en-11550-codigo-1586/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-zona-13-de-2000-mts-en-20720-codigo-1585/", 
"https://puntourbanogt.com/propiedad/alquiler-de-apartamento-en-zona-10-3/", 
"https://puntourbanogt.com/propiedad/alquiler-de-oficina-amueblada-en-zona-9/", 
"https://puntourbanogt.com/propiedad/alquiler-de-ofi-bodega-en-zona-14/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-ofibodega-muxbal-carretera-salvador/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-10-3/", 
"https://puntourbanogt.com/propiedad/alquiler-de-oficina-en-zona-1/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-en-zona-12-2/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-alquiler-en-zona-10-dentro-de-oakland/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-alquiler-en-zona-12-dentro-de-complejo/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-san-isidro-zona-16/", 
"https://puntourbanogt.com/propiedad/homepro-inmobiliaria-renta-apartamento-en-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-16/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-apartamento-de-tres-habitaciones-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-vista-hermosa-1-en-renta/", 
"https://puntourbanogt.com/propiedad/citymax-gold-alquiler-de-apartamento-en-zona-16-para-estrenar/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-ofibodega-en-muxbal-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-14/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-km-30-carretera-al-pacifico/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-mixco-de-350-mts-en-3800-codigo-1537/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-calzada-atansio-de-250-mts-en-3758-codigo-1534/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-el-naranjo-zona-4-mixco/", 
"https://puntourbanogt.com/propiedad/casa-grande-en-renta-de-uso-comercial-en-ciudad-vieja-sac/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-en-senderos-del-comendador/", 
"https://puntourbanogt.com/propiedad/lindo-apartamento-en-renta-zona-15-en-q3500/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-san-felipe-de-jesus/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-11-las-charcas/", 
"https://puntourbanogt.com/propiedad/alquiler-apartamento-en-zona-11-las-charcas/", 
"https://puntourbanogt.com/propiedad/alquiler-de-casa-en-zona-16-residencial-la-colina/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-amueblada-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-colonia-el-maestro-zona-15/", 
"https://puntourbanogt.com/propiedad/bodega-showroom-en-renta-sobre-boulevard-el-naranjo/", 
"https://puntourbanogt.com/propiedad/en-alquiler-citymax-antigua-casa-amueblada-en-residencial-san-cristobal-el-bajo/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-10-alquilo-casa-para-oficinas-o-vivienda/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-con-o-sin-muebles-en-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-renta-de-oficina-amueblada-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-amueblado-en-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-condominio-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-20-calle-zona-10/", 
"https://puntourbanogt.com/propiedad/lindo-apartamento-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-renta-en-zona-14-4/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-14-la-villa/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-nave-carretera-salvador-para-estrenar-en-julio-2022/", 
"https://puntourbanogt.com/propiedad/rento-ofibodega-km-33-carretera-salvador-para-estrenar-en-junio/", 
"https://puntourbanogt.com/propiedad/homepro-inmobiliaria-renta-casa-en-santa-catarina-pinula/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-bodega-zona-3-de-mixco/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-nave-industrial-km-30-5-amatitlan-para-estrenar/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-ofibodega-en-muxbal/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-ofibodega-frente-al-irtra-zona-12/", 
"https://puntourbanogt.com/propiedad/apartamento-moderno-en-alquiler-zona-14-guatemala/", 
"https://puntourbanogt.com/propiedad/zona-12-la-reformita-alquilo-bodega-de-600-mts2-con-oficina/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-10-excelente-ubicacion-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-15-vista-hermosa-4/", 
"https://puntourbanogt.com/propiedad/citymax-gold-renta-local-comercial-sobre-avenida-las-americas/", 
"https://puntourbanogt.com/propiedad/local-en-renta-km-12-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-alquiler-en-zona-9-guatemala/", 
"https://puntourbanogt.com/propiedad/penthouse-en-renta-zona-14/", 
"https://puntourbanogt.com/propiedad/citymax-gold-alquila-bodega-cerca-a-calzadas-roosevelt-y-doroteo-guamuch/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-10-en-2200-de-3-dormitorios-codigo-1517/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-15-vista-hermosa-3/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-villa-canales/", 
"https://puntourbanogt.com/propiedad/casa-5-habitaciones-en-renta-condominio-san-antonio-ces/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-12-aguilar-batres-alquilo-local-comercial-de-173-metros/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-15-3/", 
"https://puntourbanogt.com/propiedad/alquiler-de-casa-en-zona-14-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-9-alquilo-oficina-de-60-mts2/", 
"https://puntourbanogt.com/propiedad/apartamento-amplio-en-renta-zona-14-guatemala/", 
"https://puntourbanogt.com/propiedad/local-en-renta-avenida-las-americas-zona-13/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-condominio-zona-14-guatemala/", 
"https://puntourbanogt.com/propiedad/en-alquiler-homepro-inmobiliaria-alquila-apartamento-en-zona-10/", 
"https://puntourbanogt.com/propiedad/mundo-inmobiliario-renta-amplia-oficina-en-zona-9/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-monte-real-z-4-mixco/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-zona-12-de-500-mts-en-5195-codigo-1562/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-11-excelente-ubicacion-2/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-renta-zona-16-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/local-en-renta-zona-12/", 
"https://puntourbanogt.com/propiedad/lindo-apartamento-en-renta-ancona-z1-de-mixco/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-zona-5-de-1000-mts-en-7064-4-codigo-1560/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-14-alquilo-apartamento-remodelado-226-mts2-2/", 
"https://puntourbanogt.com/propiedad/alquilo-apartamento-287mts2-ideal-diplomaticos-consulados-embajadas/", 
"https://puntourbanogt.com/propiedad/amplio-apartamento-de-lujo-en-renta-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-renta-la-villa-zona-14-guatemala/", 
"https://puntourbanogt.com/propiedad/villas-granada-premium-apto-en-renta/", 
"https://puntourbanogt.com/propiedad/ofibodega-de-200mt2-en-renta-zona-7-capitalina/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-en-centro-de-negocios-la-paz-calzada-la-paz/", 
"https://puntourbanogt.com/propiedad/apartamento-de-100-m2-de-construccion-en-renta-zona-09/", 
"https://puntourbanogt.com/propiedad/local-en-zona-1-en-alquiler-ideal-almacen-sala-de-ventas-etc/", 
"https://puntourbanogt.com/propiedad/local-de-84-636-m2-de-construccion-en-renta-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-amoblado-zona-14-en-renta/", 
"https://puntourbanogt.com/propiedad/zona-10-villalar-alquilo-apartamento-de-3-dormitorios-258-mts2/", 
"https://puntourbanogt.com/propiedad/lindo-apartamento-en-alquiler-en-zona-13-amueblado/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-15-las-hadas-apartamento-294-mts-3-dormitorios/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-9/", 
"https://puntourbanogt.com/propiedad/apartamento-renta-en-zona-10-moderno/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-12-guatemala/", 
"https://puntourbanogt.com/propiedad/alquilo-apartamento-completamente-amueblado-y-equipado-en-zona-4/", 
"https://puntourbanogt.com/propiedad/alquilo-casa-ideal-para-oficina-fuera-de-garita-zona-14-la-villa/", 
"https://puntourbanogt.com/propiedad/oficina-de-140-m2-de-construccion-en-renta-zona-15/", 
"https://puntourbanogt.com/propiedad/mundo-inmobiliario-renta-apartamento-en-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-de-300-m2-de-construccion-en-renta-zona-14/", 
"https://puntourbanogt.com/propiedad/en-alquiler-local-de-43-80-m2-de-construccion-en-zona-9/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-11-las-charcas/", 
"https://puntourbanogt.com/propiedad/local-de-78-4-m2-de-construccion-en-renta-zona-09/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-10-alquilo-casa-fuera-de-garita-para-oficinas-o-vivienda/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-9-alquilo-oficina-amueblada-de-145-mts2-en-aristos/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-oakland-zona-10-guatemala-4/", 
"https://puntourbanogt.com/propiedad/oficinas-en-renta-en-el-naranjo/", 
"https://puntourbanogt.com/propiedad/ofibodegas-en-renta-en-el-naranjo/", 
"https://puntourbanogt.com/propiedad/zona-10-vendo-o-alquilo-apartamento-2-dormitorios-remodelado/", 
"https://puntourbanogt.com/propiedad/zona-10-apartamentos-de-lujo-para-estrenar-242-mts2/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/ofibodega-de-204-mt2-en-renta-naranjo-zona-4-de-mixco/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-14-alquilo-apartamento-de-300-mts2/", 
"https://puntourbanogt.com/propiedad/apartamento-de-lujo-amueblado-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/alquiler-de-apartamento-en-quo-zona-4-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-para-estrenar-en-zona-14/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-16-cayala-alquilo-apartamento-de-230-mts2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-15-botticelli-1-apartamento-de-300-metros/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-apartamento-de-lujo-amueblado-en-zona-10-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-10-alquilo-oficina-de-81-mts-2/", 
"https://puntourbanogt.com/propiedad/casa-de-144-m2-de-construccion-en-renta-zona-02-2/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-alquiler-zona-10-en-1300-de-3-dormitorios/", 
"https://puntourbanogt.com/propiedad/apartamento-de-2-dormitorios-en-renta-en-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-4/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-amueblada-residencial-dona-victoria-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/zona-10-alquilo-casa-fuera-de-garita-para-oficina-o-vivienda/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-10-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-14-apartamento-240-mts2-vista-a-los-volcanes/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-3/", 
"https://puntourbanogt.com/propiedad/bodega-de-358-45-m2-de-construccion-en-renta-san-cristobal/", 
"https://puntourbanogt.com/propiedad/apartamento-de-234-m2-de-construccion-en-renta-zona-10-2/", 
"https://puntourbanogt.com/propiedad/apartamento-de-122-m2-de-construccion-en-renta-zona-15/", 
"https://puntourbanogt.com/propiedad/apartamento-de-234-m2-de-construccion-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/habitacion-en-semi-amueblado-en-renta-zona-9/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/townhouse-en-renta-en-zona-13/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-en-venta-en-zona-15/", 
"https://puntourbanogt.com/propiedad/locales-en-renta-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/en-renta-complejo-empresarial-pacifico-sur/", 
"https://puntourbanogt.com/propiedad/citymax-gold-renta-apartamento-en-viu-zona-16/", 
"https://puntourbanogt.com/propiedad/alquiler-de-oficina-en-edificio-en-caes-km-16-5/", 
"https://puntourbanogt.com/propiedad/alquiler-de-ofibodega-en-zona-12/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-de-03-dormitorios-en-zona-15/", 
"https://puntourbanogt.com/propiedad/en-alquiler-citymax-gold-alquila-bodega-en-la-villa-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-listo-para-estrenar-en-zona-15/", 
"https://puntourbanogt.com/propiedad/alquiler-de-local-comercial-en-zona-1-de-boca-del-monte/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-apartamento-en-el-cafetal-antigua/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-renta-boca-del-monte/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-15-2/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-carretera-al-salvador/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-en-san-lucas-sacatepequez/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-10-de-300-mts-en-6106-codigo-1535/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-9-de-175-mts-en-1410-codigo-1488/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-14-en-1904-de-2-dormitorios-codigo-1540/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-km-9-5-carretera-a-el-salvador-altos-de-montebello/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-14-en-3360-de-3-dormitorios-codigo-1539/", 
"https://puntourbanogt.com/propiedad/citymax-gold-renta-apartamento-en-zona-15-colonia-el-maestro/", 
"https://puntourbanogt.com/propiedad/alquiler-de-apartamento-en-zona-12/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-ciudad-san-cristobal-mixco/", 
"https://puntourbanogt.com/propiedad/citymax-gold-alquiler-apartamento-san-isidro-zona-16/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/rento-preciosa-casa-amueblada-en-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/en-alquiler-oficina-zona-9-alquilo-propiedad-con-amplio-parqueo/", 
"https://puntourbanogt.com/propiedad/local-en-renta-en-plaza-comercial-zona-9/", 
"https://puntourbanogt.com/propiedad/oficina-en-renta-edificio-crece-naranjo/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-11-alquilo-local-comercial-de-290-mts2-para-estrenar/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-amueblada-san-lucas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-14-de-3-habitaciones/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-apartamento-de-272-m2-para-estrenar-en-zona-14/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-en-san-miguel-duenas/", 
"https://puntourbanogt.com/propiedad/oficina-amueblada-en-renta-en-zona-4/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-14-alquilo-apartamento-de-3-habitacion-con-c-servicio/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-casa-zona-10-fuera-de-garita-ideal-oficinas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-15-4/", 
"https://puntourbanogt.com/propiedad/casa-en-venta-y-renta-en-zona-16/", 
"https://puntourbanogt.com/propiedad/local-de-812-m2-de-construccion-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-en-el-naranjo/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-villa-alcantara-ciudad-vieja/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-amplia-fuentes-del-valle-san-miguel/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-15-en-vista-hermosa-1/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-14-5/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-renta-casa-amueblada-en-antigua-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-10-amueblado/", 
"https://puntourbanogt.com/propiedad/citymaxgold-renta-de-apartamento-en-santa-catarina-pinula/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-10-amueblado/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-en-puerta-parada/", 
"https://puntourbanogt.com/propiedad/en-alquiler-citymax-alquila-vende-casa-en-puerta-parada-caes/", 
"https://puntourbanogt.com/propiedad/citymax-gold-alquiler-de-casa-en-puerta-parada/", 
"https://puntourbanogt.com/propiedad/alquiler-de-oficina-256mts-en-zona-13/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-casa-grande-en-residencial/", 
"https://puntourbanogt.com/propiedad/alquiler-de-oficina-en-edificio-zona-9/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-de-2-dormitorios-en-zona-16/", 
"https://puntourbanogt.com/propiedad/alquiler-de-apartamento-en-zona-5-ciudad-guatemala/", 
"https://puntourbanogt.com/propiedad/en-alquiler-rento-edificio-de-oficinas-en-plaza-comercial-zona-12/", 
"https://puntourbanogt.com/propiedad/alquiler-bodega-showroom-el-naranjo/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-condominio-villa-canales/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-zona-14-de-3-habitaciones-edificio-tadeus/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-zona-14-de-3-habitaciones/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-12/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-14-la-villa-alquilo-apartamento-de-1-dormitorio-fuera-de-garita/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-vista-hermosa-1-zona-15-guatemala/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-tiffany-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-de-lujo-en-renta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/en-alquiler-km-8-ces-apartamento-2-dormitorios-maderos-ii/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-14-en-de-3700-dormitorio-codigo-1566/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-alquiler-en-zona-9/", 
"https://puntourbanogt.com/propiedad/citymax-antigua-casa-independiente-y-grande-en-renta-en-santa-lucia-milpas-altas/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-10-apartamento-amueblado-2-dormitorios-135-mts2-5/", 
"https://puntourbanogt.com/propiedad/oficinas-en-renta-zona-pradera-zona-10/", 
"https://puntourbanogt.com/propiedad/en-alquiler-ganga-oficinas-virtuales/", 
"https://puntourbanogt.com/propiedad/bodega-en-alquiler-en-zona-7-de-350-mts-en-2391-2-codigo-1568/", 
"https://puntourbanogt.com/propiedad/local-comercial-en-alquiler-en-zona-12/", 
"https://puntourbanogt.com/propiedad/zona-10-apartamento-2-dormitorios-cerca-a-fontabella-y-oakland-mall/", 
"https://puntourbanogt.com/propiedad/zona-10-alquilo-apartamento-3-dormitorios-en-joyas-de-florencia/", 
"https://puntourbanogt.com/propiedad/ofibodega-en-renta-avenida-petapa/", 
"https://puntourbanogt.com/propiedad/oficina-de-35-m2-de-construccion-en-renta-zona-04/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-zona-14-2/", 
"https://puntourbanogt.com/propiedad/ancona-apartamento-en-renta-final-de-calzada-roosevelt/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-16-apartamento-en-esq-con-bulevard-kanajuyu-zona-16/", 
"https://puntourbanogt.com/propiedad/zona-10-alquilo-apartamento-de-1-dormitorio/", 
"https://puntourbanogt.com/propiedad/oficina-de-183-m2-de-construccion-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/lindo-apartamento-ambueblado-en-renta-ancona-zona-1-de-mixco/", 
"https://puntourbanogt.com/propiedad/zona-16-cayala-alquilo-apartamento-3-dormitorios/", 
"https://puntourbanogt.com/propiedad/alquiler-de-casa-en-zona-14/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-en-la-comunidad-mixco/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-condominio-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-15-vista-hermosa-1-3/", 
"https://puntourbanogt.com/propiedad/en-alquiler-km-18-a-san-jose-pinula-alquilo-bodegas-de-350-mts-3/", 
"https://puntourbanogt.com/propiedad/apartamento-de-2-dormitorios-en-renta-en-zona-10-3/", 
"https://puntourbanogt.com/propiedad/en-alquiler-alquilo-apartamento-287mts2-ideal-diplomaticos-consulados-embajadas/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-10-14/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-10-5/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-en-zona-13/", 
"https://puntourbanogt.com/propiedad/en-alquiler-casa-en-venta-acceso-final-20-calle-zona-10-la-brecha-y-ces/", 
"https://puntourbanogt.com/propiedad/akari-apartamento-en-renta-en-zona-2-de-mixco-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-10-casa-sobre-20-calle-con-6-parqueos/", 
"https://puntourbanogt.com/propiedad/oficina-de-60-m2-de-construccion-en-renta-zona-15-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-casa-amplia-en-la-reformita-zona-12-ideal-para-empresa-oficina/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-11-mariscal/", 
"https://puntourbanogt.com/propiedad/alquiler-apartamento-edificio-atelier/", 
"https://puntourbanogt.com/propiedad/apartamento-nuevo-en-renta-en-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-de-123-m2-de-construccion-en-renta-zona-15-2/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-en-carretera-a-el-salvador-km-25/", 
"https://puntourbanogt.com/propiedad/casa-en-renta-km-12-5-condominio-santa-rosalia-mundo-inmobiliario/", 
"https://puntourbanogt.com/propiedad/casa-de-385-m2-de-construccion-en-renta-zona-10/", 
"https://puntourbanogt.com/propiedad/ofibodegas-en-renta-en-xela/", 
"https://puntourbanogt.com/propiedad/bodega-en-renta-sobre-20-calle-zona-10/", 
"https://puntourbanogt.com/propiedad/casa-en-alquiler-en-zona-15-de-3-dormitorios-en-1400-codigo-1531/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-alquiler-en-cayala-en-3500-de-3-dormitorios/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-amueblado-villas-granada-premium/", 
"https://puntourbanogt.com/propiedad/oficinas-en-renta-en-zona-9/", 
"https://puntourbanogt.com/propiedad/local-en-alquiler-en-zona-1-para-almacen-sala-de-ventas-etc/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-en-alquiler-en-zona-13/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-13-mundo-inmobiliario-2/", 
"https://puntourbanogt.com/propiedad/apartamento-en-alquiler-en-zona-9-amueblado/", 
"https://puntourbanogt.com/propiedad/apartamento-amueblado-tipo-loft-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-en-renta-zona-7-gt/", 
"https://puntourbanogt.com/propiedad/bodega-de-350mts-en-alquiler-km-18-a-san-jose-pinula-2/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-10-de-300-mts-en-4924-codigo-1476/", 
"https://puntourbanogt.com/propiedad/oficina-en-alquiler-en-zona-10-de-180-mts-en-2000-codigo-1447/", 
"https://puntourbanogt.com/propiedad/casa-de-142-m2-de-construccion-en-renta-santa-catarina-pinula/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-14-lujoso-apartamento-en-tadeus/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-14-vivaldi-alquilo-apartamento-2-dormitorios-amueblado-3/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-para-estrenar-en-zona-15/", 
"https://puntourbanogt.com/propiedad/oficina-de-67-54-m2-de-construccion-en-renta-zona-15/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-de-137-018-m2-de-construccion-en-venta-zona-14/", 
"https://puntourbanogt.com/propiedad/apartamento-de-90-m2-de-construccion-en-renta-zona-04/", 
"https://puntourbanogt.com/propiedad/apartamento-de-118-m2-de-construccion-en-renta-zona-10-2/", 
"https://puntourbanogt.com/propiedad/mundo-inmobiliario-renta-casa-carretera-a-el-salvador/", 
"https://puntourbanogt.com/propiedad/apartamento-de-2-dorm-en-renta-en-zona-10/", 
"https://puntourbanogt.com/propiedad/apartamento-de-1-dormitorio-en-renta-en-zona-10-3/", 
"https://puntourbanogt.com/propiedad/alquiler-de-apartamento-amueblado-en-zona-4/", 
"https://puntourbanogt.com/propiedad/villas-granada-premium-apto-en-renta-2/", 
"https://puntourbanogt.com/propiedad/en-alquiler-zona-9-alquilo-oficina-amueblada-145-mts2-en-aristos/", 
"https://puntourbanogt.com/propiedad/en-alquiler-apartamento-1-dormitorio-amueblado-81-mts2-zona-14-cobella/", 

]
# Captures data for a specific page with provided url
def load_urls(pageUrl):

    print("Getting page: {} - Items: {}".format(pageUrl.split("page/")[1], len(urls)))
    print("------------------------------------------------------------------------")

    source = requests.get(url=pageUrl, allow_redirects=True, headers={  'User-Agent': "PostmanRuntime/7.28.4" })

    soup = bs.BeautifulSoup(source.text, "html.parser")

    items = soup.find_all("div", {"class": "rh_list_card__wrap"})

    for item in items:
        url = item.find("a", href=True)['href']
        with open("./scan-{}.txt".format(date.today()), "a") as scan:
                scan.writelines("\"{}\", \n".format(str(url)))
                scan.close()


# Captures data for a specific entry/item with provided url
def load_item_data(item_url):
    print("loading {}".format(item_url))
    source = requests.get(url=item_url,  allow_redirects=True, headers={  'User-Agent': "PostmanRuntime/7.28.4" })

    soup = bs.BeautifulSoup(source.text, "html.parser")


    mt2 = "none"
    sector = "none"
    precio = "none"
    habitaciones = "none"
    banos = "none"
    parqueos = "none"
    nombre_agente = "none"
    numero_agente = "latest"



    try:
        sector = soup.find("nav", {"class": "property-breadcrumbs"}).find_all("li")[2].find("a").get_text()
    except (IndexError, AttributeError):
        pass

    try:
        precio = soup.find("div", {"class": "rh_page__property_price"}).find("p", {"class": "price"}).get_text()
    except (IndexError, AttributeError):
        pass

    try:
        habitaciones = (
            soup.find("div", {"class": "rh_property__meta prop_bedrooms"}).find("span", {"class": "figure"}).get_text()
        )
    except (IndexError, AttributeError):
        pass

    try:
        banos = soup.find("div", {"class": "rh_property__meta prop_bathrooms"}).find("span", {"class": "figure"}).get_text()
    except (IndexError, AttributeError):
        pass

    try:
        parqueos = soup.find("div", {"class": "rh_property__meta prop_garages"}).find("span", {"class": "figure"}).get_text()
    except (IndexError, AttributeError):
        pass

    try:
        mt2 = soup.find("div", {"class": "rh_property__meta prop_area"}).find("span", {"class": "figure"}).get_text()
    except (IndexError, AttributeError):
        pass

    item = {
        "eventType": "index_item",
        "available_timestamp": str(date.today()),
        "id": item_url,
        "url": item_url,
        "module": "puntourbanogt-gt",
        "mt2": mt2.strip(),
        "sector": sector.strip(),
        "precio": precio.strip(),
        "habitaciones": habitaciones.strip(),
        "banos": banos.strip(),
        "parqueos": parqueos.strip(),
        "nombre_agente": nombre_agente.strip(),
        "numero_agente": numero_agente.strip(),
        "type": "rent",
        "extras": [{"parent": "Comodidades", "fields": [{"name": "Piscina"}]}],
    }

    laraIndex(item)


def get():

    p = Pool(10)
    p.map(load_urls, urls_list)
    p.terminate()
    p.join()


def data():
    d = Pool(100)
    d.map(load_item_data, urls)
    d.terminate()
    d.join()


# get()
data()
